### ISSUE TITLE
TMC Parameter has no effect

### ISSUE THREAD

**Issue by MichaelAdolph** [RWTH-EBC/AixLib#100]
In Building.HighOrder.Rooms.MFD.CellarAtttic.Cellar and .Attic_Ro2Lf1 the parameter TMC can be set but has no effect as it is not used anywhere further down the code.

I'd suggest deleting these parameters to avoid any confusion. At least I would comment them as long as they are not used (if usage is intended in further releases).

**Comment by mlauster** [comment]
@MichaelAdolph, did you already solved this or is it still an open issue?

**Comment by MichaelAdolph** [comment]
I put that up for discussion - and as nobody disagreed put it on my to do list.
Thanks to the last merge I'll have to update the other pull requests anyway and also take care of this issue within the next days.

**Comment by MichaelAdolph** [comment]
Pullrequest #105 should solve this problem

**Comment by AnaConstantin** [comment]
Solved.
