### ISSUE TITLE
Optional pump in SimpleConsumer

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#1000]
**What is the problem?**

 * In some cases it is useful to integrate the pump directly into the consumer (especially for bigger non residential buildings).

**How do we want to solve it? Describe the solution you'd like**
* Optional integration of a pump that provides a prescibred m_flow. 
* the massflow m_flow will be regulated by a PI-Controller or an equation based on  Q_flow/(cp*dT_nom) 
* therefore an optional dT_nom will be integrated into the model

**Comment by XucYin** [comment]
@DaJansenGit Maybe it can be an issue for the hackday?

**Comment by DaJansenGit** [comment]
Unfortunately I won't be able to address this issue this hackday, but I will keep it in mind :)

**Comment by MartinRaetz** [comment]
@DaJansenGit 
Did you have the time to continue?
Should this issue stay active?

**Comment by DaJansenGit** [comment]
@Achim1997 is currently working on this. I think this will be included in the next weeks.
