### ISSUE TITLE
Automatic creation of missing reference files

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#1001]
**What is the problem?**

Create a new reference file for the regression tests, if the corresponding Mos script exists. 

**How do we want to solve it?**

With the help of the GitLab CI, the missing reference file is created when creating a pull request and pushed into the working branch

**Comment by PMehrfeld** [comment]
@SvenHinrichs : Is this closed by #1002? Than [the branch](https://github.com/RWTH-EBC/AixLib/pull/1056) can be deleted and this issue can be closed.

**Comment by SvenHinrichs** [comment]
@PMehrfeld : yes, this issue is solved. I delete the issue and the branch now.
