### ISSUE TITLE
Naming in Building.HighOrder.House.MFD.EnergySystem.OneAppartment.Radiators inconsistent

### ISSUE THREAD

**Issue by MichaelAdolph** [RWTH-EBC/AixLib#101]
The naming of the radiators is not consistent throughout the code, e.g. radiatorKitchen but radiator_bath, the child's radiator is called radiatorCorridor.

With respect to the rest of the code I'd rename the radiators to "radiators_whateverroom" if nobody objects

**Comment by marcusfuchs** [comment]
Sorry to object here: I think radiatorRoom would be more coherent with the Modelica Naming Conventions: https://build.openmodelica.org/Documentation/Modelica.UsersGuide.Conventions.ModelicaCode.Naming.html

**Comment by MichaelAdolph** [comment]
True, but than I'd have to ask myself if I'm going to fix the other names too or resist my urge to be pedantic.

**Comment by MichaelAdolph** [comment]
Well for some reason Pullrequest #102 doesn't show up here. Anyway, I took the rather pedantic way. I guess some of you can appreciate this

**Comment by MichaelAdolph** [comment]
Issue solved and merged into master
