### ISSUE TITLE
Division by zero error in valve models when using BaseClasses.PartialTwoWayValveKv

### ISSUE THREAD

**Issue by LauraMaier** [RWTH-EBC/AixLib#1018]
**1. The Problem/Bug**

When using AixLib.Fluid.Actuators.BaseClasses.PartialTwoWayValveKv or AixLib.Fluid.Actuators.BaseClasses.PartialTwoWayValve as base class within the valve models (e.g. if you don´t use a specific valve data set), model errors occur. The following valve models are affected (among maybe others):

- AixLib.Fluid.Actuators.Valves.TwoWayEqualPercentage

- AixLib.Fluid.Actuators.Valves.TwoWayLinear

- AixLib.Fluid.Actuators.Valves.TwoWayPolynomial

- AixLib.Fluid.Actuators.Valves.TwoWayPressureIndependent

- AixLib.Fluid.Actuators.Valves.TwoWayQuickOpening

- AixLib.Fluid.Actuators.Valves.TwoWayTable

**2. How will I fix the problem?**

In the IBPSA library a minimum value of 0.1*leakage rate was given for phi. This way, division by zero is prevented.

**Comment by PMehrfeld** [comment]
@LauraMaier : So it is related to this [issue here](https://github.com/ibpsa/modelica-ibpsa/issues/1376)? And we only need a next IBPSA merge?

**Comment by PMehrfeld** [comment]
@LauraMaier : So it is related to this [issue here](https://github.com/ibpsa/modelica-ibpsa/issues/1376)? And we only need a next IBPSA merge?
