### ISSUE TITLE
ROM - centralize "totalPersons" and other parameter

### ISSUE THREAD

**Issue by MartinRaetz** [RWTH-EBC/AixLib#1049]
**What is the problem?**
In the reduced order model are many parameter that are set manually (hard coded) within different models, such as:

- [ ] body surface (used in:

- AixLib.BoundaryConditions.InternalGains.CO2.CO2Balance
- AixLib.BoundaryConditions.InternalGains.Humans.HumanTotalHeatTemperatureDependent
- AixLib.BoundaryConditions.InternalGains.Humans.HumanSensibleHeatTemperatureDependent

- [ ] 1 Met = 58.2 W/m² (used in:

- AixLib.BoundaryConditions.InternalGains.CO2.CO2Balance
- AixLib.BoundaryConditions.InternalGains.Humans.HumanTotalHeatTemperatureDependent
- AixLib.BoundaryConditions.InternalGains.Humans.HumanSensibleHeatTemperatureDependent

There are also variables that should be centralized:

- [ ] total number of people (currently calculated in:

- AixLib.BoundaryConditions.InternalGains.CO2.CO2Balance
- AixLib.BoundaryConditions.InternalGains.Humans.BaseClasses.PartialHuman

**How do we want to solve it? Describe the solution you'd like**

Parameter into zoneParams?

Variables calculated centrally and distributed via connectors.
-> e.g. real output "totalPersons" from AixLib.BoundaryConditions.InternalGains.Humans.BaseClasses.PartialHuman and connect it to the co2 model, or more models that might be affected.

**Describe alternatives you've considered**
1. Leave it like it is.

2. directly calculate "totalPersons" in Multizone and adapt PartialHuman respectively -> possibly do the same for machines and lighting to have equal formats

**Additional context**

- [x] discuss in modelica group

**Comment by KremerMartin** [comment]
@MartinRaetz I would disagree in agglomerating the parameters into the zone params. These parameters are strongly connected to the internal gains, not the zone in which the gains occur. As I see it, we could summarize the parameters body surface and 1 Met in the `PartialHuman` model.
Maybe we could introduce an additional partial model having only the parameters described here, from which the `PartialHuman` and `CO2Balance` are extended. But I personally think, that this is a little bit overengineered.

**Comment by MartinRaetz** [comment]
I agree. After our discussion we conclude that the best way would be:

1. PartialHuman:
As a data storage for all human-related constants: A_body, MET=58, 
Possibly calculate the number of persons per zone here.

2. Human -> extends from PartialHuman
Conditional for: heat calc 1, heat calc 2, moisture, co2 (kg/s)

outside of human
- balance for co2 (incl. ACH etc.) (see the implementation for moisture)

 
After all, we think this might be over-engineering. Maybe for a Hack-Day?

**Comment by MartinRaetz** [comment]
As mentioned before, the benefit of such a restructuring process would not justify the workload. 
It is better to focus on more important issues.
