### ISSUE TITLE
Problems with Ashrea Weatherfile

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#1060]
Thanks to the new weatherfile copy implementation of @MartinRaetz in Teaser (https://github.com/RWTH-EBC/TEASER/pull/664), we recognized that the current Ashrea weatherfile for Thermalzones\ROM\Verification is not working as expected.

With the given file, there is no simulation possible.

@MartinRaetz will figure out what could be a solution, but it seems that either the keyword ATTENTION in the comments section of the weatherfile or the length of the comments line in the weatherfile seems to make problems.

Did one of you every run into problems regarding weather files comment sections or lengths? 

For further comparison between a weatherfile which works and one which does not work, you can see here the difference between the Ashrea weatherfile and the mannheim weatherfile https://www.textcompare.org/index.html?id=5fc6807b2d59400017cf4d88

**Comment by MartinRaetz** [comment]
One line in the Weather file seems to be too long. I added a line break, see: https://github.com/RWTH-EBC/TEASER/pull/664/commits/6e8977cbd2f29ee2f08dd3bdc34e66eb497fd6b2

With this configuration, it works.

For finishing this Issue:
- [ ] Change weather file in AixLib

- [ ] Change weather file in Teaser (done here: https://github.com/RWTH-EBC/TEASER/pull/664/commits/6e8977cbd2f29ee2f08dd3bdc34e66eb497fd6b2)

**Comment by MartinRaetz** [comment]
Branch: https://github.com/RWTH-EBC/AixLib/tree/issue1060_weather_file_ASHRAE

**Comment by MartinRaetz** [comment]
@MichaMans, is there anything left open to do?

Otherwise I would merge the https://github.com/RWTH-EBC/AixLib/pull/1061 and close both of the related branches: 
Branch: https://github.com/RWTH-EBC/AixLib/tree/issue1060_weather_file_ASHRAE
Branch: https://github.com/RWTH-EBC/AixLib/tree/issue1060_ahreaweatherfile

**Comment by MichaMans** [comment]
@MartinRaetz I think if the checks passes in #1061 we can merge and delete the related branches! Thank you
