### ISSUE TITLE
Error at startup and default libraries partially loaded

### ISSUE THREAD

**Issue by 0penBrain** [RWTH-EBC/AixLib#1068]
I had a vanilla OpenModelica (Release version) installed from quite a long time on Kubuntu 18.04 (Bionic) and it used to work correctly when I tested it some months ago.
Maybe an upgrade broke something, but now when I'm running it I get 2 error messages at startup :

> [2] 00:45:49 Ecriture Erreur
> Failed to load package Modelica (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/USER/.openmodelica/libraries/.
> 
> [4] 00:45:49 Ecriture Erreur
> Failed to load package ModelicaReference (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/USER/.openmodelica/libraries/.

While I used to get much libraries such as mechanical, electrical, ... now only 'OpenModelica' lib is loaded (so nothing really usable actually).
I had a look into the 2 folders of MODELICAPATH : 1st doesn't exist, and 2nd just contains 'index.json'.
I searched for things like "Modelica.mo" or "ModelicaReference.mo" on my drive and can't find anything.
I tried to purge everything and reinstall, but it's exactly the same situation.
I tried to install libs with 'installPackage' as told in the message view but it just says 'False'.
Now I'm stuck and have strictly no more clue how I could be back to a working install...

**Comment by LauraMaier** [comment]
@Maghnie Maybe this is something for you as it is linked to your issue #1076 regarding OpenModelica compatibility?

**Comment by Maghnie** [comment]
After a quick skim-through, this issue seems to be with the OpenModelica installation itself and not AixLib per se. But I can take a closer look during the hackday.

**Comment by 0penBrain** [comment]
OK, I admittedly didn't check for a while now and did now. Things seems to be far better as I got a message at startup (see below) and after choosing 'Load MSL 4.0.0' I'm back with the libs I used to have
![om](https://user-images.githubusercontent.com/48731257/117295587-5165d680-ae74-11eb-85a3-b210ee87fc50.png)

One of the 2 errors are gone and only the below one is remaining (which is a bit annoying, nothing more) :
> Failed to load package ModelicaReference (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/USER/.openmodelica/libraries/.

Feel free to ask if I may be of any help

**Comment by Maghnie** [comment]
Thanks 0penBrain for the update. I'm glad the blocking errors were worked out. 

It does seem like an OpenModelica-specific issue, so the folks at [OpenModelica](https://github.com/OpenModelica/OpenModelica/issues) could benefit from the user feedback in the future. 

For anyone else having OpenModelica installation issues, we can for now just recommend making sure all the installation commands for Linux are executed, including the one for "[Installing Modelica libraries](https://openmodelica.org/download/download-linux)". If a library-import issue specific to AixLib still pops up, please let us know. 🙂
