### ISSUE TITLE
issue1078_ automatic IBPSA merge 

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#1079]
**What is the problem?**
- the IBPSA merge should be performed automatically with the CI

**How do we want to solve it?**

When creating the branch IBPSA_Merge from the development branch, a template is automatically activated which fulfils the following functions:

- The Python script mergeModelicaIBPSA.py . is executed. 
- A new AixLib conversion script is created from the latest IBPSA conversion script.
- The whitelist is updated for the CI Check
- A pull request is created with the new IBPSA version, which performs all CI tests  
- Creating a release from the new version

**Comment by DaJansenGit** [comment]
The majority of the work is done I think and its already tested with a merge into the current development branch. In #1125  two small bugs are mentioned. When this is solved and merged into dev, we can close this issue.

**Comment by DaJansenGit** [comment]
closed with #1132
