### ISSUE TITLE
Replace old heat pump model in example GeothermalHeatPumpBase

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#1093]
**What is the problem?**

The example `Fluid.Examples.GeothermalHeatPump.BaseClasses.GeothermalHeatPumpBase` uses the obsolete model `AixLib.Obsolete.Year2019.Fluid.HeatPumps.HeatPumpSimple`. 
The example seems to be actually not a bad one, showing some kind of complex example including a rudimentary heat pump control. 
Thus, I would avoid deleting the example.

**How do we want to solve it? Describe the solution you'd like**

- [x] Decide for important outputs and add simulate-and-plot script
- [x] Change class of heat pump to one of the existing heat pump classes
- [x] Preserve simulation results of outputs of interest as much as possible. Since so far no baseline exists, receiving different results due to class exchange is okay.
- [x] Add reference results

**Comment by LauraMaier** [comment]
@PMehrfeld and @FWuellhorst: What is the current status of this issue? Maybe something for the hackday? :-)

**Comment by FWuellhorst** [comment]
I started working on this, #1092 and #912, nearly finishing all three. I will try my best to open a PR today. As I'm busy tomorrow, sadly I won't attend the hackday.
