### ISSUE TITLE
Missing file "./Tables/J1615/UserProfilesOffice.txt"

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#110]
The table file UserProfilesOffice.txt cannot be found in the repository.

**Comment by PRemmen** [comment]
@tbeu could you specify where your need this file. I couldn't find where it is used in the code.

**Comment by tbeu** [comment]
Just search for UserProfilesOffice.txt. It gives 40 hits in 24 files, e.g., AixLib.Building.LowOrder.Examples.Validation.VDI6007.Linear.TestCase1.mo.

**Comment by tbeu** [comment]
Please not that Modelica.Utilities.Files.loadResource must always be used for Modelica URIs passed as fileName to CombiTimeTable as fixed in #109.

**Comment by PRemmen** [comment]
Thanks.
This was an unused default value of an outdated version. So I just replaced the value with Modelica default value. You don't need this file to simulate the Validation examples.

**Comment by tbeu** [comment]
Ah, I see now. It was set but not used.

**Comment by PRemmen** [comment]
Merged and can be closed. Thanks @tbeu
