### ISSUE TITLE
Accidentaly broken diagrams

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#112]
@MichaelAdolph, I am afraid with your commit https://github.com/RWTH-EBC/AixLib/commit/53587f5dc9cef693d016eb9a7edb419dd1900060 you broke quite a lot of the diagrams. Could you please fix this?

**Comment by tbeu** [comment]
LinePattern.None should be removed from connects by default but not globally.

**Comment by MichaelAdolph** [comment]
fixed, see pull request

**Comment by marcusfuchs** [comment]
That was pull request #122, changes are on the master now.

**Comment by thorade** [comment]
I am afraid that with pull request #98 (for issue #97) I also broke some diagrams.
That also has to be reverted partially.

**Comment by MichaelAdolph** [comment]
maybe, but from (a rather superficial) first look most file names look common to me.
So I guess, I got you covered. At least for most of the

**Comment by MichaelAdolph** [comment]
I tried to understand what happend. Somehow the changes from  pull request #98 entered my branch that I than accidentally merged into the master. So with this pull request we should be fine again (except 1-20 mistakes I made while manually reverting).

I'll reference this issue next time if somebody tells me, it was my fault ;)
