### ISSUE TITLE
Refactor confusing names of heat pump safety models

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1128]
The current heat pump controllers have two OnOff models: One to control the compressor, one that decides if operation is safe. 

Refactoring to avoid confusing is necessary. Any ideas for different names?

Affected models:
- `AixLib.Controls.HeatPump.BaseClasses.OnOffHP`
- `AixLib.Controls.HeatPump.HPControllerOnOff`
- `AixLib.Controls.HeatPump.SafetyControls.OnOffControl`

**Comment by tobinfiedler** [comment]
@FWuellhorst Is this issue still current?

**Comment by FWuellhorst** [comment]
I will use TwoPoint Controlled Heat Pump as a name
