### ISSUE TITLE
Add TRY Weatherdata for Aachen

### ISSUE THREAD

**Issue by phillipstoffel** [RWTH-EBC/AixLib#1135]
Is your feature request related to a problem? Please describe.

- Add a TRY for Aachen to implement examples located in Aixlibs hometown

**How do we want to solve it? Describe the solution you'd like**

- Convert real weatherdata to TRY format an merge into Aixlib

**Comment by PMehrfeld** [comment]
@phillipstoffel: Isn't this closed by #1136? Then please delete the branch and close this issue.
