### ISSUE TITLE
picture for sprint two

### ISSUE THREAD

**Issue by sejadAres** [RWTH-EBC/AixLib#1139]
![image](https://user-images.githubusercontent.com/77740294/120801423-6ac87400-c541-11eb-9a5e-ab2fa07ab6a1.png)
![image](https://user-images.githubusercontent.com/77740294/120801474-7e73da80-c541-11eb-8251-eae3f3fdafe6.png)

**Comment by PMehrfeld** [comment]
@sejadAres blocked
