### ISSUE TITLE
Error in BoilerCHP.BaseClasses.PartialHeatGenerator

### ISSUE THREAD

**Issue by jengstud** [RWTH-EBC/AixLib#1144]
**Describe the bug**
When running the CHPSystem example in OpenModelica, the following error is thrown:
```
[AixLib.Fluid.BoilerCHP.BaseClasses.PartialHeatGenerator: 26:3-28:64]: PartialMedium is partial, name lookup is not allowed in partial classes.
```
The work around is to replace the reference to Modelica.Media.Interfaces.PartialMedium.MassFlowRate in line 26 of the PartialHeatGenerator by Modelica.SIunits.MassFlowRate.

**To Reproduce**
1. Go to AixLib -> Fluid -> BoilerCHP -> Examples -> CHPSystem
2. Simulate the CHPSystem example
3. See error

**Expected behavior**
The simulation should run.

**Desktop (please complete the following information):**
- OpenModelica v1.17.0 (64bit), OMSimulation v2.0.0.post284-gc8ec782-mingw on Windows 10
- AixLib release v1.0.0

**Comment by Maghnie** [comment]
Possibly fixed with d0e2479c5d464e22651de2731fbe1cab740d01ba
