### ISSUE TITLE
Add simulation and plotting script for AixLib.Fluid.BoilerCHP.Examples.CHPSystem

### ISSUE THREAD

**Issue by Maghnie** [RWTH-EBC/AixLib#1173]
Issue #1144 makes a suggestion how `AixLib.Fluid.BoilerCHP.Examples.CHPSystem` can be updated to be compatible with OpenModelica. 

So we need to generate some reference results before the change to make sure tweaking the code doesn't break anything.

**Comment by FelixStege** [comment]
@Maghnie any updates on this?
