### ISSUE TITLE
Change obsolete pump model in examples

### ISSUE THREAD

**Issue by KremerMartin** [RWTH-EBC/AixLib#1179]
**Describe the bug**
Its not really a bug, but not recommended. `AixLib.Fluid.Storage.Examples.StorageBoiler` inherits an obsolete pump model that should be replaced with the current pump model

Maybe there some other examples which inherit old pump models. They could also be collected here.

**Comment by FWuellhorst** [comment]
This affects the #1234 job as the current development CI is broken. I will fix this now.
