### ISSUE TITLE
Warnings in AixLib.Building.LowOrder.Examples.improvedLOMExample

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#118]
AixLib.Building.LowOrder.Examples.improvedLOMExample gives warnings about the initial system.
```
Warning In AixLib.Building.LowOrder.Examples.improvedLOMExample

There is no unique solution for the variable reducedOrderModel.outerwall.load1.T. If applicable, add a fixed initial value, initial equation or initial assignment.
There is no unique solution for the variable reducedOrderModel.innerwall.load1.T. If applicable, add a fixed initial value, initial equation or initial assignment.
There is no unique solution for the variable reducedOrderModel.airload.T. If applicable, add a fixed initial value, initial equation or initial assignment.

Message: InitialSystem.IterationVar
```

Since I do not know if you want to fix this just in the example or in the used models AixLib.Building.Components.DryAir.Airload, AixLib.Building.LowOrder.BaseClasses.SimpleInnerWall and AixLib.Building.LowOrder.BaseClasses.SimpleOuterWall I can't provide a PR here.

**Comment by PRemmen** [comment]
This should hopefully solve this problem. 

We will discuss, if this should be changed in the used models.

**Comment by tbeu** [comment]
Fix confirmed (for this particular example model).
