### ISSUE TITLE
Missing simulate and plot scripts for reduced order model

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#1188]
The following examples do not have a simulate and plot script:

AixLib.ThermalZones.ReducedOrder.Examples.ComparisonThermalZoneMoistAndDryAir
AixLib.ThermalZones.ReducedOrder.Examples.Multizone
AixLib.ThermalZones.ReducedOrder.Examples.MultizoneEquipped
AixLib.ThermalZones.ReducedOrder.Examples.MulltizpnePartlyCooled
AixLib.ThermalZones.ReducedOrder.Examples.ThermalZone
AixLib.ThermalZones.ReducedOrder.Examples.ThermalZoneAirExchange
AixLib.ThermalZones.ReducedOrder.Examples.ThermalZoneMoistAir
AixLib.ThermalZones.ReducedOrder.Examples.ThermalZoneMoistAirCO2AirExchange

**Comment by tobinfiedler** [comment]
@larissakuehn What is the current status of this issue?

**Comment by FWuellhorst** [comment]
This was already closed
