### ISSUE TITLE
Only humidifier of AHU does not work

### ISSUE THREAD

**Issue by JonBaum** [RWTH-EBC/AixLib#1193]
When using the AHU of the reduced order model, the humidifier does not seem to work if the dehumidifier is turned off at the same time.

**Steps to reproduce the behavior:**

1. Load example MultizoneEquipped out of the ReducedOrderModel
2. Deactivate dehuAHU and huAHU and simulate
3. Run a second simulation with huAHU activated and compare phi_supply of both simulations

**Expected behavior**

Turning on the humidifier should keep the humidity of the supply air at the minimum humidity (variable tableAHU.y[2])

**Screenshots (from a used case)**

![dehum_off_hum_off](https://user-images.githubusercontent.com/44967980/140897275-e40ee6a4-4b25-4f25-a4fa-843f03966660.png)
_dehumidifier and humidifier turned off_

![dehum_off_hum_on](https://user-images.githubusercontent.com/44967980/140897331-377a93d6-1e78-4b35-af28-62b99244cfa7.png)
_dehumidifier off and humidifier on_

The graphs are identical and the supply air humidity is not being humidified in the later case,

**Desktop**

 - Dymola Version 2020
 - tested on current development and master branch of AixLib

**Additional context**

There is a workaround for this bug: Activate the dehumidifier and set the maximum relative humidity to 1. The dehumidifier won't be turned on but the humidifier starts working

**Comment by KremerMartin** [comment]
The problem is located here, I think. I found the same mistake by trying to compare a new AHU model (see #834) with the old one:
![grafik](https://user-images.githubusercontent.com/48821826/141491613-f902ceed-60fd-49db-885f-20747634da3e.png)

**Comment by KremerMartin** [comment]
@JonBaum Ich habe das im Branch issue1193_... mal korrigiert. Sieht jetzt ganz gut aus.
![grafik](https://user-images.githubusercontent.com/48821826/141495366-94a45288-e48c-44bc-b96a-aa8c588cfc2d.png)

Ich stelle noch einen Pull-Request. Könnte aber sein, dass die Regression-Tests zunächst failen, da sich vermutlich die Ergebnisse der Results für die Examples der ROMs ändern werden.
