### ISSUE TITLE
Avoid warning in thermalZone model

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1195]
**Describe the bug**
Warnings get raised because we propagate the parameter `nOriantations` using the `zoneParam`.
This can be fixed by changing line 69 in `AixLib.ThermalZones.ReducedOrder.ThermalZone.BaseClasses.PartialThermalZone`  to:
`    final nOrientations=size(zoneParam.ATransparent, 1),`

**To Reproduce**
Check the model `AixLib.ThermalZones.ReducedOrder.Examples.ThermalZone` in the current development.

**Expected behavior**
No warnings.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22442514/140954366-3d9a9148-8d95-4590-80e8-315dc05d5dfd.png)

**Desktop (please complete the following information):**
 - Dymola 2020x

**Comment by MartinRaetz** [comment]
Thank you @FWuellhorst for identifying this bug and suggesting a fix.

I understand that this warning should be fixed. I think it works for most or possibly all cases. Though, I think there could be combinations of number_element_calc and existing or non-existing roofs, walls, ceilings, windows, etc., for which this work around could not work.

See the attached screenshots from Teaser:

Though

![grafik](https://user-images.githubusercontent.com/28930877/140963083-f99cc994-9282-48bb-96f7-c653b161ad44.png)

![grafik](https://user-images.githubusercontent.com/28930877/140963621-bee641e7-1717-48b9-a362-d244f41c3261.png)

**Comment by DaJansenGit** [comment]
Thanks also from my side. I have the same concerns that martin already raised. I think a solution would be to use `max(zoneParam.ATransparent, zoneParam.AExt,zoneParam.AWin)`. as size for the array. This should cover all cases, if I'm not wrong.

**Comment by FWuellhorst** [comment]
Ok, so `AWin`, `AExt` and `ATransparent` will not always be defined?
As the parameters in the `OneElement` model are always there I would be surprised to see an arrays with different sizes. Maybe they will contains only zeros. But they should all be of size `nOriantations` or am I wrong?
If so, it would be 
 `final nOrientations=max(size(zoneParam.AWin, 1), size(zoneParam.AExt, 1), size(zoneParam.ATransparent, 1))`
 for line 69.

**Comment by FWuellhorst** [comment]
I don't get it :D 
All Integer parameters are stand alone and not added to one another. In other languages, you would not need to specify the length of an array in order to know it's size. 
For Teaser nothing changes at all. Only the parameters are passed to the ROM in a different manner. 

Do you have some examples or guides on how to fix MMM? 

I pushed my changes, feel free to check if this would work.

**Comment by MartinRaetz** [comment]
Sorry @FWuellhorst, I didn´t want to sound arrogant. What I wanted to say is that I do not understand why this error occurs in Modelica. 

My issue with the current fix is, that the size of the array is originally calculated in teaser the calculation depends on the `number_element_calc` and also on `merge_window`.

So there are some cases where the above fix will not lead to the same integer that has originally been posted through `n_orientations`. 

As an example let´s see the four_element with `merge_window` for a zone with outer_walls facing north, east and west and a window facing south. With merge window `nOrientations = win + walls = 4` but `nOrientations=max(size(zoneParam.AWin, 1), size(zoneParam.AExt, 1), size(zoneParam.ATransparent, 1)) = max(1,3,1) = 3`. Whereat the without `merge_window` both would lead to the same result for that specific example. 

As I understand we would need to mirror the approximately 4-8? different ways of calculating `nOrientations` from Teaser to Modelica. Which I find complicated to implement and hard to understand for other users.

If I am getting something wrong, please let me know. I´d be happy explaining the problem to you via screensharing, if you want.

![grafik](https://user-images.githubusercontent.com/28930877/141076854-21a5a422-0b5d-4858-8a1a-5fd71275494a.png)

![grafik](https://user-images.githubusercontent.com/28930877/141077027-f3b1eb44-6f43-400b-a5cb-f4ae6d545f55.png)

![grafik](https://user-images.githubusercontent.com/28930877/141077738-1d14984e-5ffc-4f7e-b5d8-bf42cd0f475a.png)

![grafik](https://user-images.githubusercontent.com/28930877/141077938-134aae24-6a20-493b-a90f-ef0d0c7555ee.png)

![grafik](https://user-images.githubusercontent.com/28930877/141081179-fbd088da-4efc-48b2-871c-66d3eaface9b.png)

**Comment by MartinRaetz** [comment]
After going through Teaser another time, I found that some doc_string have been faulty. They are fixed here: https://github.com/RWTH-EBC/TEASER/tree/issue701_documentation

Now I think the line: `final nOrientations=max(size(zoneParam.AExt, 1))` should cope with all `calc_element` differentiations.
Though, the above-mentioned example will still lead to an error (if one facade orientation is only window without outer_wall).

Hence, we are down to 2 distinctions of cases.

**Comment by MartinRaetz** [comment]
As the ThermalZone does not allow for a differentiation between the number of windows and the number of walls, etc., the above mentioned fix is valid. The merge_window parameter does only apply to the area of the walls but not on the number of orientations and is not relevant for this issue. 
 
![grafik](https://user-images.githubusercontent.com/28930877/141267139-3de64670-c9af-4092-a46f-7f97fba5306d.png)
