### ISSUE TITLE
Internal Gains Output for thermalZone

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1215]
**What is the problem?**

Information on internal gains quantities would be nice.

**How do we want to solve it? Describe the solution you'd like**

Add an output connector to indicate how much heat flow is generated by internal gains.

**Comment by DaJansenGit** [comment]
I think it might be useful to reopen issue #1101 and integrate the accumulated energy by internal gains as well based on the connector created in this issue. What do you think about this @FWuellhorst?

**Comment by FWuellhorst** [comment]
I would like the idea as well!

**Comment by FWuellhorst** [comment]
Affected models:
`AixLib.ThermalZones.ReducedOrder.ThermalZone.ThermalZone`
Examples:
`AixLib.ThermalZones.ReducedOrder.Examples.ThermalZone`
