### ISSUE TITLE
Advanced information on "nOrientations" Parameter

### ISSUE THREAD

**Issue by Roumaenski** [RWTH-EBC/AixLib#1216]
**What is the problem?**

When using the SimpleRoomXElements-Example in ThermalZones.ReducedOrder, one has to set the parameter 'nOrientations'. The discription of that parameter "Number of orientations" unfortunately doesn't give a hint on to which objects (physical parts of the room) the parameter refers and how to set it up in the right manner. Tracking down the places in the code, where it's being used, one could assume, it has to do with the number of exterior walls or the ones containing windows/transparent elements. 

- ...

**How do we want to solve it? Describe the solution you'd like**

A few more words in the models documentation spent to describe what the purpose of this parameter is and how the model depends on it would be very helpfull. Maybe a short example à la "if the room you want to simulate exists of this ... set of walls, set 'nOrientations' to X" could be included.

- ...

**Comment by DaJansenGit** [comment]
You are right, there is room for improvement regarding the documentation. I will add some more information. Here is the docstring of the equivalent parameter `n_outer` from TEASER for the different capacity models:

```
four elements
        Number of total facades with different combination of tilt and
        orientation, windows and outer walls
three elements
        Number of total facades with different combination of tilt and
        orientation, windows and outer walls rooftops
one element
	Number of total outer walls with different combination of tilt and
        orientation, including Rooftops and GroundFloors
two element
	Number of total outer walls with different combination of tilt and
        orientation, including Rooftops and GroundFloors
```

**Comment by tobinfiedler** [comment]
@DaJansenGit What is the current status of this issue?

**Comment by DaJansenGit** [comment]
solved in dev
