### ISSUE TITLE
Slack notifications

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#1217]
Using github action, a fixed time interval of one month is used to check how long branches in the repository are inactive. 

If a branch is inactive for more than 90 days, the user is notified via a Slack notification.

If the branch is inactive for more than 180 days, the user is notified that the branch will be closed. In this case, a pull request is first created and then closed again and the branch is deleted. This allows the user to restore the branch.

**Comment by tobinfiedler** [comment]
@SvenHinrichs What is the current status of this issue?
