### ISSUE TITLE
Project: Weather data bugs and fixes

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1219]
As stated here #1203 and discussed internally, different bugs and features requests exist for the current way we handle weather data. 

In this issue, we will document all learnings and issues along with this longer project.

**Comment by FWuellhorst** [comment]
List of things to do:
- Feature: Real weather data reader -> @MartinRaetz 
- Bug: Latitude -> @FWuellhorst 
- Question: Difference between old and TMY3 reader  -> @Dawac

**Comment by FWuellhorst** [comment]
The latitude bug will be fixed by the next IBPSA merge.

**Comment by tobinfiedler** [comment]
@FWuellhorst What is the current status?

**Comment by FWuellhorst** [comment]
Depends on the fixes in the converter, the latest IBPSA merge and the differences in weather formats. Within a current project, @larissakuehn should also be affected.
