### ISSUE TITLE
Serious issues in AixLib.Building.LowOrder.Examples.LowOrderExample

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#124]
Running AixLib.Building.LowOrder.Examples.LowOrderExample in pedantic mode reveals serious issues on Modelica compliance.

**Comment by PRemmen** [comment]
I checked with Dymola 2016 and there are no more pedantic issues in this example. 

However, we should check the results of that example, something seems to be strange with heating and cooling demand @mlauster

**Comment by tbeu** [comment]
I still see the issues (on current master).

**Comment by PRemmen** [comment]
@tbeu we haven't merged it into the master yet, I will create a PR now
