### ISSUE TITLE
Further models for LowOrder

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#125]
This issue is to add missing high level models form internal libs to AixLib. These are:
- ThermalZonePhysicsRWin
- ThermalZoneMod
- ThermalZoneModRWin
- HouseMultizone
- HouseMultizoneRWin
- TypeBuilding
- TypeBuildingRWin

Of course, the task is not only to move the models, but to pick the reasonable ones, combine versions with and without RWin and to adapt style to guidelines

**Comment by PRemmen** [comment]
solved by #130
