### ISSUE TITLE
Incorrect AixLib models in connection with the IBPSA merge

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#1291]
In the course of the IBPSA Merge, the IBPSA library was converted to MSL 4.0.0. The AixLib models have been updated to MSL 4.0.0 accordingly. 
Currently, there are AixLib models that do not successfully pass the CI checks and have therefore been whitelisted. These are the following models:

- [ ] AixLib.Media.Refrigerants.Examples.RefrigerantTestImplementation
- [ ] AixLib.Media.Refrigerants.Examples.BranchingDynamicPipes
- [ ] AixLib.DataBase.CHP.ModularCHPEngineMedia.CHPCombustionMixtureGasNasa
- [ ] AixLib.Fluid.Actuators.Dampers.VAVBoxExponential
- [ ] AixLib.Systems.ModularAHU.RegisterModule
- [ ] AixLib.Systems.ModularAHU.Validation.AHU2_Heater
- [ ] AixLib.Systems.ModularAHU.Validation.AHU2_Cooler
- [ ] AixLib.Systems.HydraulicModules.ThrottlePump
- [ ] AixLib.Systems.HydraulicModules.Pump
- [ ] AixLib.Systems.HydraulicModules.Injection
- [ ] AixLib.Systems.HydraulicModules.Throttle
- [ ] AixLib.Systems.HydraulicModules.Admix
- [ ] AixLib.Systems.HydraulicModules.Injection2WayValve
- [ ] AixLib.Systems.HydraulicModules.Example.Pump
- [ ] AixLib.Systems.ModularAHU.Validation.AHU2_Preheater
- [ ] AixLib.Systems.HydraulicModules.Example.Injection 
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.BaseClasses.PartialIsenthalpicExpansionValve
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.BaseClasses.PartialExpansionValve
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.BaseClasses.PartialModularExpansionVavles
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.ExpansionValvePressureDifference
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.ExpansionValveMassFlowRate
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.BaseModelStaticHeatPumps
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.StaticHeatPumpBoundaries
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.ModularExpansionValvesPressureDifference
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.Examples.ModularExpansionValvesMassFlowRate
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.SimpleExpansionValves.IsenthalpicExpansionValve
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.ModularExpansionValves.ModularExpansionValves
- [ ] AixLib.Fluid.Actuators.Valves.ExpansionValves.ModularExpansionValves.ModularExpansionValvesSensors
- [ ] AixLib.Fluid.Movers.Compressors.BaseClasses.PartialCompressor
- [ ] AixLib.Fluid.Movers.Compressors.BaseClasses.PartialCompression
- [ ] AixLib.Fluid.Movers.Compressors.BaseClasses.PartialModularCompressors
- [ ] AixLib.Fluid.Movers.Compressors.ModularCompressors.ModularCompressorsSensors
- [ ] AixLib.Fluid.Movers.Compressors.ModularCompressors.ModularCompressors
- [ ] AixLib.Fluid.Movers.Compressors.Examples.RotaryCompressor
- [ ] AixLib.Fluid.Movers.Compressors.Examples.ModularRotaryCompressor
- [ ] AixLib.Fluid.Movers.Compressors.Examples.RotaryCompressorPressureHeatLosses
- [ ] AixLib.Fluid.Movers.Compressors.Examples.RotaryCompressorPressureLosses
- [ ] AixLib.Fluid.Movers.Compressors.Utilities.HeatTransfer.SimpleHeatTransfer
- [ ] AixLib.Fluid.Movers.Compressors.SimpleCompressors.CompressionProcesses.RotaryCompression
- [ ] AixLib.Fluid.Movers.Compressors.SimpleCompressors.RotaryCompressors.RotaryCompressor
- [ ] AixLib.Fluid.Movers.Compressors.SimpleCompressors.RotaryCompressors.RotaryCompressorPressureHeatLosses
- [ ] AixLib.Fluid.Movers.Compressors.SimpleCompressors.RotaryCompressors.RotaryCompressorPressureLosses
- [ ] AixLib.Fluid.Movers.Compressors.Validation.ModularInactiveCompressors
- [ ] AixLib.Fluid.Movers.Compressors.Validation.EfficiencyModels
- [ ] AixLib.Fluid.Movers.Compressors.Validation.SimpleHeatTransfer
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.BaseModelStaticHeatPump
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.BaseModelStaticHeatPumpController
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.BaseModelStaticBoundaries
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.SpecifiedModels.RefrigerantR410aScrollCompressorController
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.SpecifiedModels.RefrigerantR410aScrollCompressor
- [ ] AixLib.Fluid.Movers.Compressors.Validation.StaticHeatPumpBoundaries.SpecifiedModels.RefrigerantR134aScrollCompressor
- [ ] AixLib.Fluid.Storage.BufferStorage
- [ ] AixLib.Fluid.Storage.Examples.TwoPhaseSeparator
- [ ] AixLib.BoundaryConditions.InternalGains.Examples.InternalGains.BaseClasses.Humans
- [ ] AixLib.Fluid.Examples.Performance.BaseClasses.Example1
- [ ] AixLib.Fluid.MixingVolumes.Validation.BaseClasses.MixingVolumeReverseFlow
- [ ] AixLib.Fluid.MixingVolumes.Validation.BaseClasses.MoistureMixingConservation
- [ ] AixLib.ThermalZones.HighOrder.Validation.ASHRAE140.BaseClasses.PartialCase
- [ ] AixLib.Fluid.DistrictHeatingCooling.Demands.Examples.OpenLoopVarTSupplyDpBypass
- [ ] AixLib.Systems.ModularAHU.Examples.EONERC_AHU2

**Comment by SvenHinrichs** [comment]
[AixLib.Fluid-errorlog.txt](https://github.com/RWTH-EBC/AixLib/files/8563027/AixLib.Fluid-errorlog.txt)
[AixLib.Media-errorlog.txt](https://github.com/RWTH-EBC/AixLib/files/8563033/AixLib.Media-errorlog.txt)
[AixLib.Systems-errorlog.txt](https://github.com/RWTH-EBC/AixLib/files/8563034/AixLib.Systems-errorlog.txt)

**Comment by FelixStege** [comment]
@DaJansenGit, any updates on this?

**Comment by FWuellhorst** [comment]
Aside from the refrigerant models, which are not developed further, the errors are fixed by now. I will close this.
