### ISSUE TITLE
Building efficiency measures

### ISSUE THREAD

**Issue by TobiasBlacha** [RWTH-EBC/AixLib#1295]
In the corresponding branch we will investigate different building energy efficiency measures with the high order model

**Comment by tosch4** [comment]
@Yi-Nie @LauraMaier 
Can you give us some information about the current status?

**Comment by Yi-Nie** [comment]
This branch is used for a specific project and does not develop new features. It is not maintained afterwards and can be deleted automatically. In my opinion this issue can be closed
