### ISSUE TITLE
New workflow, semantic Versioning

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#131]
As discussed we suggest to implement a new workflow for AixLib. We should make use of Semnatic Versioning http://semver.org/ . In order to still have a reasonable number of releases we could do the following.

Two permanent branches:

**master-branch** - This branch should always be a stable version. Bugfixes will be merged into the master, with changing version number (eg. from 0.1.12 -> 0.1.13) and a new release on GitHub.

Between each minor (e.g. v0.1.13 -> v0.2.0) and major (e.g. v1.6.5 -> v2.0.0) release all development of new features and minor revision is coordinated in the **development-branch** without changing the version number.The targets of each release are documented via Milestones. After all Milestones are successfully implemented in the development branch, they are merged into the master, and a new version will be released. The development branch is also kept up to date with the master (bugfixes).

**Comment by marcusfuchs** [comment]
Tagged v0.2.0 as starting point for the new workflow. Also, I created milestones v0.3.0 and Deep Future.

**Comment by marcusfuchs** [comment]
Pushed branch development for v0.3.0

**Comment by marcusfuchs** [comment]
Wiki is updated.
