### ISSUE TITLE
Polynomial Based Pump Records

### ISSUE THREAD

**Issue by sarahleidolf** [RWTH-EBC/AixLib#1354]
Polynomial Based Pump Records:

- Pump DN25 H 0.5 to 12
- Pump DN50 H 0.5 to 16

**Comment by tosch4** [comment]
@FelixStege @sarahleidolf 
please add more details.

**Comment by sarahleidolf** [comment]
Add new Pump Records to AixLib.DataBase.Pumps.PumpPolynomialBased based on Pump Characteristic curves.

**Comment by sarahleidolf** [comment]
Add new Pump Records to AixLib.DataBase.Pumps.PumpPolynomialBased based on Pump Characteristic curves.
Characteristic curves mapped on the basis of the maximum and minimum height at a given volume flow rate (maxMinHeight=[Q [m3/h], Hmax [m], Hmin [m]]) and the maximum and minimum speed.

- Pump_DN25_H05_12 "Pump with head 0.5 to 12m PN 10 maximum volume flow 12.0 m^3/h"
   nMin=750, nMax=4350
- Pump_DN50_H05_16 "Pump with head 0.5 to 16m PN 6/10 maximum volume flow 53.0 m^3/h"
  nMin=500, nMax=3200
