### ISSUE TITLE
GeothermalHeatPump example fails in OpenModelica

### ISSUE THREAD

**Issue by HannahRomberg** [RWTH-EBC/AixLib#1367]
Error in model:  AixLib.Fluid.Examples.GeothermalHeatPump.GeothermalHeatPump 
Failed to build model: AixLib.Fluid.Examples.GeothermalHeatPump.GeothermalHeatPump
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:312:11-312:43:writable] Warning: Conditional component ‘mHC1_flow_nominal‘ is used in a non-connect context.
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:305:5-305:34:writable] Warning: Conditional component ‘m_flow_small_HC1‘ is used in a non-connect context.
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:333:3-334:118:writable] Warning: Conditional component ‘mHC1_flow_nominal‘ is used in a non-connect context.
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:312:11-312:43:writable] Warning: Conditional component ‘mHC1_flow_nominal‘ is used in a non-connect context.
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:305:5-305:34:writable] Warning: Conditional component ‘m_flow_small_HC1‘ is used in a non-connect context.
[D:/04_git/AixLib/AixLib/Fluid/Storage/BufferStorage.mo:333:3-334:118:writable] Warning: Conditional component ‘mHC1_flow_nominal‘ is used in a non-connect context.
Error: Too few equations, under-determined system. The model has 4628 equation(s) and 4629 variable(s).

**Comment by FelixStege** [comment]
@HannahRomberg, is this something for the upcoming hackday or can we remove the label?

**Comment by HannahRomberg** [comment]
@FelixStege, issue remains from the last hackday. I would try closing it the upcoming hackday unless you have other plans.
