### ISSUE TITLE
Simulate and plot scripts and ref results for multizone examples

### ISSUE THREAD

**Issue by LauraMaier** [RWTH-EBC/AixLib#1388]
The following examples do not have reference results so far:

- [x]  AixLib.ThermalZones.ReducedOrder.Examples.Multizone
- [x]  AixLib.ThermalZones.ReducedOrder.Examples.MultizoneEquipped
- [x]  AixLib.ThermalZones.ReducedOrder.Examples.MulltizpnePartlyCooled

Simulate and plot scripts will be developed and the CI will push ref results accordingly.

**Comment by FWuellhorst** [comment]
Closed by #1390
