### ISSUE TITLE
Grammar and Scripting Error

### ISSUE THREAD

**Issue by senihozkan** [RWTH-EBC/AixLib#1406]
Hi, I am a new user of OpenModelica. 

When I try to load PropulsionSystem library, I get the error like below. Thank you so much.
![Error](https://user-images.githubusercontent.com/118957205/203797816-c38588e8-e313-42fc-9d00-8d459ca5921f.png)

**Comment by FelixStege** [comment]
@senihozkan, were you able to solve your problem? Can this issue be closed?

**Comment by FWuellhorst** [comment]
Closing as not related to the AixLib
