### ISSUE TITLE
Rename master to main and delete development

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1412]
With the updated CI, the separation of dev and master is not required anymore. This will also enable smooth use of squash and merge. 
@DaJansenGit @SvenHinrichs Will you handle this?

**Comment by DaJansenGit** [comment]
Yes, "we" or lets say @SvenHinrichs will handle this ;) We will add the needed changes to the CI and afterwards move/rename the branches.

**Comment by SvenHinrichs** [comment]
This should not be a problem. When do you plan to make the switch from master/develoment to main? For this I would only have to briefly recreate the templates for me.

**Comment by DaJansenGit** [comment]
I would go for it asap. For priority, I would finish the docs for the structure first, but afterwards we can perform the renaming and deletion of development.
