### ISSUE TITLE
make AHU conditional

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#142]
in MultizoneEquipped

**Comment by PMehrfeld** [comment]
@mlauster : I have made the AHU replaceable in MultizoneEquipped. I think this might be a good possibility. What do you think?

**Comment by mlauster** [comment]
@PMehrfeld, your solution looks very good, thanks! And a speed up of 40% for cases without `AHU` is impressive.
I made a small change regarding the declaration of the replaceable block in `MultizoneEquipped` and renamed `PartialAHU` to `partialAHU`.
If I'm not mistaken, you integrated the parameter that are relevant for the user in `partialAHU`, what is about `dp_sup`, `dp_eta`, `eta_sup` and `eta_eta`?
- [ ] Please add some basic information for `NoAHU` and `partialAHU` and fill in revision section.

**Comment by PMehrfeld** [comment]
@mlauster: I made the requested enhancements (Info and parameters are now in building record). Additionally, I improved the selection of AHU in MultizoneEquipped.mo.
Please check and merge via pull request #148. Contact me if you have further questions.
