### ISSUE TITLE
Errors in thermalZone Examples

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#1424]
Selecting zone records using the dropdown menu in the thermal zone examples leads to errors when using Dymola 2023

We have performed the following test with the example `AixLib.ThermalZones.ReducedOrder.Examples.ThermalZone`:
- Per default, the path for the record is: "DataBase.ThermalZones.OfficePassiveHouse.OPH_1_OfficeNoHeaterCooler()", in that case, check and simulation are successful without any warnings.
- When changing the path manually to `AixLib.DataBase.ThermalZones.OfficePassiveHouse.OPH_1_OfficeNoHeaterCooler()` there are still no warnings.
- If we chose the same record via the drop down menu the path looks the same: `AixLib.DataBase.ThermalZones.OfficePassiveHouse.OPH_1_OfficeNoHeaterCooler()`, the check still is successful without any warnings, but during simulation (which still runs) the following error appears 400 times: 
```
Argument number 1 in
sum(AixLib.DataBase.ThermalZones.OfficePassiveHouse.OPH_1_OfficeNoHeaterCooler( 293.15, true, 6700.0, 1675.0, 5.0, 0.87266462599716, 5, {108.5, 19.0, 108.5, 19.0, 0.0}, {108.5, 19.0, 108.5, 19.0, 0.0}, 2.7, 0.017727777777, 0.78, 2.1, 0.09, {244.12, 416.33, 244.12, 416.33, 208.16}, 2.19, 1, {1.4142107968E-05}, 0.000380773816236, {492976267.489}, 5862.5, 2.27, 1, {1.13047235829E-05}, { 1402628013.98}, 0.0, 0.0, 1, {0.001}, 0.001, {0.001}, 0.0, 0.0, 1, {0.001}, 0.001, {0.001}, 1, {0.0}, {0.0}, {1.0}, 0.7, 0.7, 283.15, 20.0, 5.0, 20.0, 20.0, 5.0, {1.5707963267949, 1.5707963267949, 1.5707963267949, 1.5707963267949, 0.0}, {0.0, 1.5707963267949, 3.1415926535898, 4.7123889803847, 0.0}, {0.2, 0.2, 0.2, 0.2, 0.1}, {0.25, 0.25, 0.25, 0.25, 0.0}, 0.1, 0.07142857142857142, 1.2, 70.0, 0.5, 0.5, 7.0, 0.6, 12.5, 0.6, false, 0.2, 1.0, {3.0, 2.0}, {1.0, 283.15, 290.15}, {0.2, 273.15, 283.15}, true, 0.0, 12.0, {0.7, 0.7, 0.7, 0.7, 0.0}, {100.0, 100.0, 100.0, 100.0, 0.0}, 167500.0, 0.0, 1000.0, 1.0, false, 0.0, -1.0, 0.0, 0.0, 1000.0, 1.0, false, 288.15, 295.15, false))
must be an array.
```

For other versions of Dymola (tested versions: 2022, 2022x) this error does not appear.

**Comment by FWuellhorst** [comment]
Apparently, this issue is fixed if `replaceable parameter DataBase.ThermalZones.ZoneBaseRecord zoneParam` is used. Using `choicesAllMatching` on non-replaceable objects seems to be not legal in Modelica. 
Nevertheless, the issue will be raised to Dymola.
