### ISSUE TITLE
Non-standard annotation

### ISSUE THREAD

**Issue by maltelenz** [RWTH-EBC/AixLib#1426]
This seems to be using a non-standard annotation without a vendor prefix, making it invalid Modelica:

https://github.com/RWTH-EBC/AixLib/blob/4280d7cd2c339d62cd6ab650c0e076f3aef1bd78/AixLib/Controls/HeatPump/HPControl.mo#L16

There are many more cases spread out across the library.

**Comment by FWuellhorst** [comment]
This affects 38 models. 10 are already obsolete, 7 will be fixed due to the heat pump move to IBPSA. Remaining models are mostly HOM. However, the current HOM implementation should be using enumerations anyway, in my opinion.
Example:
`if calcMethodOut == 1 or calcMethodOut == 2 then`
What does this mean?
`if calcMethodOut == calcMethodOut.DIN6946 or calcMethodOut == calcMethodOut.ASHRAEFundamentals then`
is much clearer to read and understand. 
For enumerations, Dymola does not support radio-button. This means using Enums would make the use obsolete.
 @larissakuehn @StGoebel @KremerMartin @LauraMaier : As you are among the users of the HOM, are you in favor or against removing the buttons?

The UI would change something like this:
![image](https://user-images.githubusercontent.com/22442514/219584678-ba0c44b8-3c2e-4d1a-be31-5bc6e10a65b3.png)


Instead of this:
![image](https://user-images.githubusercontent.com/22442514/219584859-3bed4f62-926d-42fa-aaeb-e4247342d576.png)

**Comment by FWuellhorst** [comment]
@maltelenz : Is there an option in OM to warn about wrong annotations?

**Comment by KremerMartin** [comment]
I would be fine with a drop-down menu instead of radioButtons as it is only a visual element.  I would also agree with @FWuellhorst to use enumerations for better code readability.

**Comment by maltelenz** [comment]
> @maltelenz : Is there an option in OM to warn about wrong annotations?

I don't know, I represent Wolfram System Modeler (which currently doesn't have a good general way to find invalid annotations).

**Comment by PatrickHenkel1** [comment]
RadioButtons are used in the following files:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/phe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/phe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/phe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>




·       \Controls\HeatPump\AntiLegionella.mo
--
·       \Controls\HeatPump\HPControl.mo
·       \Controls\SetPoints\HeatingCurve.mo
·         \Fluid\HeatExchangers\ActiveWalls\BaseClasses\PanelHeatingSegment.mo
·         \Fluid\HeatExchangers\ActiveWalls\PanelHeating.mo
·       \Fluid\HeatExchangers\EvaporatorCondenserWithCapacity.mo
·         \Obsolete\Year2019\Fluid\HeatPumps\HeatPumpDetailed.mo
·         \Obsolete\Year2020\ThermalZones\HighOrder\Components\Walls\Wall_ASHRAE140.mo
·         \Obsolete\Year2020\ThermalZones\HighOrder\Rooms\MFD\CellarAttic\Attic_Ro2Lf1.mo
·         \Obsolete\Year2020\ThermalZones\HighOrder\Rooms\MFD\CellarAttic\Cellar.mo
·         \Obsolete\Year2022\ThermalZones\HighOrder\Rooms\MFD.mo
·         \Obsolete\YearIndependent\FastHVAC\BaseClasses\EvaporatorCondenserWithCapacity.mo
·         \Systems\HeatPumpSystems\BaseClasses\HPSystemController.mo
·         \Systems\HeatPumpSystems\BaseClasses\PartialHeatPumpSystem.mo
·       \Systems\HeatPumpSystems\HeatPumpSystem.mo
·         \ThermalZones\HighOrder\Components\Walls\BaseClasses\ConvNLayerClearanceStar.mo
·         \ThermalZones\HighOrder\Components\Walls\Wall.mo
·         \ThermalZones\HighOrder\Components\WindowsDoors\Door.mo
·         \ThermalZones\HighOrder\Examples\OFDHeatLoad.mo
·         \ThermalZones\HighOrder\Examples\OFD_1Jan.mo
·         \ThermalZones\HighOrder\Rooms\BaseClasses\PartialRoomParams.mo
·       \Utilities\HeatTransfer\HeatConvInside.mo
·       \Utilities\HeatTransfer\HeatConvOutside.mo
·       \Utilities\HeatTransfer\HeatToRad.mo
·       \Utilities\Time\DaytimeSwitch.mo
·         \ThermalZones\HighOrder\Components\Examples\Walls\OutsideWall.mo
·         \ThermalZones\HighOrder\House\OFD_MiddleInnerLoadWall\BuildingEnvelope\GroundFloorBuildingEnvelope.mo
·         \ThermalZones\HighOrder\House\OFD_MiddleInnerLoadWall\BuildingEnvelope\UpperFloorBuildingEnvelope.mo
·         \ThermalZones\HighOrder\House\OFD_MiddleInnerLoadWall\BuildingEnvelope\WholeHouseBuildingEnvelope.mo
·         \ThermalZones\HighOrder\Rooms\BaseClasses\PartialRoomFourWalls.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Attic_Ro2Lf5.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow1IwL2IwS1Gr1Uf1.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow1IwL2IwS1Lf1At1Ro1.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow2IwL1IwS1Gr1Uf1.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow2IwL1IwS1Lf1At1Ro1.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow2IwL2IwS1Gr1Uf1.mo
·         \ThermalZones\HighOrder\Rooms\OFD\Ow2IwL2IwS1Lf1At1Ro1.mo
·         \ThermalZones\HighOrder\Rooms\RoomEmpiricalValidation\RoomTwinHouseN2.mo
·         \ThermalZones\HighOrder\Validation\ASHRAE140\BaseClasses\PartialCase.mo
·         \ThermalZones\HighOrder\Validation\ASHRAE140\Case620.mo




</body>

</html>
