### ISSUE TITLE
Typo in class name in choice

### ISSUE THREAD

**Issue by maltelenz** [RWTH-EBC/AixLib#1427]
I assume this is supposed to say `EastWestFacingWindows`?

https://github.com/RWTH-EBC/AixLib/blob/b133dc798c18614a9a728add4ad3f881ec04ba78/AixLib/ThermalZones/HighOrder/Validation/ASHRAE140/BaseClasses/PartialCase.mo#L50

**Comment by FWuellhorst** [comment]
That is correct, thanks for noticing and raising the issue!
