### ISSUE TITLE
Add AixLib in OMEdit

### ISSUE THREAD

**Issue by CHengFFF** [RWTH-EBC/AixLib#144]
Dear AixLib team:
i am studying in RWTH and doing my master thesis now.It will really help me if i can use the AixLib.  i am having problems while adding the AixLib as a library in Openmodelica 1.9.3. It shows  Grammar Error and Scripting Error:Failed to load package AixLib () using MODELICAPATH . So how could i solve this problem? 
Thanks a lot!

**Comment by marcusfuchs** [comment]
Sorry @CHengFFF, we seem to have overlooked this issue. Is this still a problem? For me, AixLib at least opens fine in OM.

**Comment by marcusfuchs** [comment]
I'll close this, but feel free to reopen if there is a problem, we'll respond sooner this time.
