### ISSUE TITLE
refactor pressureDrop coefficient to dp_nominal in PartialHeatGenerator

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#1444]
**What is the problem?**

Currently the `PartialHeatGenerator` model uses the following equation to calculate the `dp_nominal` variable:
```
dp_nominal=m_flow_nominal^2*a/(rho_default^2)
```
with `a` being the pressureDrop coefficient. As this coefficient is only a relict of the `Modelica.Fluid.Fittings.GenericResistances.VolumeFlowRate` model which is not used anymore, we want to get rid of it.

**How do we want to solve it?**
* Remove the default equation from `PartialHeatGenerator`
* Refactor all records as they provide the pressure coefficient currently (but only because it was needed for the former model approach and not because the data sheets provided it).
  *  calculation to calculate dp_nominal from a: `dp_nominal = m_flow_nominal^2*a/(rho_default^2)`

**Comment by FWuellhorst** [comment]
Why would you get rid of a? It is not clear that you adhere to the m_flow_nominal specified in the record. in this case, fixing dp_nominal without a and n is difficult. 
We actually improved the a-n based notation in this PR: https://github.com/RWTH-EBC/AixLib/pull/1543

**Comment by DaJansenGit** [comment]
As discussed, we will leave the n-based notation.
