### ISSUE TITLE
Heat pump model example does not run

### ISSUE THREAD

**Issue by HannahRomberg** [RWTH-EBC/AixLib#1462]
**Describe the bug**
Heat pump model does not run when choosing N-dimensional Performance data included in Ressources.

Error: The following error was detected at time: 0
Requested value is outside data range

**To Reproduce**
1. Go to AixLib.Fuid.HeatPumps.Examples.HeatPump
2. Choose any sdf N-dimensional Performance data for PerDataMainHP included in AixLib\AixLib\Resources\Data\Fluid\BaseClasses\PerformanceData\LookUpTableND
3. Simulate

**Comment by HannahRomberg** [comment]
Temperatures in .sdf data are in °C. Shouldn't they be in K?

**Comment by FWuellhorst** [comment]
Which N-D model do you mean? The VCLibPy sdf tables or the manufacturer based?
These tables are somewhat hard to build yourself, did you use the default .sdf file?

**Comment by FWuellhorst** [comment]
I think the data tables are wrong. The units for all three files are in degC but stated as K. The file VZH088AG.sdf has con and eva swapped. 
Putting `extrapMethod` to hold last value starts the simulation for the file 30XW-0254, but it brakes. This example is  build for the selected performance data. You may have to tweak the scaling factor to achieve a good fit between actual demand and the selected performance data.
