### ISSUE TITLE
Add Communication Package for Co-Simulation Interfaces

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#149]
Add models for co-simulation interfaces

**Comment by marcusfuchs** [comment]
@AnaConstantin: Is this still open?

**Comment by AnaConstantin** [comment]
Yes. We are taking our time with it. i think in one month it will be ready.
If haste is required, please let us know.

**Comment by marcusfuchs** [comment]
Sorry, no, haste is not required at all. In preparation of the hack day we were just going through all the issues to verify they are still open.

**Comment by tbeu** [comment]
The [Modelica_DeviceDrivers](https://github.com/modelica/Modelica_DeviceDrivers) offer TCP/IP socket communication (for Windows and Linux).

**Comment by marcusfuchs** [comment]
@tbeu: Thank you for the information
@AnaConstantin and @GeorgFerdinandSchneider, could you have a look at this and share your view on how these two solutions compare?

**Comment by AnaConstantin** [comment]
Hello everyone. Yes, we are aware that there is a TCP/IP socket communication in Modelica_DeviceDrivers. Historically, our package was created because at that time no such model was available in the Modelica_DevceDrivers Library. So when AixLib started to cristlyse its purpose we started moving relevant packages into it. The models both use the same library for winsockets, and the implementation is a bit different, but still to the same purpose. I find our model has better documentation, and a bit more functions which to my mind makes it more user friendly. I doubt that someone with experience in working with Modelica_DeviceDrivers would start using our model. But someone starting in Co-Simulation via TCP/IP could get a good start with our model and when in need of more protocol support, come to Modelica_DeviceDrivers.  We are open to referencing the model from Modelica_deviceDrivers in the description of the model.
@GeorgFerdinandSchneider what do you think?

**Comment by GeorgFerdinandSchneider** [comment]
Hello everyone!

thankyou for the feedback @tbeu. As mentioned by @AnaConstantin we are aware of the TCP/IP communication capabilities of Modelica_DeviceDrivers. We moved forward implementing the communication package as at that point in time no TCP/IP support in Modelica_DeviceDrivers was available. We added the package to AixLib now as we require the support of multiple sockets in our applications.
It would be great to reference Modelica_DeviceDrivers library in the model documentation.

**Comment by tbeu** [comment]
Some remarks:
 1. Using global variables is not thread-safe. The preferable solution is to use external objects.
 1. Modelica_DeviceDrivers offers TCP/IP also for (GNU) Linux.
 1. Modelica_DeviceDrivers also compiles with MinGW and Cygwin.

I propose to reuse MDDTCPIPSocket.h from Modelica_DeviceDrivers.

**Comment by AnaConstantin** [comment]
Hello everyone, sorry for the late reply, just got back from vacation.
@tbeu thank you for your suggestions. I propose we move with them in a sepparate issue.
My suggetion is to close the current issue, which was adding the package as that target as been achieved, and also set a loooong time ago.
@marcusfuchs, @GeorgFerdinandSchneider ok by you?
Once the pull request is accepted, I'll open the new issue.

**Comment by GeorgFerdinandSchneider** [comment]
@AnaConstantin sounds great, lets start a new issue.

Best regards,

Georg

**Comment by marcusfuchs** [comment]
@AnaConstantin @GeorgFerdinandSchneider 
I'll close this issue and create a new one for the further development
