### ISSUE TITLE
AixLib contains models with experiment annotation that have parameters without bindings and without explicitly set start values.

### ISSUE THREAD

**Issue by casella** [RWTH-EBC/AixLib#1494]
Dear AixLib developers,

please check the latest OpenModelica [regression test report](https://libraries.openmodelica.org/branches/history/master/2024-03-06%2022:42:24..2024-03-07%2022:25:06.html). For the latest released version of AixLib ([AixLib](http://libraries.openmodelica.org/branches/master/AixLib/AixLib.html)) and for the development version of AixLib ([AixLib_dev](http://libraries.openmodelica.org/branches/master/AixLib/AixLib.html)) there are about 35 models that fail since we fixed ticket OpenModelica/OpenModelica#10386.

According to the latest version of Modelica Specification, i.e., 3.6, when you simulate a model all parameters with `fixed = true` should have a binding equation (either provided as a default in the components, or set by modifiers when instantiating them). The only exception is parameters that have an explicitly set start attribute - in that case, if a binding equation is lacking, the start attribute is used to set the parameter value and a warning should be issued.

The first failing case is [AixLib.Electrical.Machines.PVInverterRMS](http://libraries.openmodelica.org/branches/master/AixLib/files/AixLib_AixLib.Electrical.Machines.PVInverterRMS.err), which is actually a component, not a model that should be simulated. In this case it is OK not to have a binding for some parameters, as they will be provided when instantiating the component, but you should remove the `experiment` annotation, since it makes no sense to simulate this component by itself.

In all other cases, some parameter bindings are missing. You can
- add a default binding to the parameters in the component definitions, or
- add an explicit binding when you instantiate the components or,
- add an explicit start = 0 attribute to the parameters in the component definition, which will be used as a fallback value, with a warning being issued.

This will make those models compliant with the Modelica Specification in force, and get them running again in OpenModelica.

Thanks!

**Comment by FWuellhorst** [comment]
@casella Thanks for raising this issue, we will fix it asap!
