### ISSUE TITLE
Problems with arbitrary number of Orientations - Multizone LOM

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#150]
I want to use the MultizoneEquipped Building for simulating thermal zones with less or more then 5 orientations. However this does not work. I need some help here. Not sure it is because of my model setting (from automated model generation) or it's because of the AixLib models

I will push three example models with 4,5 and 6 orientations to a new branch.

**Comment by mlauster** [comment]
There was a problem in the redeclaration of `ThermalZone` in `partialMultizone`. This should be fixed now and all models should run. @PRemmen, can you check and if everything is okay, delete your examples? If we define this as a bug, we need to merge this in the master. Is it a branch of master or development?

**Comment by MichaMans** [comment]
I'm still having trouble to simulate some other multi orientation examples. I'll push an example to the branch and it would be great if someone of you could have a look at it. 

Even if this example is not really relevant we should check if the export itself works correct

**Comment by PRemmen** [comment]
partly solved by #161 issue stays open

**Comment by mlauster** [comment]
@PRemmen models work now, still need to have a look for @MichaMans model. Will do this after #168 branch has been merged to development.

**Comment by mlauster** [comment]
@MichaMans, is this still an issue or too old to take care of?

**Comment by mlauster** [comment]
Since we did a lot of changes and will in the next step integrate Annex ROM as new core, I will close this issue.
