### ISSUE TITLE
Issues on heat pump condenser/evaporator heat flow calculation

### ISSUE THREAD

**Issue by wehuang16** [RWTH-EBC/AixLib#1507]
**Describe the bug**
For the Aixlib heat pump model during "cooling" operation, there is a possibility that the calculation for the condenser/evaporator heat flow is not quite correct. 

**To Reproduce**
1. Use a modelica tool, such as Dymola or OpenModelica, to simulate this heat pump example in the "main" branch (https://github.com/RWTH-EBC/AixLib/blob/main/AixLib/Fluid/HeatPumps/Examples/HeatPump.mo)
2. we will first see that the simulation runs for 3600 seconds. The first half (1800s) is heating mode, and the second half is cooling mode.<img width="604" alt="Screenshot 2024-06-30 at 11 14 28 AM" src="https://github.com/RWTH-EBC/AixLib/assets/82864676/3022153d-d3d5-491c-a506-0df20a5a952f">
3. View the parameter QCon, QEva, and Pel, we notice that during the second half of simulation when the heat pump is in cooling mode, QCon is about -9.1kW, QEva is about 8.7kW, Pel is about 0.4kW.
![Screenshot 2024-07-01 at 9 42 52 PM](https://github.com/RWTH-EBC/AixLib/assets/82864676/c3a921b5-85c2-4ad7-81e9-91f893b7c80f)

4. QEva is positive, meaning that heat flows from the heat pump refrigerant at the evaporator to the flowing fluid (water or air), so the evaporator in the model actually acts as an actual "condenser". QCon is negative, meaning that heat flows from the flowing fluid (water or air) to the heat pump refrigerant at the condenser, so the condenser in the model actually acts as an actual "evaporator". 
5. The correct calculation should be that the absolute value of the actual "evaporator" heat flow (currently represented by QCon for cooling) plus the electric power equal to the absolute value of the actual "condenser" heat flow (currently represented by QEva for cooling). Thus, the absolute value of the actual "evaporator" heat flow (9.1kW) should be **less than** the absolute value of the actual "condenser" heat flow (8.7kW), which might not be correct.

**Expected behavior**
I expect that for cooling, when the QCon is acting as an actual "evaporator", and QEva is acting as an actual "condenser", absolute value of QCon should be **less than** the absolute value of QEva.

**Desktop (please complete the following information):**
I used Dymola 2023x on an ubuntu 20.04 environment

**Additional context**
This issue on heat pump condenser/evaporator heat flow calculation has actually been fixed on the IBPSA heat pump libraries about 2 months ago. Specifically, we can look at these examples at the IBPSA github "main" branch (https://github.com/ibpsa/modelica-ibpsa/tree/master/IBPSA/Fluid/HeatPumps/ModularReversible/Examples)

**Comment by FWuellhorst** [comment]
Thanks for raising this well documented issue! 
You are correct. I just merged the latest IBPSA version, were I fixed this issue, into AixLib. The "old" models will be moved to the Obsolete package, as the changes are not manageable using a conversion script. I would highly recommend using the new models. If you have questions on how to switch, please ask. I will try to give a short tutorial on how to switch from old to new HP models.

**Comment by wehuang16** [comment]
> Thanks for raising this well documented issue! You are correct. I just merged the latest IBPSA version, were I fixed this issue, into AixLib. The "old" models will be moved to the Obsolete package, as the changes are not manageable using a conversion script. I would highly recommend using the new models. If you have questions on how to switch, please ask. I will try to give a short tutorial on how to switch from old to new HP models.

Thank you!

**Comment by FWuellhorst** [comment]
@wehuang16 we moved the model in the latest main. Please see https://github.com/RWTH-EBC/AixLib/wiki/Switch-from-model-HeatPump-to-ModularReversible if you want to move from the old to the new approach.
