### ISSUE TITLE
Check if Record and used model are compatible

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#151]
We are already raising some warning if the weightfactors are not compatible to the used model. However it might make sense to integrate a mechanism that assert the weightfactors (or other parameters) and if they don't fit we shouldn't simulate the model.

This causes a lot of confusion

**Comment by mlauster** [comment]
So you mean we should turn the warnings into errors? If so, the reason to raise warnings and not errors was to theoretically allow unbalanced weightfactors for some (theoretical) cases. I agree, we can change them into errors.

**Comment by mlauster** [comment]
Ok, new idea: Implement an new parameter in ZoneBaseRecord, called `calculationCore` and check in thermalZonePhysics model if this EBC or VDI (or better numericals, that makes it easier to implement in parameter window (as radio buttons) as well for users without TEASER).

**Comment by PRemmen** [comment]
:+1:
