### ISSUE TITLE
The link OM in readme is outdated

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/AixLib#1512]
**Describe the bug**
The link for [![OM](https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/AixLib/development/badge_file/om_readyness_badge.svg)](https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/AixLib/development/badge_file/om_readyness_badge.svg) is not accessable. The link might be updated.

**Comment by FWuellhorst** [comment]
Fix in latest main
