### ISSUE TITLE
idealHeaterCooler - Cooler_on

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#152]
EnergyMeter for cooling (coolMeter) is always instantiated this causes an error if the Cooler is turned off. (reported by @SebastianStinner )

**Comment by mlauster** [comment]
we have two versions of ideal heater cooler, see #126. we should check the other model as well and take care of the duplication.

**Comment by PRemmen** [comment]
solved by #153 still two heater cooler in AixLib #126
