### ISSUE TITLE
HeatPump turns singular without modeSet input through Bus even if not reversible

### ISSUE THREAD

**Issue by Mov0** [RWTH-EBC/AixLib#1531]
**Describe the bug**
A heat pump based on _AixLib.Fluid.HeatPumps.HeatPump_ that only supports heating mode (_useRev_=false) and is not connected through the bus connector (_useBusConnectorOnly_=false) will turn structurally singular. Though the connector for _modeSet_ disappears correctly, when _useRev_ is set to false and the heat pump only supports heating mode, _modeSet_ does not seem to be set to true (for heating mode) internally. This results in the requirement to manually set _modeSet_ to true through the bus connector, which should not be necessary.

**To Reproduce**
1. Copy AixLib.Fluid.HeatPumps.Examples.HeatPump
2. Switch _useRev_ in _heatPump_ to false. Delete _booleanSwitch_, _hysCooling_, _logicalSwitch_ and _not2_, essentially simplifying the example to match a heat pump that is only capable of heating. See Screenshots.
3. Check the model

**Expected behavior**
The model should not require _modeSet_ to be assigned a value thorugh the bus connector

**Screenshots**
This is structurally singular:
![Screenshot 2024-08-14 160819](https://github.com/user-attachments/assets/67f5275e-a25d-4c04-bda5-0a2ed7349cc3)
While this is working:
![Screenshot 2024-08-14 160757](https://github.com/user-attachments/assets/ce517eb5-a0b5-439c-922d-95f49c1963e5)

**Desktop**
 Dymola2023x with Modelica 4.0.0 on Windows 10 22H2

**Comment by FWuellhorst** [comment]
That is true, thanks for raising this issue. I am currently in the process of moving the heat pump models to Obsolete #1520 . I will fix it when moving the models, but I would just advise to use the new models.
