### ISSUE TITLE
LOM.BuildingPhysics

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#154]
in Building.LowOrder.BaseClasses.BuildingPhysics.BuildingPhysics the parameter "orientationswallshorizontal" is hardcoded to {90,90,90,90,0}

"orientationswallshorizontal" should be added to the ZoneBaseRecord.

Is this a bug?

**Comment by mlauster** [comment]
Hm, good question if this is a bug. I think we could consider this as well as a development as we didn't have it in the BaseRecord so with your commit we enable a new feature (what on the other hand should have been enabled long ago). So whatever you think is best.

**Comment by PRemmen** [comment]
Development is fine :)

**Comment by PRemmen** [comment]
closed by #163
