### ISSUE TITLE
Replace obsolete pump model in storage examples

### ISSUE THREAD

**Issue by HannahRomberg** [RWTH-EBC/AixLib#1552]
**Problem**
The StorageBoiler and the StorageSolarCollector Examples within the Storage package use the obsolete pump model.

**Suggestion for solution**
Replace obsolete pump model with up to date pump model.

**Comment by FWuellhorst** [comment]
Good point. Maybe a good first issue for a hackday? :)

**Comment by HannahRomberg** [comment]
Issue already fixed. I was working with an older version...
