### ISSUE TITLE
Arbitrary number of zones with arbitrary orientations each

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#156]
With #150 we should be able to generate and run an arbitrary number of zones with with a variable number of orientations. But each zone will take the first n (number of orientations of zone) entries from the solRad vector. It is not possible take arbitrary entries of the solRad vector.
Example:
Orientations are {90,180,270,360}
Zone 1 has {90,180,270}, so it is correct to take the first three entries.
Zone 2 would like to have {270}, but gets {90}.

In my opinion the best way to solve that is to define a vector that specifies the orientations for each zone (and not only the number of orientations) and calculate solar radiation on zone level. According to Michael Wetter, this should have no influence on calculation speed as Dymola finds similar equations and calculates them only once. This approach also fits well to the Annex60 stuff for solar radiation.
I would introduce this new feature with the new Annex60 ROM's as it requires a lot of changes and goes hand in hand with introducing the solar radiation Bus.

**Comment by mlauster** [comment]
By the way, we get a vector with horizontal orientations anyway with #154 as we need this for `EqAirTempMod`.

**Comment by PRemmen** [comment]
I'm not quite sure about naming here (orientationswallhorizontal is very missleading) But #154 was for the Tilt angle this issue is for the azimuth angle.

**Comment by marcusfuchs** [comment]
Will be solved in #150
