### ISSUE TITLE
Remove non ASCII Characters from code

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#172]
Hi, as I've seen there was already #155 which dealed with a couple of files. However my search revealed additional files.
I suggest only ASCII characters and deg instead of °.
No special german letters: ü -> ue and ß->ss.
Otherwise I personally had problems in working with python with results generated using some models from AixLib.

**Comment by pema1** [comment]
Hi Ana,

As far as I know Dymola still seems to have problems with UTF8. A good workaround could be to use html substitutions:
&deg;C instead of °C

Do you use Python 2.x? I also suggest switching to >=3.4

Regards,

Peter

**Comment by marcusfuchs** [comment]
Let's go through all files and change to only one encoding standard.

**Comment by MichaMans** [comment]
I searched for Non ASCII Characters in the files. Found the following files with Non ASCIIs:
- 'D:\\GIT\\AixLib\\AixLib\\Building\\Components\\Weather\\BaseClasses\\Sun.mo', 1
- 'D:\\GIT\\AixLib\\AixLib\\Building\\Components\\Weather\\RadiationOnTiltedSurface\\RadOnTiltedSurf_Liu.mo', 39
- 'D:\\GIT\\AixLib\\AixLib\\Building\\Components\\Weather\\RadiationOnTiltedSurface\\RadOnTiltedSurf_Perez.mo', 1
- 'D:\\GIT\\AixLib\\AixLib\\DataBase\\Weather\\WeatherBaseDataDefinition.mo', 5

I'll have a look at it.

**Comment by mlauster** [comment]
@MichaMans, is this already in the master? Then we could close this issue.

**Comment by MichaMans** [comment]
@mlauster According to PR #230 this was merged into the development at 15.04.
I think it should be in the master then. We've let the issue open in case we need to change the file format of the files. I don't know if we should let this one open, since nobody seems to have an issue with the file format.

**Comment by mlauster** [comment]
Then let's close it an reopen if we get issues regarding the format

**Comment by MichaMans** [comment]
I found some more hits for the non ASCII character search in the development and master branch. I'm changing it in the development for now. 4 affected files found with 7 hits, all german ü.

**Comment by thorade** [comment]
Dymola 2018 release notes mention it is able to handle UTF-8 properly Section 3.2.6):
https://www.3ds.com/products-services/catia/products/dymola/latest-release/
https://www.3ds.com/fileadmin/PRODUCTS/CATIA/DYMOLA/PDF/Dymola_Release_Notes.pdf
Files will be saved as UTF-8 with BOM.

Also, OpenModelica will check the encoding whenever opening a library, so it is recommended to open the library in OpenModelica from time to time.
