### ISSUE TITLE
Revisions in AHU model

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#173]
As AHU does not work as desired when e.g. dehumidification is turned off, I perform some corrections in the model.

**Comment by mlauster** [comment]
@PMehrfeld, what is the current status on this?

**Comment by PMehrfeld** [comment]
The HRS issue is solved. I have just tested MultizoneExample with diverse AHU settings (including that every mode is disabled). This has worked fine so far.
I will do some work in the future to tidy up the code of AHU.mo. But for now, this is fine. 
@mlauster: You can merge via #185

**Comment by mlauster** [comment]
closed via #185
