### ISSUE TITLE
High Order Examples: Modifier for protected T_ground

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#174]
The models

- AixLib.Building.HighOrder.Examples.OFD_1Jan
- AixLib.Building.HighOrder.Examples.RoomGFOw2_DayNightMode

modify the protected variable `T_ground`, which is not legal Modelica.

**Comment by AnaConstantin** [comment]
Great, I also just now learned how to add this dreaded each. Thanks.
I can merge development into this branch, test it and then send another pull request. I have to get the hang of the work flow, and best way to do it is by practice.
I'll do the same with the branch for issue #175
