### ISSUE TITLE
Remove HVAC package

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#180]
Before, solve #177.

**Comment by PMehrfeld** [comment]
@marcusfuchs: please mention here when PR #220 is merged.

**Comment by marcusfuchs** [comment]
See my comments in #220

**Comment by marcusfuchs** [comment]
#220 is merged.

**Comment by mlauster** [comment]
Will be removed if no objections until 11.08.2016

**Comment by mlauster** [comment]
closed via #283
