### ISSUE TITLE
Evaluate SimpleValve and ThermostaticValve

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#182]
Evaluate how to proceed with SimpleValve and ThermostaticValve

Advantages/Disadvantages to have them in parallel to Annex60 models?

**Comment by mlauster** [comment]
This is our current strucutre of valves in our internal lib:

![valves](https://cloud.githubusercontent.com/assets/6892690/19269403/ae49b688-8fba-11e6-8f84-698bc817f51d.png)

Based on this, we should decide from which level to switch to Annex60 base models and which upper-level models to keep.

**Comment by mlauster** [comment]
Way forward:
Check if `MixingValve` can be replaced by Annex60-`MixingValve and `ValveIncompressible` by MSL version or an Annex60 equivalent. If so, keep `ThermostaticRadiatorValve` and `FloorheatingValve` and base them on standard components. Get rid of all other models, except possibly `ThermHead`, what might in this case be cleaned up and refactored.
@mlauster will clarify with @AnaConstantin and @RoozbehSangi  if there are any objections and who can do what.

**Comment by mlauster** [comment]
After moving our internal model into `AixLib`, we can delete `SimpleValve` and `ThermostaticValve`.

**Comment by mlauster** [comment]
See related #208

**Comment by mlauster** [comment]
After contacting @AnaConstantin and @RoozbehSangi, this is the way to go:

- `ThermostaticRadiatorValve` and `FloorheatingValve` are the only two models that will be moved to `AixLib`. For that, they will be refactored to divide physical model and control. For the physical model, we try to allow choosing between `MSL.Valves` (which are similar to our old `Valve.Incompressible`) and the `IBPSA.Fluid.Actuators.Valves`. For the controls, the idea is to allow `ThermHead` for thermostatic valves and miscellaneous others, e.g. for floor heating, from `MSL` or `IBPSA`. I fear this can only be done by @AnaConstantin .
-   In our current version of `AixLib`, we have three own implementations. `SimpleValve` and `ThermostaticValve` will be deleted. `MixingValve` needs evaluation and comparison against `ThreeWayEqualPercentageLinear` and `ThreeWayLinear`. As `MixingValve` has been inspired by the `Buildings`-Library models, it might be quite similar to `ThreeWayEqualPercentageLinear` and `ThreeWayLinear` (they originate from `Buildings`-Library too). This can be done by @RoozbehSangi or possibly @mlauster will give it a try.

**Comment by RoozbehSangi** [comment]
@mlauster At the time MixingValve was developed, there used to be only SimpleValve and ThermostaticValve in our library. Since SimpleValve is going to be deleted, MixingValve should be deleted too, as MixingValve is based on SimpleValve. The following examples should also be deleted:
AixLib.Fluid.Actuators.Valves.Examples.MixingValveBackwardDirection
AixLib.Fluid.Actuators.Valves.Examples.MixingValveForwardDirection

**Comment by mlauster** [comment]
Thanks, @RoozbehSangi, then the remaining open point is refactoring and moving `ThermostaticRadiatorValve` and `FloorheatingValve`, see comment https://github.com/RWTH-EBC/AixLib/issues/182#issuecomment-296988825 above. @AnaConstantin is in charge of that, so I will assign her to that issue.

**Comment by mlauster** [comment]
I will close this issue for now, since there seems to be no real need to migrate `ThermostaticRadiatorValve` and `FloorHeatingValve` at the moment. If this comse up again, please reopen.
