### ISSUE TITLE
move EBC boiler into AixLib

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#186]
This model is already MSL conform and needs only minor revisions in documentation and naming. We need it for FastHVAC

**Comment by SebastianStinner** [comment]
EBC boiler has a lot of control elements included in the model. It might be better to split up the modeling and control parts in two different models. In FastHVAC, we already have a model without control and separated controllers.

**Comment by mlauster** [comment]
I vote for separating controls and model

**Comment by AnaConstantin** [comment]
I also have a model which separetes physical model, internal control (reaching a set temperature) and external control (e.g. heating curve). However the question remains: just move the model as it is, or improve the model in the same step.

**Comment by marcusfuchs** [comment]
I'd be ok with collecting such models at least in an AixLib branch. Then from case to case I suggest to compare the models and decide on the next steps.

**Comment by SebastianStinner** [comment]
@AnaConstantin Can you transfer your model to the AixLib?

**Comment by AnaConstantin** [comment]
I'll transfer it in five minutes, as an idea how it is structured, to see if you like it. All the records have to come as well from the DataBase, some small controllers (onOff, a simple PITemp), as well as examples. This will take some time.

**Comment by PooyanJahangiri** [comment]
In order to use a single partial model for both Boiler and CHP and other future models this issue has been addressed together with #188. For further developement in the boiler model please create another thread.

**Comment by AnaConstantin** [comment]
Close the issue #186 and start a new one from the model created by @PooyanJahangiri
