### ISSUE TITLE
move EBC heat pump into AixLib

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#187]
We already have a branch for this (Annex60_HP_review) and the model should be already in a good state. We need it for FastHVAC

**Comment by marcusfuchs** [comment]
Please consider branch `Annex60_HP_Review`

**Comment by PMehrfeld** [comment]
This issue and branch only transferred necessary models from EBC Libs to AixLib.
Branch `Annex60_HP_review` is further developed!
- [ ] branch `issue187_moveHeatPump` must be deleted

**Comment by PMehrfeld** [comment]
branch is deleted. Further discussion see #264
