### ISSUE TITLE
move EBC CHP into AixLib

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#188]
This model is already MSL conform and needs only minor revisions in documentation and naming. We need it for FastHVAC

**Comment by SebastianStinner** [comment]
EBC CHP has a lot of control elements included in the model. It might be better to split up the modeling and control parts in two different models. In FastHVAC, we already have a model without control and separated controllers.

**Comment by mlauster** [comment]
Sounds like a good approach, I vote for it.

**Comment by mlauster** [comment]
merged via #296
