### ISSUE TITLE
move EBC buffer storage into AixLib

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#189]
This model needs some review regarding:
- [ ] structure
- [ ] MSL conformity
- [ ] documentation
- [ ] naming

We currently have a lot of dependencies to other models in EBC libs. We should check which models need to be moved as well, what their status is and if they can be replaced by AixLib or Annex60 models. If models need to be moved, we need to discuss where to put them in AixLib (in one `BaseClasses` package for `Buffer Storage` or into dedicated packages like `HeatTransfer`)

**Comment by marcusfuchs** [comment]
It would be great if within this issue or as a separate issue we could also evaluate the model `AixLib.Fluid.Storage.Storage` that is already in AixLib. Do we still need that (maybe for `FastHVAC`?) and if so, do we have sufficient examples and unit tests?

**Comment by SebastianStinner** [comment]
We do not need the AixLib.Fluid.Storage.Storage for FastHVAC as we are using the core of EBC buffer storage.

**Comment by marcusfuchs** [comment]
Perfect, this is on `development`!
