### ISSUE TITLE
Utilitites.HeatTransfer: _old models still necessary?

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#201]
The package `Utlities.HeatTransfer` should be checked for old models: Can we add information to the docs under which circumstances the _old model can be removed?

**Comment by AnaConstantin** [comment]
Model should be removed.
Will also delete AixLib.Building.Components.Walls.BaseClasses.ConvNLayerClearanceStar_old.

**Comment by marcusfuchs** [comment]
This is merged with #219
