### ISSUE TITLE
Consider moving AixLib.Utilities.Control to AixLib.Controls

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#202]
It may be reasonable to move `AixLib.Utilities.Control` to `AixLib.Controls`

**Comment by PRemmen** [comment]
Agree!

**Comment by PRemmen** [comment]
I will move PITemp to Continuous controllers and create new package for ventialtionController, any objections?

**Comment by mlauster** [comment]
I'm fine.

**Comment by marcusfuchs** [comment]
No objections.
