### ISSUE TITLE
Remove uses of HVAC.Meter

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#204]
The models 
`AixLib.HVAC.Meter.EEnergyMeter` 
and 
`AixLib.HVAC.Meter.TEnergyMeter` 
are duplicates of 
`AixLib.Utilities.Sensors.EEnergyMeter` 
and 
`AixLib.Utilities.Sensors.TEnergyMeter`

The following models should change their components to be used from `Sensors` rather than `HVAC`:
`AixLib.Building.HighOrder.Examples.Validation.ASHRAE140.Case600`
`AixLib.Building.HighOrder.Examples.Validation.ASHRAE140.Case900`
`AixLib.Building.LowOrder.Examples.ThermalZoneExample`
`AixLib.Building.LowOrder.Examples.Validation.ASHRAE140.Case950`
`AixLib.Fluid.HeatExchangers.Utilities.FuelCounter`

This should be solved before #180

**Comment by PRemmen** [comment]
Couldn't find any usage of ```EEnergyMeter``` or ```TEnergyMeter``` in ```AixLib.Fluid.HeatExchangers.Utilities.FuelCounter```

**Comment by marcusfuchs** [comment]
That was probably my mistake, can't find any usages of the duplicate HVAC meters in AixLib in your branch, so that should be fine

**Comment by marcusfuchs** [comment]
This is now on `development`
