### ISSUE TITLE
Duplicate example models for Radiator model

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#205]
The models
`AixLib.Fluid.HeatExchangers.Examples.PumpRadiatorThermostaticValve`
and
`AixLib.Fluid.HeatExchangers.Examples.PumpRadiatorValve`
are duplicates of
`AixLib.Fluid.HeatExchangers.Radiators.Examples.PumpRadiatorThermostaticValve`
and 
`AixLib.Fluid.HeatExchangers.Radiators.Examples.PumpRadiatorValve`

We should decide which ones to keep.

**Comment by PRemmen** [comment]
As they use several components from fluid:

- Valve/ThermostaticValve
- Pump
- Boiler
- Pipe

I vote to move them to Fluid.Examples

**Comment by AnaConstantin** [comment]
I agree with @PRemmen. Could you please move the still existing examples to Fluid so we can close the issue?

**Comment by PRemmen** [comment]
solved by #362
