### ISSUE TITLE
Fix unit tests for LOM

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#210]
There are existing unit tests for `AixLib.Building.LowOrder.Examples.Validation.VDI6007`.

We should check whether these can still be used, need to be refined or should be deleted.

**Comment by marcusfuchs** [comment]
The problem seems to be that the unit tests still point to the package 
`AixLib.Building.LowOrder.Examples.Validation.Linear` while the example models are in `AixLib.Building.LowOrder.Examples.Validation.VDI6007.Linear`. This should be fairly easy to fix. I will remove the old reference results and fix this.

**Comment by mlauster** [comment]
Since we test that models automatically in IBPSA library, this issue is obsolete. I will close it, please reopen if new activities are planned.
