### ISSUE TITLE
Annotation experimentSetupOutput(events = false) in LOM Validation Star

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#217]
E.g. `AixLib.Building.LowOrder.Examples.Validation.VDI6007.Star.TestCase1` uses the annotation `experimentSetupOutput(events = false) `, which is not accepted by pedantic checking (which the unit tests do, I think). 

@mlauster @PRemmen : Can we remove this annotation?

**Comment by mlauster** [comment]
Is done in #129, PR #222

**Comment by marcusfuchs** [comment]
Then we can close this.
