### ISSUE TITLE
Move EBC Radiator_ML into AixLib

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#225]
This model is already MSL conform and needs only minor revisions in documentation and naming. We need it for FastHVAC

**Comment by PRemmen** [comment]
When I check the moved radiator i get following error, does anyone has an idea?

`Check of AixLib.Fluid.HeatExchangers.Radiators.Radiator_ML_EBC:

Component type specifier BaseProperties is a partial type.
File: D:/GIT/AixLib/AixLib/Fluid/Interfaces/ConservationEquation.mo, line 82
Component context: multiLayer_HE.Volume.dynBal.medium
Component declared as Medium.BaseProperties medium in Modelica.Media.Interfaces.PartialMedium`

**Comment by mlauster** [comment]
This is taken care of #297 so I close this issue
