### ISSUE TITLE
HydraulicResistance uses problematic formulation in flow equation.

### ISSUE THREAD

**Issue by pema1** [RWTH-EBC/AixLib#232]
# Flow Equation Should be Changed
## Problem
While pondering on issue #206 I found that the model HydraulicResistance computes the a wrong flow direction in my test case. The reason lies in the flow equation:
`dp = 8 * zeta / (Modelica.Constants.pi ^ 2 * D ^ 4 * rho) * m_flow^2`

As positive and negative mass flow would lead to the same pressure difference in this equation. It probably depends on where the solver starts looking for a solution for where you will finally end up. In my simple case it was always the wrong solution.

## Soultion
The equation can be reformulated like this to tackle the mentioned problem:
`dp = sign(m_flow) * 8 * zeta / (Modelica.Constants.pi ^ 2 * D ^ 4 * rho) * m_flow^2`

## Optimisation of Formula
In older Dymola versions I realized that quadratic or higher exponent terms (b^n) would often lead to slower simulation time in general compared to computation of `b*b*b...` Also strange results for small bases b could occur leading to simulation crash. I suspect the compiler will use a different approach to compute both terms. Therefore, I would change the equation like this:
`dp = sign(m_flow) * 8 * zeta / (Modelica.Constants.pi * Modelica.Constants.pi * D * D * D * D * rho) * m_flow * m_flow`

## Side Note
**HydraulicResistance** extends Interfaces.**PartialTowPortTransport**. This has the (unusual?) definition:
`dp = port_a.p - port_b.p`
meaning that positive flow from a to b leads to positive(!) dp. Many models would assume that positive flow would lead to negative pressure difference - suggesting a loss of pressure. Not so here.

**Comment by marcusfuchs** [comment]
The model `AixLib.Fluid.Interfaces.PartialTwoPortTransport` is from the Annex 60 project. I agree, that `dp = port_b.p - port_a.p` would be more intuitive than `dp = port_a.p - port_b.p`. We can address this in the next Annex 60 conference call and see what the general feelings about this are.

**Comment by pema1** [comment]
The optimization aproach did not leed to an improvement of simulation speed in my simple test case. I will add a graphic that showes the result.

Interestingly, the HydraulicResistance test model is much slower (+60%) than the FixedResistancesDpM test model. The selection of the equation from (from_dp=true or false) is not the reason for the speed differenence. I assume the better initialization in FixedResistancesDpM might be the reason. Bear in mind that only a fraction of the computational effort goes into the two models which means that the difference in simulation speed between the two models is far bigger than 60%!

Improving the HydraulicResistance model for simulation speed could be worth while.

**Comment by marcusfuchs** [comment]
Solved in #234
