### ISSUE TITLE
AHU fails if V_dot_sup is zero

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#242]
The AHU fails if the suplly volume flow is zero. We should take care of this. 
One solution is to set the supply volume flow to a very small parameter (Modelica.Constants.eps) if the supply volume flow is zero.
A better option is to check if the model has an equation which can be converted in an equation where V_dot_sup doesn't is the denominator.

**Comment by MichaMans** [comment]
I would suggest to convert the equation:
`dTFan = P_el_sup/(V_dot_sup*rho * (c_pL_iG + X_oda * c_pW_iG));`
into
`P_el_sup = dTFan * V_dot_sup*rho * (c_pL_iG + X_oda * c_pW_iG);`
so we can handle the case that V_dot_sup is zero.

**Comment by mlauster** [comment]
Have you tested if that solves the problem / if this is the critical equation? Anyway, I don't see a drawback in this formulation, sounds promising!

**Comment by MichaMans** [comment]
I did a short test and it worked. I'm going to implement it and create a PR if it really works.

**Comment by PMehrfeld** [comment]
closed by #243
