### ISSUE TITLE
OpenModelica: ERROR on opening TEASER constructed Modelica Model "melaten_campus.py":

### ISSUE THREAD

**Issue by R33B** [RWTH-EBC/AixLib#256]
[1] - [334] uncritical errors

[335] 12:05:49 Grammatik Fehler
.../Project/M5980/package.mo: 1:1-4:10]: Expected the package to have within Project; but got within ;.

[336] 12:05:49 Skripting Fehler
Failed to load package Project () using MODELICAPATH ...\teaser\OutputData\;C:/OpenModelica1.10.0-dev-64bit/lib/omlibrary.

**Comment by R33B** [comment]
ERROR of same type:

> [5] 15:28:19 Grammatik Fehler
> [.../Anaconda2/Lib/site-packages/teaser/OutputData/Project/SuperBuilding/SuperBuilding.mo: 1:1-116:18]: Expected the package to have within SuperBuilding; but got within ;.
> 
> [6] 15:28:19 Skripting Fehler
> Failed to load package SuperBuilding () using MODELICAPATH ...\Anaconda2\Lib\site-packages\teaser\OutputData\Project\; .../OpenModelica1.10.0-dev-64bit/lib/omlibrary.

**Comment by mlauster** [comment]
This is a problem of TEASER and willl be solved in https://github.com/RWTH-EBC/TEASER/issues/254

I will close it here.
