### ISSUE TITLE
Aixlib.Fluids.Movers.Pump with ON/OFF

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/AixLib#268]
There is no simple table based pump that can be turned off. I will work on a solution.

**Comment by marcusfuchs** [comment]
@tstorek
This seems related to #184 where we would like to see which pump models are needed for future applications. In the issue title, you refer to the specific model `Aixlib.Fluids.Movers.Pump`. For your application, do you specifically need the model `Aixlib.Fluids.Movers.Pump` with additional on/off functionality or could another model for the pump behavior also be ok? And using a model like `AixLib.Fluid.Movers.FlowControlled_m_flow` and setting the input signal to 0 does not work for you?

**Comment by mlauster** [comment]
@tstorek, is this still an issue for you or did you find a working solution?

**Comment by PMehrfeld** [comment]
@tstorek: I absolutely agree with @marcusfuchs' comment!
Just set the input to 0 and everything is fine, right?
Especially, since we are aiming to keep control and component separated.

**Comment by tstorek** [comment]
@mlauster I think I will work for now with the movers that are already existing. That works fine for now.
@PMehrfeld Yes, that is a possible solution. I am not exactly sure but I think that the models changed since I opened the issue and forgot to close it. However, by setting the m_flow to zero would not exactly do the same as a switch. Nevertheless, for the solver it is probably easier to handle. In reality one would send a signal for volume and not for mass. Maybe we should think about changing that. Since we want to support different types of fluids, V_flow would make things easier. Also from the principle of pumps it would be senseable from my point of view. Right now the models already contain their controller. I think in the near future we will reconsider this approach anyways in order to achieve our goal to seprate controls and physical models.

**Comment by PMehrfeld** [comment]
Thanks. Sounds like we can close this issue.
No branch exists to this issue, so we do not need to delete any branch.
If you want to model this approach for volume flow, you can just open a new issue, @tstorek
