### ISSUE TITLE
Arbitrary discretisation of wall layers and insertion of heated layers possible in wall model 

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#271]
Wouldn't it be great if we were able to discretise the wall layers according to wonderfully thought out functions?!
Additionally wouldn't it be great to be able to introduce heated layers (cooling also possible) between chosen wall layers (layers that may have been discretised already)?!
@mlauster and @HenrykWolisz wouldn't it be great?

**Comment by PMehrfeld** [comment]
Just came by to push this quite old issue and branch [issue271_discWall](https://github.com/RWTH-EBC/AixLib/tree/issue271_discWall) ;)

**Comment by mlauster** [comment]
@AnaConstantin, is there any work on this? I suspect not, so I will set this to stale.

**Comment by mlauster** [comment]
@AnaConstantin, I suspect there is lot of work still to do here, right? I will close this issue for now, please reopen if work is still planned.
