### ISSUE TITLE
EEnergyMeter vs. TEnergyMeter

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#272]
For me the two sensors (`AixLib.Utilities.Sensors.TEnergyMeter` and `EEnergyMeter`) are almost duplicates.
In my opinion they can be merged to only one EnergyMeter.
What do you think?

**Comment by pema1** [comment]
In fact they are identical in that **TEnergyMeter** is extending **EEnergyMeter**. Alexander has probably implemented both as a means to easily setup seperate instances with _sensible default names_. If you omit the TEnergyMeter model you would need to remember to to change the default instance name every time. 

I would suggest to leave it in as the overhead is minimal - or change the name to **EnergyMeter**.

**Comment by PMehrfeld** [comment]
Yes, I understand your argumentation but I think renaming it to EnergyMeter might be the best solution.
Also I find it confusing that the input connector is flipped horizontally compared to regular usage.

Any further opinions?

**Comment by pema1** [comment]
I have no other options to suggest. I am OK that you remove and rename. Maybe you should should add the changes to a conversion script. I suppose that most people used the TEnergyMeter model. The change would probably also brake some models like boiler or heat pump.

**Comment by PMehrfeld** [comment]
Upon brief consultation with Marcus Fuchs the topic of conversion scripts and raise of the version number will be discussed in our next modelica meeting. So this issue has to rest at least till 29 Aug.

Anyway, a hint by Marcus was to add a comment in the documentation that due to the derivative the whole input is one state and can lead to reducing the simulation performance significantly.

**Comment by pema1** [comment]
The state selection is very unfortunate in this case. I tried to improve by 
`q_joule(stateSelect = stateSelect.avoid)`. However, that does not work sufficiently. Even `stateSelect.never` does not change the behaviour in the cases I have seen. 

@marcusfuchs do you see another way to implement such a sensor for plotting? Using the `sum()` function in the plot window does not produce a cummulative sum. The Handbook suggests using `stateSelect.never` but that does not seem to work.

As it is only a convenience model for plotting and it might reduce simulation speed I would argue to remove the model or place a notification in the icon to avoid that model if possible.

**Comment by PMehrfeld** [comment]
The model will probably be changed and implemented with a conversion script just before or at hack day. Ana is going to present a workflow about conversion scripts for AixLib (@AnaConstantin).

**Comment by PMehrfeld** [comment]
- removed two models and used duplicate of `EEnergyMeter` regardless of conversion script
- added info that might slow down simulation speed (preferred view is info)
- see PR #284

**Comment by marcusfuchs** [comment]
This is on development branch.
