### ISSUE TITLE
Plate Heat Exchanger

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/AixLib#274]
In the fluid-library I miss a adequate model of a plate heat exchanger, where the efficiency depends on the conduction coofficient of the material and the size of the area. Additionally, the model should be able to handle different fluid properties on each side of the heat exchanger. In the HVAC library there was a simple model like that but unfortunately it  cannot handle the different fluid properties of the fluid-library. Thus, unfortunetly they are not 100 % compatible.
It would be great if something like that could be added.
Thank you.

**Comment by marcusfuchs** [comment]
Paul and I will transfer the old simple HVAC model to AixLib until we have a better model available

**Comment by tst-pth** [comment]
I have done an updated Heat Plate Exchanger Model based on the model developped by Thomas Dixius. The model uses only components from the AixLib and Modelica-Library.

**Comment by PMehrfeld** [comment]
Work continues in #486

**Comment by DaJansenGit** [comment]
Due to there is no progress in #486 I will close this issue for now.  Of course it can be reopened at any time!
