### ISSUE TITLE
Integrate Building into ThermalZones

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#276]
On the long run, we should incorporate our models for building physics, currently at home in `AixLib.Building`-package, into `AixLib.ThermalZones`-package to comply with `Annex60`-structure. 
For `AixLib.Building.LOM`, major parts are done in #260, this issue here is to collect and solve remaining parts of `AixLib.Building`:
- [x] Move `AixLib.Building.LowOrder.Validation.ASHRAE140` to `AixLib.ThermalZones.ReducedOrder.Validation.ASHRAE140`. For that, the test cases need to be modified to use `AixLib.ThermalZones.ReducedOrder` models and possibly `AixLib.BoundaryConditions` weather data handling
- [x] Move `AixLib.Building.HighOrder`. @AnaConstantin, can you estimate how much work that is and what has to be done for that?
- [x] File through `AixLib.Building.Components` and decide where they should find their new home. I suggest to:
  - [x] Move major parts (`AixLib.Building.Components.Walls`, `AixLib.Building.Components.WindowsDoors`,`AixLib.Building.Components.DryAir`) to `AixLib.ThermalZones.HighOrder` .
  - [x] Get rid of `AixLib.Building.Components.Weather` or integrate it in `AixLib.BoundaryConditions`.
  - [x] Find a new home for `AixLib.Building.Components.Sources`. They are used by `AixLib.Building.HighOrder` and `AixLib.Building.LowOrder`, one solution could be to integrate them in `AixLib.Building.HighOrder` or `AixLib.Utilities.Sources`.

**Comment by PRemmen** [comment]
partly solved with #368 (only for LOM)

**Comment by mlauster** [comment]
closed via #599
