### ISSUE TITLE
Database includes very old references

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#285]
The Database records include statements like `Record is used in model <a href=\"AixLib.HVAC.Sources.TempAndRad\">AixLib.HVAC.Sources.TempAndRad</a>`, which refer to models that are no longer present in the library. I will clean that up.

**Comment by mlauster** [comment]
@marcusfuchs, do you plan to do this until V.04?

**Comment by PMehrfeld** [comment]
Closed by #370

**Comment by mlauster** [comment]
Pipes database package needs to be reintegrated

**Comment by mlauster** [comment]
closed via #380
