### ISSUE TITLE
SolarCollectorSystem 

### ISSUE THREAD

**Issue by KFinkbeiner** [RWTH-EBC/AixLib#293]
- Compare thermal collector models (AixLib vs. HVAC)
- In case of further use of the HVAC model
                     \* remove the integrated sun model
                     \* move into AixLib

**Comment by KFinkbeiner** [comment]
--> AixLib thermal collector model is highly simplified compared to the HVAC model

**Comment by KFinkbeiner** [comment]
- [ ] Comparison of the collector models from HVAC and Buildings lib.
         - IAM function
         - efficiency model
         - heat losses at standstill
         - model parametrization (data availability)

**Comment by mlauster** [comment]
When you are ready to implement it in `AixLib`, please create a `SolarCollector` package in `Fluid`.

**Comment by MichaMans** [comment]
From a first quick view it seems to be a very simple model. The existing models of the modelica-buildings for example are more detailed. Do you think it makes sense to implement a solarthermal model? In addition it seems that there is no need at the moment for such a model.

**Comment by mlauster** [comment]
If the `Buildings` model is not yet part of `IBPSA`, we could ask Michael Wetter to add it. This would then require agreements form all other institutions, but should be feasible.

**Comment by mlauster** [comment]
Is someone still interested in moving that model? Otherwise we could close that issue

**Comment by PMehrfeld** [comment]
In my opinion, a solar thermal collector would definitely beneficous for us (as long as no similar model exist in the other libraries)!

1. @KFinkbeiner: Can you wrap up your investigation about the differene models in the different libraries. We do not need to have something redudant.

1. If we leave the solar thermal collector, which is already in master, we have to correct it:

- [ ] The efficiency must be calculated with the mean temperature (flow and return) of the solar thermal collector. Currently, the efficiency calculation model only has the flow temperature as input (s. below)

- [ ] The efficiency must provide an upper limit. `dT` can become negative and as a consequense, eta might raise significantly high. Solution: limit it to `Collector.eta_zero` with: `eta = min(Collector.eta_zero, Collector.eta_zero - Collector.c1 * dT / G - Collector.c2 * dT * dT / G);`. Although, it might be physically more correct to have knowledge about the behaviour of `eta` for negative `dT`s. But in literature there only exist litte data about this. Furthermore, this a really rare status. Therefore, in my opinion, limit it to `eta_zero` is an absolutely sufficient solution.


![grafik](https://user-images.githubusercontent.com/11769433/31539738-d64cbab6-b009-11e7-87eb-f624a720ba51.png)

**Comment by PMehrfeld** [comment]
Closed by #470
