### ISSUE TITLE
FVUandExergyMeter

### ISSUE THREAD

**Issue by RoozbehSangi** [RWTH-EBC/AixLib#301]
Two packages are going to be integrated into AixLib; a package that contains models for Facade Ventilation Unit (FVU) and its controller. FVU model can be used for heating, cooling and ventilation purposes. The second package contains a tool to perform the exergy analysis of HAVC systems.

**Comment by marcusfuchs** [comment]
@RoozbehSangi 
It's great that you address this integration! Regarding the workflow, could you consider doing the integration of FVU and exergy meter in two separate issues if that does not increase your workload too much? Two separate pull requests may be easier to review and maintain in the future.

**Comment by RoozbehSangi** [comment]
Done!
