### ISSUE TITLE
Extend HeatPump Model to work as a Chiller and as a reversible Heat Pump

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#308]
Work on AixLib.Fluid.HeatPumps.HeatPumpDetailed
To Do:
1. Create three modes: heat pump, chiller and reversible
2. Introduce variables Tuse and Tsource and rewrite equations for TEv and TCon
3. Model should still allow for caracteristic data in both table and polynomial form, but package all necessary information in a record for both cases

**Comment by AnaConstantin** [comment]
Additionally compare to existing Models from Annex60 and describe the differences in the documentation

**Comment by MBaranskiEBC** [comment]
Extension: 
1. Add an interface for external control based on the bus connector

**Comment by MBaranskiEBC** [comment]
I suggest we move the controller interfaces to [https://github.com/RWTH-EBC/AixLib/issues/354](url) to have a better overview and create pull request more frequently.

**Comment by mlauster** [comment]
@MBaranskiEBC, is somebody actively working on this issue? I will otherwise postpone it to a future milestone.

**Comment by mlauster** [comment]
Covered in #57, since nothing is happening here, I will close it.
