### ISSUE TITLE
Integrate FastHVAC Package

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#309]
We should try to integrate the FastHVAC Package. First list of things to do (please add your points):

- [ ] Integrate a FastHVAC Package to the structure
- [ ] Integrate Interfaces
- [ ] Integrate Components
- [ ] Integrate Examples

At the moment we are not really forcing an implementation, but we want to start an integration step by step.

**Comment by TobiasBlacha** [comment]
These models still have to be transferred into the AixLib:
- [ ] ActiveWalls Package: Panelheating_1D_Dis and BaseClasses
- [ ] Controller Package (if we want to have its own controller package for the fastHVAC)
- [ ] Eletrical Package: PowerConsumptionUC
- [ ] HeatExchanger Package: DHWHeatExchanger, MultiRadiator, Radiator_ML and BaseClasses
- [ ] Solar_UC Package: PVsystem (Eletrical), SolarCollectorSystem (Thermal) and BaseClasses
- [ ] Valves Package: Manifold, Splitter, ThressWayValve, ThermostaticValve and BaseClasses
- [ ] UC Package
- [ ] Examples: ActiveWalls, HeatExchanger, Pipes, Pumps, Sensors, Sinks, Valves, Solar_UC, Systems

**Comment by MichaMans** [comment]
Workflow recommendations:
- checkout a new branch from development branch
- checkout specific files or folder you want to integrate in small steps with:
git checkout issue309_fastHvac -- Path/To/Your/Specific/File
- add and commit these files, to adjustments, make PR

**Comment by mlauster** [comment]
close via #489
