### ISSUE TITLE
Module-based AHU model 

### ISSUE THREAD

**Issue by KFinkbeiner** [RWTH-EBC/AixLib#310]

**Comment by marcusfuchs** [comment]
@KFinkbeiner 
Thanks for starting this issue. Could you please add 1-2 sentences of description to inform everyone about what the aim of this development is?

**Comment by KFinkbeiner** [comment]
Firstly, the aim is to develop a modular model of an air handling unit (AHU). The modular modeling approach enables the modeling of AHU with different component configurations in a time efficient manner. Further, the modular modeling approach simplifies the on-going development of individual components, as well as the entire AHU.
Secondly, the model should be suitable to the AixLib low-order building models. Here, a map based (states of moist air – Mollier diagram) modeling approach is pursued, which promises a reasonable computation time.

**Comment by Mathadon** [comment]
This may be of interest: https://github.com/open-ideas/IDEAS/issues/571

**Comment by Mathadon** [comment]
This too: http://www.tandfonline.com/doi/full/10.1080/19401493.2016.1273391

**Comment by mlauster** [comment]
Could we close this issue and have further discussion in #360 to prevent similar discussions in several issues, @KFinkbeiner?

**Comment by KFinkbeiner** [comment]
Sorry for missed comments. The current status of the development is:
1. A list of all AHU components is prepared
2. Refering the thermodynamic function (coolin, heating...) and the used technology, the list is sorted 
3. The component performance is identified in the Mollier diagram and is described by corresponding equations 
4. First component models are implemented and we run first tests

**Comment by PMehrfeld** [comment]
@KFinkbeiner : I am not sure what the current status is here. But I set the milestone to next version which is due on 30 May 2018. Maybe you can solve this issue (partially) at the institute's hack day ;)

**Comment by LauraMaier** [comment]
@KFinkbeiner Maybe you can work on this issue at the institute´s hack day tomorrow :)

**Comment by KremerMartin** [comment]
@KFinkbeiner As we have some models ready, only needing some refinement, this maybe could be a task for the hacktober. ;) Especially on the Hackday next week. :)

**Comment by Dawac** [comment]
@KFinkbeiner : As there is no branch linked to this issue and the topic seems to also be discussed in #360, we will close this issue on the upcoming Hackday

**Comment by KremerMartin** [comment]
@Dawac I will open a new issue. On the upcoming Hackday, I will provide the actual development of the new modular equation-based AHU model on the regarding branch.
@KFinkbeiner Maybe we could work together on this, if you've got time on the next Hackday. ;)

**Comment by KremerMartin** [comment]
Closed by #834 .
