### ISSUE TITLE
Missing base class AixLib.Media.PerfectGases.MoistAirUnsaturated

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#311]
The base class "AixLib.Media.PerfectGases.MoistAirUnsaturated" of model "AixLib.Utilities.Psychrometrics.Examples.WetBul_pTX.Medium" is unknown.

**Comment by tbeu** [comment]
I tested with current master.

**Comment by AnaConstantin** [comment]
We has a new release at the end of last year. 
@tbeu could you please check if this issue is still current? Thank you

**Comment by tbeu** [comment]
Can no longer reproduce. Thanks.
