### ISSUE TITLE
Missing dependency on Modelica_Synchronous in uses annotation

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#312]
As AixLib.Airflow.AirHandlingUnit.AHU uses components from Modelica_Synchronous, the uses annotation of the AixLib package should indicate that dependency and the used version.

**Comment by PMehrfeld** [comment]
@tbeu : Quite a good hint. I will take care of this.

**Comment by PMehrfeld** [comment]
see #314

**Comment by marcusfuchs** [comment]
This is now on the development. Considering that we'll merge development soon into the master, do we need to make this change as a bugfix in master additionally, or can we wait für v0.4.0?

**Comment by tbeu** [comment]
I tested with current master.

**Comment by AnaConstantin** [comment]
We has a new release at the end of last year.
@tbeu could you please check if this issue is still current? Thank you

**Comment by tbeu** [comment]
Can no longer reproduce. Thanks.
