### ISSUE TITLE
Integration of ncDataReader

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#313]
I am currently working on getting an alternative data reader integrated into AixLib since I have faced many issues with CombiTimeTables in the context of complex simulations.
The repo is located here: [https://github.com/tbeu/netCDF-DataReader](url)

I will discuss two issues in that repository and report the news here.

**Comment by tbeu** [comment]
Can you please share your issues with the CombiTimeTable. Ist it about [mo:#2080](https://trac.modelica.org/Modelica/ticket/2080)?

**Comment by thorade** [comment]
Feel free to also comment here:
https://github.com/UdK-VPT/BuildingSystems/issues/12
Maybe we could have one very good data reader in Annex60?

**Comment by tbeu** [comment]
@thorade Thanks for cross-referencing. I even forgot about it and the ideas mentioned therein.

**Comment by PMehrfeld** [comment]
I have commented the issue here:
https://github.com/UdK-VPT/BuildingSystems/issues/12

Hopefully, I will have a look at https://trac.modelica.org/Modelica/ticket/2080 next week.

**Comment by PMehrfeld** [comment]
@fwuellhorst : Write documentation and migrate NcDataReader model into AixLib

**Comment by mlauster** [comment]
Closed via #340

**Comment by PMehrfeld** [comment]
With commit 996399fc0633dbd3949dcc94ef03d17ca6ddde2d I deleted parameter standard values. But for string vectors `varName`, `attNameReal` and `attNameInt` at least empty strings like `{""}` are necessary, otherwise error occurs `Failed to expand the variable NcDataReader_test.varName`. 
Since all `use_...` parameters are true and strings were set in the example, the error did not occur. But with default values an error will be thrown.

**Comment by mlauster** [comment]
Closed via #342

**Comment by mlauster** [comment]
@PMehrfeld, is our netCDF reader module read-only? 
See https://github.com/UdK-VPT/BuildingSystems/pull/64#issuecomment-281308134
I think that's a valuable point

**Comment by thorade** [comment]
As far as I know, every user has to mark the directory read-only himself on his own computer.
Or can Dymola .mos scripts change the permissions?

**Comment by PMehrfeld** [comment]
Since we are not checking out the repo https://github.com/tbeu/netCDF-DataReader as a submodule of our AixLib repo, there is no further need to concern about read-only rights. Any User must clone the repo and open the Modelica library of the netCDF-DataReader manually. This is also described in the documentation of the particular model in AixLib.
