### ISSUE TITLE
Replace non-standard annotation by standard annotation attribute `groupImage`

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#328]
There are plenty of `__Dymola_Images.Parameters.source` annotations in the models that can be substituted by the standard-conform (as of MLS 3.2) annotation attribute `groupImage`. See https://github.com/modelica/Modelica/issues/408 for the corresponding issue on the MSL.

**Comment by AnaConstantin** [comment]
Closed via pull request #369
