### ISSUE TITLE
Minor issues in AixLibSocketCommunication.h

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#329]
1. It says `unsigned char **convertDbltoHex(double num)` in AixLibSocketCommunication.h, but return value is of type `unsigned char *`.
1. It says `int SocketReceive(char **buffer, int maxLen, int socketHandle)` in AixLibSocketCommunication.h but according to the MLS it should be `const char **buffer`.

**Comment by tbeu** [comment]
#277 might be the remedy for the second issue.

**Comment by tbeu** [comment]
Edited. I was wrong earlier.

**Comment by AnaConstantin** [comment]
Closed in pull request #349
