### ISSUE TITLE
Naming of thermal mass inconsistent

### ISSUE THREAD

**Issue by MichaelAdolph** [RWTH-EBC/AixLib#33]
Most Rooms in the Building.HighOrder Library of AixLib offer a simple radio button to select the Thermal Mass Class. Unlike the whole GUI, the labels  assigned (S, M, L) are abbreviations for the German "Schwer", "Mittel" and "Leicht". This is a possible source of confusion, as it could be misunderstood as "Small", "Medium" and "Large".

It suggest renaming the abbreviations to:
S --> high
M --> medium
L --> low

**Comment by marcusfuchs** [comment]
This is on the master through #111
