### ISSUE TITLE
Transfer model for hydraulic separator to AixLib

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#334]
- [x] Check Annex60 for similar models

- [ ] If no models identified transfer model using newest components

- [ ] If model identified asses is mdoels should be combined, or just one of the models should be used

**Comment by TobiasBlacha** [comment]
@AnaConstantin for me it looks like the model has already been transferred into the AixLib: AixLib.Fluid.MixingVolumes.HydraulicSeparator
In addition, I could not find a similar model in the Annex60.

**Comment by AnaConstantin** [comment]
@TobiasBlacha you are correct.
