### ISSUE TITLE
Transfer pipe models to AixLib

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#335]
- [x] Compare pipe models to the one from Annex60 and decide is models should be combined or just use the mdoels from Annex60

- [x] Transfer models if needed

**Comment by TobiasBlacha** [comment]
Currently, we have four different pipe models in our internal library that have not been integrated into the AixLib. The main differences to the pipe model of the Modelica standard library are that pipe insulation and heat storage of the pipe and insulation material can be taken into account. @AnaConstantin and @RoozbehSangi because you are in the documentation of all this pipe models, I wanted to ask you if you think that we still need all four models (DynamicPipeEBC1, DynamicPipeEBCAggregated, DPE_ambientLoss, DPEAgg_ambientLoss).

**Comment by AnaConstantin** [comment]
@TobiasBlacha, I think we only need one model that can do it all:
1. can be discretized in length (via option)
2. can have losses to the ambient (both wall, or air, via option) 
I would suggest the make the pipe model  ontop of which the thermal losses are added replaceable between the Pipe model from Annex 60 and the one from MSL.

**Comment by TobiasBlacha** [comment]
During the transfer of the pipe model I noticed some points:
- The variable "diameter" was incorrectly parameterized
- The star connector is not in use when the pipe has an insulation (why?)

**Comment by TobiasBlacha** [comment]
The pipe model was extended by the parameter isEmbedded, which can be used to distinguish whether the pipe is embedded in a solid material or not. If the pipe is embedded in a solid material, there is no radiative and convective heat transfer. 
The applications of the pipe model have also been expanded:
- Pipe without heat losses
- Embedded Pipe (heat losses)
- Embedded Pipe with insulation (heat losses)
- Pipe (heat losses) 
- Pipe with insulation (heat losses)

**Comment by RoozbehSangi** [comment]
The outcome of discussions with Ana and Tobias about the last status of the pipe model: Tobias is currently integrating all our old pipe models into one. He'll tell us whenever he is done, thank you Tobias!

**Comment by mlauster** [comment]
As you are already revising documentation, is this ready to merge, @TobiasBlacha?

**Comment by TobiasBlacha** [comment]
I have adapted the documentation and I have removed old parts of code for the pipe model. @mlauster I think the model is ready for a review.

**Comment by mlauster** [comment]
@TobiasBlacha, it seems not clear what to do with issue. Has it been merged with #458 and can be closed or are you still working on that and are planning for another PR? In this case, should we move that to the next milestone?

**Comment by TobiasBlacha** [comment]
This issue has been merged with #458 and can be closed.
