### ISSUE TITLE
Transfer models for Active Walls to AixLib

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#336]
- [x] Research if similar models are available in Annex 60 

- [x] If models available decide on best course of action: combine models or use just one of the models

- [x] Transfer needed models

**Comment by Mathadon** [comment]
I'm not sure what active walls are, but I'm pretty sure we don't have them in Annex 60.

**Comment by mlauster** [comment]
I think these are models for thermo active building systems (TABS), like https://www.ashrae.org/resources--publications/periodicals/ashrae-journal/features/using-building-mass-to-heat-and-cool-thermo-active-building-systems

**Comment by Mathadon** [comment]
We have a concrete core activation model in IDEAS based on Koschenz:
IDEAS.Fluid.HeatExchangers.RadiantSlab.EmbeddedPipe

**Comment by mlauster** [comment]
If you are already revising documentation, is this ready to merge, @TobiasBlacha?

**Comment by PMehrfeld** [comment]
`IDEAS.Fluid.HeatExchangers.RadiantSlab.EmbeddedPipe` has a different modelling approach. Thus, our ActiveWall model was transferred into AixLib.

Closed via #459 

But work will be continued in #531
