### ISSUE TITLE
Implement new heat transfer model for heat storage

### ISSUE THREAD

**Issue by ChristianGrozescu** [RWTH-EBC/AixLib#337]
A model should be implemented that considers bouyancy effects properly

**Comment by mlauster** [comment]
Have a look at the models implemented in IDEAS, https://github.com/open-ideas/IDEAS  and Buildings, https://github.com/lbl-srg/modelica-buildings. I think they have something more sophisticated than what we currently have and they plan to merge their systems and bring it into Annex60, which is the basis of AixLib, see https://github.com/iea-annex60/modelica-annex60/issues/314.

**Comment by Mathadon** [comment]
See also work in progress here:
https://github.com/Mathadon/modelica-annex60/tree/issue314_storageTank

**Comment by SebastianStinner** [comment]
@Mathadon : Thank you for sharing the link to your model. If I can see it correctly from the paper and a quick look on the model, the buoyancy effects of heating rods or heat exchangers are not considered as they are not induced by jet flows.

**Comment by Mathadon** [comment]
That's correct. The model does not support internal heat exchangers.

**Comment by PMehrfeld** [comment]
Something new in this branch [issue337_heatTransferStorage](https://github.com/RWTH-EBC/AixLib/tree/issue337_heatTransferStorage) @SebastianStinner and @ChristianGrozescu?

**Comment by SebastianStinner** [comment]
Yes, we are trying to bring all the models into this branch and merge them into issue309_fastHVAC

**Comment by DaJansenGit** [comment]
The new heat tranfser models are now merged into [ issue337_heatTransferStorage](https://github.com/RWTH-EBC/AixLib/tree/issue309_fastHvac) #502

**Comment by PMehrfeld** [comment]
- [ ] Avoid using `final inner` statements like in `AixLib.FastHVAC.Components.Storage.BaseClasses.PartialHeatTransferLayers`.

**Comment by mlauster** [comment]
@DaJansenGit, @pme, is this issue still current? If so, is there a branch and what is the stauts? If not (r.g. replaced by another issue), can we close this?

**Comment by DaJansenGit** [comment]
As this was solved with #614, I will close this issue now.
