### ISSUE TITLE
Description Issue in PartialMultizone.mo

### ISSUE THREAD

**Issue by stroitzsch** [RWTH-EBC/AixLib#338]
Description/Comment of `Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a intGainsRad` is `"Convective internal gains"` but should be `"Radiative internal gains"` at https://github.com/RWTH-EBC/AixLib/blob/master/AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo#L73

**Comment by mlauster** [comment]
Thanks, @stroitzsch for chatching that and @TobiasBlacha for self-assigning that. :) @TobiasBlacha do you really think it's a bug? That would menad solving it in the master and issuing a new release... . From my side it would be fine solving it in the development as it's "only" in the description string.

**Comment by TobiasBlacha** [comment]
@mlauster okay, then i will change the label to "development" and fix this in the development branch.

**Comment by mlauster** [comment]
Closed via #339
