### ISSUE TITLE
Create records for materials of wall layers

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#344]
... and integrate them in the wall records.
Use the concept from IDEAS as startpoint: IDEAS.Buildings.Data.Materials

**Comment by mlauster** [comment]
@AnaConstantin, how to proceed with this? Will we do this or shall we close this for now? @PMehrfeld, any interest from your side to add these functionalities?

**Comment by PMehrfeld** [comment]
Currently there is no need for me, although I like this idea.

**Comment by mlauster** [comment]
I will close this for now then.
