### ISSUE TITLE
Detailed district heating model

### ISSUE THREAD

**Issue by MBaranskiEBC** [RWTH-EBC/AixLib#353]
The issue is to include a district heating/cooling model into AixLib, preferably with renewable feed-in. 
@marcusfuchs is there a model in Annex 60 that we can use for that?

**Comment by mlauster** [comment]
Has this issue been split up in #402 and #403, @marcusfuchs and @MBaranskiEBC ? We could then close this issue.

**Comment by marcusfuchs** [comment]
We'll continue all DHC modeling in #403. So I'll close this. @MBaranskiEBC @FaridDavani : If you would like to participate in this development, please get in touch.
