### ISSUE TITLE
Add controllers and controller interfaces

### ISSUE THREAD

**Issue by MBaranskiEBC** [RWTH-EBC/AixLib#354]
In order to be able to quickly connect new controllers to the component models such as heat pump, we need standardized interfaces. I suggest we create bus connectors for each component and define the variables that we need for typical controllers. In addition, we can add a number of typical controllers to the controls package.

**Comment by marcusfuchs** [comment]
@MBaranskiEBC 
As I understand it, this issue is not completely solved by #355, right? I will therefore leave it open.

**Comment by MBaranskiEBC** [comment]
@marcusfuchs yes thanks! I will continue working on it by adding further controllers and interfaces for other components. As far as the heat pump model (#308) and the pump (#184) are concerned, @AnaConstantin and I will work in the respective branches to modify the models accordingly. So it's a good thing that we have the first interfaces and controllers in the development branch.

**Comment by mlauster** [comment]
@MBaranskiEBC, is still an open point or handled/solved in other issues? In the second case, we could close this issue

**Comment by mlauster** [comment]
@MBaranskiEBC, is this still active?

**Comment by mlauster** [comment]
Isn't this covered in various other issues, e.g. by @alexanderAKU? In this case, we could close it here it think.

**Comment by MBaranskiEBC** [comment]
@mlauster yes it should be well covered in other issues, let's close it here.

**Comment by PMehrfeld** [comment]
@MBaranskiEBC : So the [according branch](https://github.com/RWTH-EBC/AixLib/tree/issue354_controllerInterfaces/AixLib) can be deleted? Then the following (added) files might be lost.

![unbenannt](https://user-images.githubusercontent.com/11769433/44148991-be412be6-a09a-11e8-8159-5ec0cdf2ff98.JPG)

**Comment by LauraMaier** [comment]
@MBaranskiEBC In regard to the upcoming hackday tomorrow: What is the current status of this issue ? :)
