### ISSUE TITLE
We need to better describe our workflow for contributions

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#356]
In the past, many of our colleagues had difficulties understanding our workflow. I think a better definition of our workflow will help us all to get more people on board and enjoy the AixLib development together. Therefore, I suggest to update our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki), especially to better reach out to our colleagues with little or no previous experience with Git, GitHub and the AixLib.

I will draft a few new points at [Proposal for Git Workflow](https://github.com/RWTH-EBC/AixLib/wiki/Proposal-for-Git-Workflow). All contributions and suggestions are welcome!

As part of this effort, we also make the following changes:
- Add templates for issues and pull requests (#358)

**Comment by mlauster** [comment]
We could use templates for issues and pull requests, see

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by PMehrfeld** [comment]
Also a workflow or some kind of check list for code review migth be helpful (including some cross links to other wiki pages like `Variable Naming` or `Documentation`).

**Comment by marcusfuchs** [comment]
For a nice example on how issues could look like with the new workflow see @PRemmen 's issue in the TEASER repo: RWTH-EBC/TEASER#440

**Comment by marcusfuchs** [comment]
In the current structure of our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki), `Contribute to AixLib` is a part of the `Git Workflow` section. 

@alexanderAKU and I think that it would be good to split this up into two section. The `Contribute to AixLib` could be a gateway for describing approaches to e.g. 
- report an error
- suggest an improvement
- add a new model
- etc.

The `Git Workflow` section could then focus on describing how we work with git, i.e.
- Creating good issues
- Structure your work in small commits with good commit messages
- How to review a pull request
- etc

In addition, we then would need to find new homes for [Structure of Repository](https://github.com/RWTH-EBC/AixLib/wiki/Structure-of-AixLib-Repository) and [Behind the Scenes](https://github.com/RWTH-EBC/AixLib/wiki/Behind-the-Scenes)

If there are no objections, we would start drafting this new structure.

**Comment by alexanderAKU** [comment]
I added a new page for working with issues: [Create an Issue](https://github.com/RWTH-EBC/AixLib/wiki/Create-an-Issue)

**Comment by thorade** [comment]
related: https://github.com/blog/1184-contributing-guidelines

**Comment by mlauster** [comment]
@thorade, thanks a lot for that hint! How did you get knowledge about all that things?

**Comment by thorade** [comment]
I read about it here: https://github.com/modelica/Modelica/issues/2161 ;-)

**Comment by mlauster** [comment]
That's a self-citation!

**Comment by thorade** [comment]
github introduced the new community checklist:
https://github.com/RWTH-EBC/AixLib/community
https://github.com/blog/2380-new-community-tools

**Comment by PMehrfeld** [comment]
Is this issue still relevant @mlauster and @marcusfuchs? I just deleted the branch `issue358_templates` since it was fully merged.
So, if there are no further open aspects, one of you can close this issue.

**Comment by mlauster** [comment]
Let's close it for now and reopen it if needed.
