### ISSUE TITLE
Develop a model for the Menerga Air Handling Unit (AHU)

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#360]
## What is the problem?

- There is no model for a specific air handling unit model (Menerga sorpsol). 
- Existing AHU model is hard to modify

## Why do we want to solve it?

- We want to develop a new control strategy for the Menerga Air Handling Unit. Therefor, we need a model including all sensor and actor signals of the air handling unit. The model is needed for evaluating and testing the control strategy.

## How do we want to solve it?

- The model should be composed of components for a high reusability
- Develop missing components (adiabatic evaporation, absorber/desorber)
- Modify existing models (pumps, valves, etc) to build up the air handling unit model

**Comment by alexanderAKU** [comment]
My student Christian (@aku-cbe) and I want to develop a control strategie. Therefor, we need a model that can handle all actor signals as an input and that gives sensor values as an output.

The issues [Physical air handling unit model #357](https://github.com/RWTH-EBC/AixLib/issues/357) and  [Module-based AHU model #310](https://github.com/RWTH-EBC/AixLib/issues/310) will be considered.

**Comment by mlauster** [comment]
@alexanderAKU, what is the status on this? There aren't any commits so far mentioning this this issue.

**Comment by PMehrfeld** [comment]
@alexanderAKU  : I am not sure what the current status is here. But I set the milestone to next version which is due on 30 May 2018. Maybe you can solve this issue (partially) at the institute's hack day ;)
However, if you prefer focussing on your hydraulic admix modules, uncheck the milestone again.

**Comment by MBaranskiEBC** [comment]
@PMehrfeld We will restart the work on this issue. The former assignee obviously forgot to mention the issue. There have been commits to [https://github.com/RWTH-EBC/AixLib/tree/issue360_MenergaControls](url). However, I just took a look at the models and there are a lot of issues (external dependencies etc).

**Comment by mlauster** [comment]
@alexanderAKU, how are the plans on this?

**Comment by alexanderAKU** [comment]
@mlauster The master thesis is finshed. Nevertheless, the model needs to be reworked (naming, parameter propagation, etc.).

**Comment by LauraMaier** [comment]
@alexanderAKU What is the current status of this issue?

**Comment by KremerMartin** [comment]
@alexanderAKU What is the current status of this issue? Is there a chance of finishing it during Hacktober or the Hackday next week?
