### ISSUE TITLE
Example of hydraulic system

### ISSUE THREAD

**Issue by MBaranskiEBC** [RWTH-EBC/AixLib#371]
## What is the problem?
- There is no detailed example of a hydraulic system, only simplified systems such as "SimpleHouse" or "HeatPumpDetailed"

## Why do we want to solve it?
- A more detailed example would show how various components can be connected. It can further serve as a basis for future developments or specific case studies

## How do we want to solve it?
- We can integrate a simple  model containing a heat pump, storages, a boiler and a simple geothermal source that we already have in a private repository. 

## Who do you think will benefit from your solution?
- Anyone working with the components in AixLib can get some inspiration for how to build a hydraulic system.
- Anyone in need of  some kind of system for example to test a room model can use the model as it is

**Comment by PMehrfeld** [comment]
@MBaranskiEBC: Absolutely appreciating that you are going to integrate such a example!
But I know about two more examples in AixLib containing an example for a hydraulic system:

- `AixLib.Building.HighOrder.Examples.Appartment_VoWo`
- `AixLib.Building.HighOrder.Examples.RoomGFOw2_DayNightMode`

**Comment by MBaranskiEBC** [comment]
@PMehrfeld Thanks I just took a look at them. The focus in those examples is more on the demand side, whereas the model we already have in the private repo is a energy conversion system. So it could complement the existing examples.

**Comment by marcusfuchs** [comment]
@MBaranskiEBC 
I think such detailed examples would greatly help to improve the usability of AixLib. I would be great if the model documentation would explain what users should look after in the model and its results.

**Comment by MBaranskiEBC** [comment]
I have added a first version of the hydraulic system example. I will try to finalize it this week and create a pull request.

**Comment by PMehrfeld** [comment]
@MBaranskiEBC : It looks as a lot of good work has already been performed in this issue. What about bringing it to a merge until the milestone due to date :)

**Comment by marcusfuchs** [comment]
This is now on the development branch.
