### ISSUE TITLE
HeatPump simple contains undocumented components

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#373]
## What is the problem?

As described in our [modeling guidelines on Documentation](https://github.com/RWTH-EBC/AixLib/wiki/Documentation#description-string) (specifically [here](https://github.com/RWTH-EBC/AixLib/wiki/Documentation#description-string)), all parameters, variables and components should have a documentation string. These documentation strings are in part missing in `AixLib.Fluid.HeatPumps.HeatPumpSimple`

## Why do we want to solve it?

- Documentation strings make it a lot easier for everyone to quicker and better understand the model
- This is a good first issue (not much effort and expertise are needed to fix this)

## How do we want to solve it?

Every variable and parameter should get a documentation string.
E.g. 
```Modelica
  Modelica.Fluid.Interfaces.FluidPort_a
                    port_a_source(redeclare package Medium = Medium)
                                  annotation(Placement(transformation(extent = {{-100, 60}, {-80, 80}})));
```
should be changed to 
```Modelica
  Modelica.Fluid.Interfaces.FluidPort_a
                    port_a_source(redeclare package Medium = Medium) "Heat pump inlet on the source side"
                                  annotation(Placement(transformation(extent = {{-100, 60}, {-80, 80}})));

```
In this example, `"Heat pump inlet on the source side"` is the added documentation string.

**Comment by aku-cbe** [comment]
I will do this first issue

@alexanderAKU

**Comment by marcusfuchs** [comment]
This is now on the `development` branch.
