### ISSUE TITLE
Add correct documentation template to the User's Guide

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#374]
## What is the problem?

Our documentation template is only up to date in the Wiki, but not in the library (as dicussed in #365)

## Why do we want to solve it?

It is a convenient option for many users to copy the template from the User's Guide within the library rather than from the Wiki

## How do we want to solve it?

We'll add the template from the Wiki to the User's Guide and link to the Wiki from there

**Comment by AnaConstantin** [comment]
Was closed via pull request #375
