### ISSUE TITLE
Addition of undisturbed ground temperature model

### ISSUE THREAD

**Issue by FelixBue** [RWTH-EBC/AixLib#376]
## What is the problem?

- There is no ground temperature model in the AixLib

## Why do we want to solve it?

- For the comparison of low temperature networks to conventional district heating, thermal losses in the distribution pipes should be modeled. A model for the ground temperature trajectory over a whole year is more precise than a constant temperature.

## How do we want to solve it?

- Add the Kusuda-Assenbach model from the library of my master thesis to the AixLib. It is a simple one-equation model that delivers a form of sine-wave depending on depth, type of soil and outside air temperature.

This has been discussed with @marcusfuchs

**Comment by marcusfuchs** [comment]
This is now on the development branch.
