### ISSUE TITLE
Illegal syntax

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#379]
(size(var))[1] needs to replaced by size(var, 1) in all places of [ncDataReader.mo](https://github.com/RWTH-EBC/AixLib/blob/development/AixLib/Utilities/Sources/ncDataReader.mo#L34).

**Comment by PMehrfeld** [comment]
@tbeu: Thanks for this hint.
I assigned myself a bit too quick. I think this might be a [`good first issue`](https://github.com/RWTH-EBC/AixLib/issues?q=good+first+issue+label%3A%22good+first+issue%22). 
See #372 
Important hereby is the [short tutorial on how to solve a first issue for beginners which is in our Wiki](https://github.com/RWTH-EBC/AixLib/wiki/First-contribution).

So, if someone knows a student who should learn the contribution procedure, please assign him or her :)

**Comment by marcusfuchs** [comment]
This is actually needed to be fixed in order for AixLib to work in OpenModelica, too. Therefore, I will quickly fix this for the upcoming v0.5.0 release.

**Comment by PMehrfeld** [comment]
What have been a good first issue ;)
But I totally agree with you, @marcusfuchs, that this must have been done for v0.5.0.
