### ISSUE TITLE
HeatPumpDetailed contains undocumented components

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#390]
## What is the problem?

- Much like in #373, the model `AixLib.Fluid.HeatPumps.HeatPumpDetailed` contains elements without doc-strings. See #373 for a detailed description of the problem

## Why do we want to solve it?

- Documentation strings make it a lot easier for everyone to quicker and better understand the model
- This is a good first issue (not much effort and expertise are needed to fix this)

## How do we want to solve it?

- Again, see #373 and the corresponding pull request #388  for guidance on how to solve this.
- Follow our [tutorial for first-time contributors](https://github.com/RWTH-EBC/AixLib/wiki/First-contribution)

**Comment by PMehrfeld** [comment]
@MirkoEngelpracht and @marcusfuchs: Is this one already solved by #395?

**Comment by MirkoEngelpracht** [comment]
@PMehrfeld: No, this issue isn't solved by #395. For #395, I Just added the missing doc-strings for the example models.

**Comment by PMehrfeld** [comment]
solved by #413
