### ISSUE TITLE
Improve documentation on heat pump examples

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#391]
## What is the problem?

- Just as #373 and #390 , the example models `AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed` and `AixLib.Fluid.HeatPumps.Examples.HeatPumpSimple` contain elements that are missing a doc-string. See #373 for a detailed description of the problem.
- In addition, both models contain a typo in their documentation: `consumptiion` should be `consumption`. 

## Why do we want to solve it?

- Documentation strings make it a lot easier for everyone to quicker and better understand the model
- This is a good first issue (not much effort and expertise are needed to fix this)

## How do we want to solve it?

- Again, see #373 and the corresponding pull request #388  for guidance on how to solve this.
- Follow our [tutorial for first-time contributors](https://github.com/RWTH-EBC/AixLib/wiki/First-contribution)
- Feel free to adress one or both of the models mentioned above in your pull request.

**Comment by MirkoEngelpracht** [comment]
@marcusfuchs: Hello Marcus, I'd like to do this issue as my first issue.

**Comment by marcusfuchs** [comment]
Perfect, I'd suggest you go ahead and follow [the tutorial for first-time contributors](https://github.com/RWTH-EBC/AixLib/wiki/First-contribution). If you need any help or something is not clear, just post here and we'll be happy to help and improve the tutorial.

**Comment by marcusfuchs** [comment]
This is now on the development branch.
