### ISSUE TITLE
Copyright file needs to be updated

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#393]
The copyright file mentions 

> Copyright (c) 2010-2014, RWTH Aachen University, E.ON Energy Research Center, Institute for Energy Efficient Buildings and Indoor Climate. All rights reserved. 

The `2014` part needs to be updated.

**Comment by tst-pth** [comment]
I would like to work on this issue as my good first issue.
Is there any information I need to know about this?

**Comment by mlauster** [comment]
No, nothing more to know about, it really is that simple. ;) Easiest way would be to set `2014` to `2017`, a bit more sophisticated would be to first check if there is an official way to say that it's `until today`. For this, it might help to check licenses of of other, popular software.

**Comment by tst-pth** [comment]
Okay thank you :) I just updated the file in a first version by only renaming the "2014" to "2017". I will try to make the changement automatically by using the getTime() function.
My only problem is that I can not push my "issue393_..." branch because it tells me that the permission is denied. Can you maybe please help me with that?

**Comment by mlauster** [comment]
You have already have a pending invitation to AixLib students group, @tst-pth. You need to accept that in order to have write access on AixLib. You should see some message for the invitation when you are logged in and visit https://github.com/RWTH-EBC or maybe as well https://github.com

**Comment by PMehrfeld** [comment]
@tst-pth: Additionally, I just updated this invitation. So you probably have a new unread message.

**Comment by tst-pth** [comment]
Ahh thank you it's working now :) 
As mentioned in my last comment I will try to improve the annotation so that the year updates automatically.

**Comment by tst-pth** [comment]
I did not find anything in popular libraries concerning the automatic changing of the copyright file. But I created a pull request so that the initial update can be merged ( #430 )

**Comment by PMehrfeld** [comment]
closed via #430
