### ISSUE TITLE
issue394_Multizone_nPorts

### ISSUE THREAD

**Issue by mschumacher247** [RWTH-EBC/AixLib#394]
## What is the problem?

- Compilation of Multizone Example in JModelica throws an error

## Why do we want to solve it?

- Because we can

## How do we want to solve it?

- Remove nPorts from Multizone model

![multizone_error](https://cloud.githubusercontent.com/assets/8257582/26242513/0292e5a4-3c89-11e7-8d35-fe95af12a645.png)

**Comment by mlauster** [comment]
Hm, I don't see a better solution for that soon, so go ahead and create a PR, @mschumacher247!

**Comment by marcusfuchs** [comment]
@mschumacher247 Are you testing this with JModelica 2.0, too?

**Comment by AnaConstantin** [comment]
In order to not forget, I'm assigning to this issue in order to ask by Modelon if they have a different suggestion for a solution, as such problems might appear in other models build under Dymola.

**Comment by mschumacher247** [comment]
Test was done with nightly build r9895 of JModelica SDK. So Version 2.0 should be covered too

**Comment by mlauster** [comment]
closed via #399
