### ISSUE TITLE
Window Models

### ISSUE THREAD

**Issue by mla-srs** [RWTH-EBC/AixLib#397]
I want to integrate window models based on the guideline VDI 6007. It includes shadow calculations, more accurate correction values (CorG) and illumination calculations. Alltogether the direct heat transfer through the window into the room and the heat because of the illumination is calculated.

**Comment by mla-srs** [comment]
Do you want me to integrate the SolarGain directory to the Windows directory or should it remain seperate? @mlauster

**Comment by mlauster** [comment]
Hm, what you think is more clear, @mla-srs . It might make sense to add it to the windows directory

**Comment by mla-srs** [comment]
I would say so too. For the upper class window models the correction values are used. So actually it is a base class for them.

**Comment by mla-srs** [comment]
Closed by #405.
