### ISSUE TITLE
collect topics for next release

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#400]
This is an issue, where we collect possible topics for the release of AixLib v0.7.0

I would suggest to create kind of a pool in this issue chat. In particular this means, each suggestion for one topic should be written in one comment. All contributors can use the thumbs up symbol to vote for this topic.

**Comment by PMehrfeld** [comment]
compatibility with OpenModelica

**Comment by PMehrfeld** [comment]
continuous integration

**Comment by PMehrfeld** [comment]
reduce number of issues

**Comment by PMehrfeld** [comment]
top-level package `Systems`

**Comment by DaJansenGit** [comment]
in v0.7.4 the new heat pump model is integrated into fastHVAC and the old one delted

**Comment by MartinRaetz** [comment]
@DaJansenGit
Is there a status update?
Can this issue be closed? (To reduce number of issues ;) )

**Comment by DaJansenGit** [comment]
I think we should leave this issue open because it is always ongoing

**Comment by DaJansenGit** [comment]
As I think the new GitHub projects feature is a better way to bundle issues for the next planned release I would link to close this issue. Any objections @PMehrfeld ?
