### ISSUE TITLE
Conversion script of current development with v0.5.0

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#404]
## What is the problem?

- With #366 the parameter `D` in model `AixLib.Fluid.FixedResistances.HydraulicResistance` changed to `diameter` (according to the [Wiki conventions](https://github.com/RWTH-EBC/AixLib/wiki/Variable-Naming))

## Why do we want to solve it?

- So that errors will be avoided automatically.

## How do we want to solve it?

1. Change (in development branch) AixLib version from v0.5.0 to 0.5.1
2. Create file `AixLib\Resources\Scripts\ConvertAixLib_from_0.5.0_to_0.5.1.mos` with content `convertModifiers("AixLib.Fluid.FixedResistances.HydraulicResistance", {"D"}, {"diameter=%D%"});`
3. Add conversion script in `package.mo`: `conversion(from(...,version="0.5.0",script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.0_to_0.5.1.mos")`

## A few more questions

1. I used the `bug` label. This is meant as a bugfix for development, not for master. I hope this is correctly used.
2. Is anyone more familiar with conversion scripts? (@AnaConstantin, @mlauster, @marcusfuchs, @pema1?) What if someone directly changes from v0.4.0 to v0.6.0? Will the script then be executed? Or should we use `conversion(from(...version="",script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.0_to_0.5.1.mos")`?
3. The file `AixLib/Resources/Scripts/ConvertAixLib_from_0.1_to_0.2.mos` is two years old and empty. I will delete it with this issue.

Thanks for any input!

**Comment by AnaConstantin** [comment]
Closed with pull request #419
