### ISSUE TITLE
Modular and scalable heat pumps and refrigerating machines

### ISSUE THREAD

**Issue by MirkoEngelpracht** [RWTH-EBC/AixLib#407]
## What is the problem?

Currently, there are no models that allow building modular and scalable heat pump or refrigerating machine models. In this case, modular means different set-ups like two evaporators (and also two expansion valves), a compressor rack or different refrigerants; scalable means different sizes of each component like the heat exchanger area or the swept volume of the compressor. Furthermore, the controllable components (e.g. the compressors and the expansion valve) should have a controller block as an interface that allows either to use an internal component controller or to use an external controller.

## Why do we want to solve it?

We want to solve this issue in order to be able building such models as mentioned before. Those models can be used, for example, to analyse different controlling concepts as well as the effect of different refrigerating media or different heat pump set-ups to the overall efficiency.

## How do we want to solve it?

In order to solve this issue, we will first develop the component models and, afterwards, provide examples of different heat pump and refrigerating machine set-ups. Specifically, we will create and solve the following issues:

1.	_Refrigerant:_ We will add at least two different refrigerants, for example, R134a and probably R410a using the concept presented by Sangi et al. (see paper “A Medium Model for the Refrigerant Propane for Fast and Accurate Dynamic Simulations”).
2.	_Compressors:_ We will add two different types of compressors (e.g. a scroll compressor and a turbo compressor). Both compressors will have variable rotational speed and, therefore, will be controllable.
3.	_Heat Exchangers:_ We will add two different types of heat exchangers (e.g. a plate heat exchanger and properly a finned tube heat exchanger). These heat exchangers shall be able to operate in different modes like concurrent-, counter-current and cross-current. Moreover, the heat exchangers shall be able to describe the evaporation and condensation of the refrigerant media.
4.	_Expansion valve:_ We will add an expansion valve that is controllable since its opening degree will be variable.
5.	_Controller block:_ We will add a controller block that can be used with the compressors or the expansion valve. This controller block will provide different internal controllers (e.g. a simple hysteresis as well as a PID controller). Moreover, it will be possible to provide an external controller.
6.	_Example systems:_ We will add some example models (e.g. heat pumps and refrigerating machines) to show the modular and scalable concept as well as to show the use of the controller block.

In general, we will try to focus the simulation speed while modelling the components because it should be able to use the heat pumps and refrigerating machines within larger systems. Moreover, the models mentioned before will be developed during my master thesis that is supervised by tstoreck and cvering. 

## Who do we think will benefit from our solution?

We think that everyone will benefit from our solution who wants to model controllable heat pumps and refrigerating machines and who wants to model the refrigerant circuit.

**Comment by mlauster** [comment]
It would be really great to have such models! I propose to first have a look at models and issues of https://github.com/ibpsa/modelica-ibpsa, https://github.com/lbl-srg/modelica-buildings, https://github.com/UdK-VPT/BuildingSystems and https://github.com/open-ideas/IDEAS to benefit from existing models and discussions.

**Comment by MirkoEngelpracht** [comment]
@mlauster Thanks for the hint. I'll check out the different libraries right away.

**Comment by PMehrfeld** [comment]
@cvering and @tstorek : I know 30 May is ambitious, but maybe this promising project can be pushed forward ;)

**Comment by mlauster** [comment]
@cvering, are all points from this issue adressed in PRs #451, #498 and #499? Or could you give an update, what for further work is planned that isn't adressed in another issue? This would help estimating when we can close this issue.

**Comment by cvering** [comment]
Hey mlauster! I am on it! We will close these issues within the next days!

**Comment by cvering** [comment]
Thank you all for your kind support! We will close this issue and bring it together in the new vapor compression cycle package: #739
