### ISSUE TITLE
issue409_FastHVAC_Heatexchanger

### ISSUE THREAD

**Issue by mschumacher247** [RWTH-EBC/AixLib#409]
The Heatexchanger models don't check because of a wrong link to BaseClasses.WorkingFluid
![unbenanntes bild](https://cloud.githubusercontent.com/assets/8257582/26825580/f55788dc-4ab5-11e7-8f92-f8726369e82a.png)

**Comment by mlauster** [comment]
@mschumacher247, is this read to be merged?

**Comment by PMehrfeld** [comment]
@mschumacher247 : This could be the topic for your work at next hack day ;)

**Comment by PMehrfeld** [comment]
@mschumacher247 : Feel free to reopen again.
