### ISSUE TITLE
Data center server/serve rack model

### ISSUE THREAD

**Issue by PooyanJahangiri** [RWTH-EBC/AixLib#410]
## What is the problem?
There are no models representing data center components, specifically servers and racks.

## Why do we want to solve it?
With the increase of using data centers as a source of flexibility in todays complex energy systems, having a validated but simple model of server racks and servers in a data center can be useful.

## How do we want to solve it?
We will try to move the already generated data center models from the [EU Project GEYSER](http://www.geyser-project.eu/) to AixLib and update them to be compatible with other models in AixLib.

## Who do we think will benefit from the models?
Everyone needing to model and simulate eithe a stand alone data center or a data center in a smart city concept. The model includes all the thermal behavior of the DC for both air cooled as well as water cooled systems.

**Comment by PMehrfeld** [comment]
@PooyanJahangiri: Is this still an open issue? Are the models from EU Project GEYSER going to be part of AixLib?
Otherwise you can close this issue and delete the branch [issue410_dataCenter](https://github.com/RWTH-EBC/AixLib/tree/issue410_dataCenter).

**Comment by mlauster** [comment]
As @PooyanJahangiri left the institute, I assume this is a dead issue, will be closed. I will leave the branch in case somebody wants to pick up.

**Comment by tstorek** [comment]
Maybe it will be interesting the combine his approach with the approach of the batteryrooms and racks #406 ?
