### ISSUE TITLE
Re-introduce thermal zone example records

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#412]
## What is the problem?

We once had example records for different usages of thermal zones. These were removed, because they were not needed. As #392 shows, these records can help to demo control concepts with more interesting results, though.

## Why do we want to solve it?

Easy fix for more interesting control examples.

## How do we want to solve it?

Restore and update old records which were previously removed.

**Comment by marcusfuchs** [comment]
Seems like it's not so easy after all, as the records seem to have changed a lot. I brought back an old record from [commit 41fb74e19925146fff11cdc7c82f357411fd45e3](https://github.com/RWTH-EBC/AixLib/tree/41fb74e19925146fff11cdc7c82f357411fd45e3/AixLib/DataBase/Buildings/OfficePassiveHouse). @mlauster Could you have a look at this and check how much effort it would be to update the old records? Or did I use a too old version?

**Comment by mlauster** [comment]
If I got it correct, the reintegration is no longer necessary. Fot now, I close that issue
