### ISSUE TITLE
Add a temperature sensor to the prescribed heat exchanger

### ISSUE THREAD

**Issue by larsschellhas** [RWTH-EBC/AixLib#414]
Recently I wanted to use a prescribed heat exchanger for modeling a heat transfer between a fluid and a capacity. For this it would be good to know, what the temperature in the heat exchanger itself is, because I could use it then as prescribed temperature BC (see attached Image)

![image](https://user-images.githubusercontent.com/14281234/27100841-c1b6a1c8-507f-11e7-80a0-070fb0154b51.png)

**Comment by PMehrfeld** [comment]
@larsschellhas: You can also use the model `Modelica.Blocks.Sources.RealExpression` in order to receive a Real value from any submodel. Using these models is not always the most elegant solution. But you should consider, if this is a suitable solution for you.

**Comment by larsschellhas** [comment]
thanks @PMehrfeld , that´s probably the simplest way. I guess, this ticket can therefor be closed,
