### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#416]
At the moment we could integrate the html validator of the buildingspy for the AixLib as a CI Service.  This is hopefully the first step of more CI within the AixLib. I'll therefore do the following steps:
- [x] Activate Travis-CI for the AixLib
- [x] Setup Travis to run the html checks of the documentation
- [ ] Integrate /bin/ directory from the IBPSA library to get the right python files for running real unittests
- [ ] Setup a dymola docker 
- [ ] Set all Environmental variables and docker registries

**Comment by mlauster** [comment]
Isn't that already done now, @MichaMans ?

**Comment by mlauster** [comment]
@MichaMans, I think this is done, right? Can we close this issue?

**Comment by mlauster** [comment]
Current status: We need to clarify licences and then set up a Docker and  use in with TravisCI

**Comment by MichaMans** [comment]
Main work and discussion now in #697
