### ISSUE TITLE
there are no open good first issues

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/AixLib#427]
> there are no open good first issues

## What is the problem?

- there are no open good first issues

## Why do we want to solve it?

- I'd like to start to work with Aixlib

## How do we want to solve it?

- ...

**Comment by thorade** [comment]
#448 is a good first issue

**Comment by PMehrfeld** [comment]
@tstorek: Is this interesting for you?

**Comment by PMehrfeld** [comment]
you had some ;)
