### ISSUE TITLE
MultiZone model corrupt at "withWindows=false"

### ISSUE THREAD

**Issue by mschumacher247** [RWTH-EBC/AixLib#43]
Since the MultiZone model is not part of AixLib yet, this issue is not urgent for now. Should be fixed when integrating MultiZone model into AixLib

**Comment by mlauster** [comment]
This might be due to vectorization of model where the conditioning of single vector entries might not work. I will try that. Anyway, the statement was thought for avoiding problems when window area is zero. Maybe we can find a more elegant way to avoid dividing by zero.

**Comment by mlauster** [comment]
Hm, I tried it by myself but it worked fine. We should crosscheck that.
