### ISSUE TITLE
Error message when loading library in OpenModelica v1.11.0

### ISSUE THREAD

**Issue by fab6** [RWTH-EBC/AixLib#445]
Hi,

I just tried to load the library (latest git) with openmodelica on linux.

Unfortunately I get the following error message:

[1] 09:02:21 Syntax Warning
[/share/Tools/THERMO/MODELICA/Libraries/AixLib_RWTH/AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo: 6:36-6:482]: Lexer treating \ as \\, since \h is not a valid Modelica escape sequence.

[2] 09:02:21 Translation Error
[/share/Tools/THERMO/MODELICA/Libraries/AixLib_RWTH/AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/package.order: 0:0-0:0]: Found duplicate names in package.order file: RadiatorTypes.

[3] 09:02:21 Scripting Error
Failed to load package AixLib () using MODELICAPATH /share/Tools/THERMO/MODELICA/Libraries/AixLib_RWTH:/share/software/Optimization/OpenModelica/v1.11.0/lib/omlibrary:/home/fbraenns/.openmodelica/libraries/.

Do you have a hint, how I can solve this?
Thanks
Fabian

**Comment by AnaConstantin** [comment]
Hi, sorry for the error, apparently there is a rougue "RadiatorTypes" in the mentioned package.order which we didn't catch at the last checks.
We'll fix it. Until then you should be able to load the library is you just go to [/share/Tools/THERMO/MODELICA/Libraries/AixLib_RWTH/AixLib/Fluid/HeatExchangers/Radiators/BaseClasses/package.order] and delete the last line where RadiatorTypes is written for the second time.
Let me know if you still have problems with loading AixLib after this.

**Comment by fab6** [comment]
Thank you for the quick help! Yes, it works now.

**Comment by PMehrfeld** [comment]
Closed by #447
