### ISSUE TITLE
Wrong thickness value in DataBase\Walls\EnEV2002\Floor

### ISSUE THREAD

**Issue by MoritzJaeger** [RWTH-EBC/AixLib#446]
## What is the problem?

- In the data record **FLground_EnEV2002_SML** the thickness of the first wall layer is 0.4 m. This seems like a very large value according to the other data records for floors connected to the ground. My guess is that we are missing a zero so that the value should be 0.04 m.

## Why do we want to solve it?
Wrong results when using EnEv2002 as insulation standard
- If the thickness of one layer has a wrong value, the calculation of the thermal resistance of the wall would be wrong and therefore heat load calculations of buildings using this particular wall type lead to wrong results.

## How do we want to solve it?
- By changing the thickness value in the above mentionend data record, the problem should be fixed very easily. 
- As a first guess the thickness of 0.4 meters should probably be 0.04 meters.

**Comment by mlauster** [comment]
@MoritzJaeger, a bit more information in the comments section, what you would like to do and why, would be helpful.

**Comment by MoritzJaeger** [comment]
@mlauster, I edited the comment section a bit but I don't really know if my guess of 0.04 meters is correct.

**Comment by PMehrfeld** [comment]
@MoritzJaeger I think you might be right. Especially, when we compare this to analogous records like `AixLib.DataBase.Walls.WSchV1995.Floor.FLground_WSchV1995_SML`.
@AnaConstantin What do you think? You implemented these records. Probably this bug has to be fixed.

**Comment by AnaConstantin** [comment]
@MoritzJaeger thank you for finding this out. You are right, it should be 0.04. Please change it and I will be happy to review the pull request.

**Comment by MoritzJaeger** [comment]
@AnaConstantin  I would be happy to do that but when I try to push my changes to the issue branch i get this error message:   Permission to RWTH-EBC/AixLib.git denied.

**Comment by mlauster** [comment]
@MoritzJaeger, I added you to the corresponding group of developers, can you push now?

**Comment by MoritzJaeger** [comment]
@mlauster, yes it worked. Thank you
