### ISSUE TITLE
Warnings in OpenModelica

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#448]
## What is the problem?

- 34 Warnings are raised of type `OpenModelica (64-bit) only supports 63-bit signed integers!` (In HVACAgentBasedControl or DataBase packages)
- 1 Warning is raised of type `Lexer treating \ as \\, since \h is not a valid Modelica escape sequence.`

## Why do we want to solve it?

- To achieve compatibility with OM

Tested with OM v1.11.0 (64-bit). 
If using the development, replace `AixLib\Fluid\HeatExchangers\Radiators\BaseClasses\package.order` with the one from current master.

Here the full message log:

```Modelica
[1] 13:02:05 Syntax Warnung
[D:/04_Git/AixLib_branches/AixLib/AixLib/Controls/HVACAgentBasedControl/Agents/RoomAgent.mo: 72:9-72:21]: OpenModelica (64-bit) only supports 63-bit signed integers! Transforming: 100000000000 into a real
...

[24] 13:02:05 Syntax Warnung
[D:/04_Git/AixLib_branches/AixLib/AixLib/DataBase/Boiler/General/Boiler_Vitogas200F_42kW.mo: 6:18-6:28]: OpenModelica (64-bit) only supports 63-bit signed integers! Transforming: 4009000000 into a real

...

[35] 13:02:05 Syntax Warnung
[D:/04_Git/AixLib_branches/AixLib/AixLib/Utilities/Communication/SocketCommunication/Functions/TCP/package.mo: 6:36-6:489]: Lexer treating \ as \\, since \h is not a valid Modelica escape sequence.
```

**Comment by thorade** [comment]
https://trac.openmodelica.org/OpenModelica/wiki/WritingCompliantLibraries#LargeIntegervalues

Easy to fix: Just append a `.0` to the number, e.g. `123456789.0` instead of `123456789`.

**Comment by PMehrfeld** [comment]
Thanks @thorade. 
So the issue is open for everyone now.

**Comment by arnoldfuetterer** [comment]
The problem still occurs with the Version OM v1.12.0 (64-bit).
There are 45 warnings now.
I will start to work on the issue now.

**Comment by KremerMartin** [comment]
@arnoldfuetterer @LauraMaier  What is the current status on this issue?

Maybe this could be something for the hackday next week. ;)

**Comment by LauraMaier** [comment]
Issue #448 was solved

**Comment by shawnli89** [comment]
> Issue #448 was solved

I tried the version OM v1.15.0 (64-bit) stable, there are still 70 Syntax Warning and most of them are "OpenModelica (64-bit) only supports 63-bit signed integers! Transforming: 4009000000 into a real
"
BTW, the  OM v1.16.0 can't use HVACAgentBasedControl as well.

**Comment by PMehrfeld** [comment]
@LauraMaier and @arnoldfuetterer: Could you please have a look into this issue. I reopened it.

**Comment by arnoldfuetterer** [comment]
@PMehrfeld I'll have a look into it!

**Comment by arnoldfuetterer** [comment]
Found a .mo-file that was in lower case that hindered OpenModelica to open AixLib. After I renamed the file I don't get any Syntax Warnings with neither OM v1.14.0 (64-bit) nor OM v1.16.0 (64-bit).

**Comment by shawnli89** [comment]
> Found a .mo-file that was in lower case that hindered OpenModelica to open AixLib. After I renamed the file I don't get any Syntax Warnings with neither OM v1.14.0 (64-bit) nor OM v1.16.0 (64-bit).

Thanks for your attention.
I can't find ModularAHU file in Github https://github.com/RWTH-EBC/AixLib/tree/master/AixLib/Systems or on my computer C:\Program Files\OpenModelica1.15.0-dev-64bit\lib\omlibrary\AixLib 0.7.3\Systems
What should I do?
![Annotation 2020-03-12 082345](https://user-images.githubusercontent.com/30115130/76475726-d2753980-643a-11ea-9144-7d17bc501e18.jpg)

**Comment by PMehrfeld** [comment]
@shawnli89 : The necessary changes are not in the `master` branch yet.  
Please checkout or download the `development` branch ([LINK](https://github.com/RWTH-EBC/AixLib/tree/development)).  
I will close this issue. Please feel free to reopen it, if you have any further questions.

@arnoldfuetterer : Thanks for the changes!
