### ISSUE TITLE
LOM.SplitterThermPercentAir

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#45]
I have to objections:
- For what is "AirPercent" in the name?
- The loop connecting input and output can be more efficiently handled by a vectorized equation using .* if necessary
- In the sum equation, the multiplication needs to be done via .*. This might cuase errors if input is a scalar.

**Comment by PRemmen** [comment]
1. This is because the model was developed for another purpose. I will change that
2. I will try to implement the vectorized equation

**Comment by PRemmen** [comment]
Only tested with LOM Example. @mlauster
