### ISSUE TITLE
FastHVAC: simulation of HeatPump with JModelica 

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#452]
## What is the problem?

 I am trying to run some models I constructed in Dymola with JModelica. I just recognised that JModelica has a problem with the HeatPump model (AixLib.FastHVAC.Components.HeatGenerators.HeatPump.HeatPump) 
out of the Fast_HVAC (Branch: Issue309_Fast_HVAC).
The following errors apear trying to simulate it with JModelica: 
"Cannot find component declaration for Corr_icing"
"Illegal access to class in expression: corr_icing"

## Why do we want to solve it?

We want to solve the problem in order to include existing components into the models.

## How do we want to solve it?
By including the CycleHP model into the HaetPump model there is made the following "redeclaration"  

  Fluid.HeatPumps.BaseClasses.CycleHP                   cycle(
    Corr_icing=corr_icing);

By adding "redeclare function" to it it still works in Dymola and in my opinion it doesn't change the performance of the model, is that right? 

But this change makes it possible to simulate the model with JModelica.

**Comment by PMehrfeld** [comment]
@larissakuehn : Are you still working on this?
@JSchiefelbein : If my guess is correct, you would be the next person to approach regarding this issue. If so, please assign yourself and update this issue :)

**Comment by JSchiefelbein** [comment]
@larissakuehn finished her thesis a while ago. I would suggest closing this issue for now. As far as I can recap, the HPs were running on JModelica. If necessary, this issue can be re-opened.

**Comment by sohertz** [comment]
Hello, I took the lastest AixLib version on Github today and try to compiled the 'AixLib.FastHVAC.Examples.HeatGenerators.HeatPump.ValidationHeatPump' on JModelica but I have two same compiling errors as described in this ticket. That's how I found it. Could one of you help me so that I can compile the model on JModelica ? @JSchiefelbein maybe?

```
Error at line 236, column 5, in file 'C:\JModelica.org-2.10\install\ThirdParty\MSL\AixLib\Fluid\HeatPumps\HeatPumpDetailed.mo':
  Cannot find component declaration for Corr_icing

Error at line 236, column 16, in file 'C:\JModelica.org-2.10\install\ThirdParty\MSL\AixLib\Fluid\HeatPumps\HeatPumpDetailed.mo':
  Illegal access to class in expression: Corr_icing
```

**Comment by PMehrfeld** [comment]
@sohertz :
