### ISSUE TITLE
FastHVAC: ThermostaticValve 

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#454]
## What is the problem?
The model "ThermostaticValve" (AixLib.FastHVAC.Components.Valves.ThermostaticValve) is using the following linear valve charactteristic: 

HVAC.Components.Valves.BaseClasses.ValveCharacteristics.linear

which is not available. 

## How do we want to solve it?
We can solve this problem by using the linear valve Characteristic from the Modelica Library. 
( Modelica.Fluid.Valves.BaseClasses.ValveCharacteristics.linear)

**Comment by TobiasBlacha** [comment]
The change has already been integrated in the development by #455 , so I will close this issue.
