### ISSUE TITLE
Expansion valves and two-phase tank for modular heat pumps

### ISSUE THREAD

**Issue by MirkoEngelpracht** [RWTH-EBC/AixLib#457]
## What is the problem?

This issue is a work package for issue #407.

Currently, there are no expansion valve models that allow to handle two-phase media (e.g. refrigerants #408). Therefore, we want to add models of expansion valves.

Moreover, there are currently no two-phase tank models that are required within close loop systems of, for example, heat pumps. Therefore, we want to add a model of a two-phase tank.

## Why do we want to solve it?

We want to solve this for issue #407: The expansion valve and two-phase tank can be used, for example, for close loop systems such as heat pumps or chillers.

## How do we want to solve it?

Regarding the expansion valve model:

- In an first attempt, we'll model isenthalpic expansion valves.
- The mass flow characteristic follows from the Bernoulli equation to m_flow = f(C,p_in,p_out).
- Different models of flow coefficients (C) will be implemented as presented in literature.
- Regarding the modularity described in #407, we'll vectorise the model.
- Moreover, we'll implement an internal controller model.

Regarding the two-phase tank model:

- In an first attempt, we'll model a fully-mixed two-phase tank assuming thermodynamic equilibrium at all times.

**Comment by PMehrfeld** [comment]
Like in #407 
@cvering and @tstorek : I know 30 May is ambitious, but maybe this promising project can be pushed forward ;)

**Comment by mlauster** [comment]
Will be closed by #498

**Comment by LauraMaier** [comment]
Due to merged pull request in #498, this issue is closed.
