### ISSUE TITLE
PVSystem is only connectable with old weather model

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#460]
## What is the problem?
In AixLib there is only a PV System (AixLib.Fluid.Solar.Electric.PVSystem) which is compatible to the old weather model, because it is only connectable with a solar radiation connector (AixLib.Utilities.Interfaces.SolarRad_in).

## Why do we want to solve it?
We want to solve this problem in order to use the model in combination with the new weather model.

## How do we want to solve it?
We could either change the model in the AixLib library, add a second (modified) model or add an existing one from another library like "Buildings". 

Change model or add a second model: 
- Replace the Solar radiation connector with a weatherBus (AixLib.BoundaryConditions.WeatherData.Bus)
- Add "AixLib.BoundaryConditions.SolarIrradiation.DiffusePerez" and "AixLib.BoundaryConditions.SolarIrradiation.DirectTiltedSurface" in order to calculate the solar radiation on a tilted surface and use the sum of both as Input for the PVSystem

Does anybody still use the old model or can we replace it? 
If not, could we include a second model in the sub package Electric and maybe name it "PVSystemTMY3" or some other name?

Add existing models: e.g.: 
- Buildings.Electrical.AC.OnePhase.Sources.PVSimple
- Buildings.Electrical.AC.OnePhase.Sources.PVSimpleOriented
(but I think the AixLib model includes more detailed calculations,e.g. for the efficiency)

**Comment by PMehrfeld** [comment]
@larissakuehn: Thanks for the well written issue!
I am aiming to use the model with the old weather bus, since the High Order Models are still using this one.

Thus, from my point of view a modelling approach with base class and then having two models with different weather bus models seems to be a good idea.

Anyway, you should also compare the two models (AixLib and Buildings) to each other. From a quick view the one from Buildings seems to have only a constant efficiency?!

**Comment by larissakuehn** [comment]
@PMehrfeld: 
Yes, that's right the efficiency in Buildings is constant. There is only one equation for solar power in the model. Therefore I now modified the model out of the AixLib. 

I will create a Pull request to the development branch, or which branch would you recommend?

I need the model as well in the branch issue309_fastHvac because I am working with the models out of the FastHvac... But in general it wouldn't be very useful to just add it to the branach issue309_fastHvac, am I right?
So would it be possible to merge it to both the development and the issue309_fastHvac branch?

**Comment by PMehrfeld** [comment]
closed via #463
