### ISSUE TITLE
Modular Hydraulic Systems

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#462]
## What is the problem?

- Many hydraulic systems consist of specific hydraulic modules e.g. injection circuit or admix circuit. The AixLib doesn't contain complete hydraulic modules, thus standard hydraulic systems have to be modeled for every new model. 
Identifying and modeling hydraulic modules is a part of the project ZUGABE.
This issue aims to transfer the developed modules to the AixLib.

## Why do we want to solve it?

- We want model hydraulic systems faster and in a standardised way.

## How do we want to solve it?

- The modules are already developed and just need to be transfered

**Comment by alexanderAKU** [comment]
The following hydraulic modules will be transfered:

- [ ] admix circuit
- [ ] injection circuit
- [ ] Throttle circuit with pump
- [ ] Throttle circuit
- [ ] unmixed circuit

@pema1 I going to use the SpeedControlled_Nrpm pump (in AixLib.Fluid.Movers)

**Comment by MBaranskiEBC** [comment]
@alexanderAKU I appreciate a lot that you aim to include the modules. I further believe that the modules will also solve #357. So, I would like to assist here by building the example I had created in #357 using the modules. The example is a model of an air handler we have in our research lab.

**Comment by PMehrfeld** [comment]
@alexanderAKU : I have set the milestone v0.6.0. Let's see how far you get with this issue until that due to date. Afterwards feel free to change the milestone to next version.
