### ISSUE TITLE
Change ambient temperature in model to determine the heat load of the HOM building

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#466]
## What is the problem?

- Heat load of HOM is set to 271.15 K instead of 261.15 K.

## Why do we want to solve it?

- Aachen's reference temperature is -12 degC

## How do we want to solve it?

- change `constAmb(k=271.15)` to `constAmb(k=271.15)` in `AixLib.Building.HighOrder.Examples.OFDHeatLoad.mo`

**Comment by MSteinbach** [comment]
I've changed the ambient heat temperature to Aachen's reference temperature of 261.15 K

**Comment by PMehrfeld** [comment]
Merged via #497
