### ISSUE TITLE
Compressors for modular heat pumps

### ISSUE THREAD

**Issue by MirkoEngelpracht** [RWTH-EBC/AixLib#467]
## What is the problem?

This issue is a work package for issue #407.

Currently, there are no compressor models that allow to handle two-phase media (e.g. refrigerants #408). Therefore, we want to add models of compressors.

## Why do we want to solve it?

We want to solve this for issue #407: The compressor can be used, for example, for close loop systems such as heat pumps or chillers.

## How do we want to solve it?

In a first attempt, we want to model the compressors based on the grey-box approach. Therefore, we'll introduce three different efficiencies (i.e. overall mechanical efficiency, overall volumetric efficiency and overall isentropic efficiency). These efficiencies will be introduced either as polynomials derived for a specific refrigerant (i.e. obtained by measurements or given in literature) or as polynomials based on the similitude theory (i.e. these approach is suitable for unknown refrigerant behaviour).
Moreover, we'll introduce both a modular model that allows to easily compute compressors in parallel (i.e. compressor racks) and a controller interface. The latter allows either to provide external set signals to the compressors or a simple internal control if an external signal is not provided.

**Comment by PMehrfeld** [comment]
Like #407 
@cvering and @tstorek : I know 30 May is ambitious, but maybe this promising project can be pushed forward ;)

**Comment by mlauster** [comment]
Will be closed by #499

**Comment by cvering** [comment]
Thank you all for your kind support! We have, in addition, further compressor models in #609 that we bring together with these ones.
We will close this issue and bring it together in the new vapor compression cycle package: #739
