### ISSUE TITLE
Data bus connectors for modular heat pumps

### ISSUE THREAD

**Issue by MirkoEngelpracht** [RWTH-EBC/AixLib#479]
## What is the problem?

This issue is a work package for issue #407.

Currently, there are no expandable connectors (data bus connectors) for the modular heat pump model that is developed in #407. Therefore, we want to add such data bus connectors.

## Why do we want to solve it?

Data bus connectors have the advantage that a huge amount of control signals can be easily passed between two or even more models.

## How do we want to solve it?

We will define four types of data bus connectors:

1. ModularExpansionValveBus: This connector contains interfaces that may be needed for modular expansion valves; this is required to solve #457.
2. ModularCompressorValveBus: This connector contains interfaces that may be needed for modular compressors; this is required to solve #467.
3. ModularSensorBus: This connector contains interfaces that may be needed for modular sensors
4. ModularHeatPumpBus: This connector contains the three connectors mentioned above and some further parameters that are more general.

**Comment by PMehrfeld** [comment]
Thanks for opening the issue.

Discussing this with @fstinner and probably @MBaranskiEBC is necessary, since some work in this direction is already going on.

E.g. issue #354 is already talking about implementing a bus.

**Comment by MirkoEngelpracht** [comment]
@PMehrfeld, thanks for your hint.

I've already discussed that with @tstorek , @alexanderAKU  and @cvering, however,  I'll talk to them.

**Comment by cvering** [comment]
@PMehrfeld 
Thanks for the hint! I think the work done before is a one dimensional problem. The BUS connector introduced by @MirkoEngelpracht is a high dimensional one.
This is a modelling approach that @alexanderAKU uses for his modular pipe models as well. I think there is no need for discussion with @fstinner and/or @MBaranskiEBC.

**Comment by tstorek** [comment]
@PMehrfeld 
Thank you for your comments as @cvering already mentioned. The data bus for the modular heat pump model is easily interchnagable, however, it will cover the most information needed for heat pumps. Thus, rather a modelling approach than actually a convention. The work done by @fstinner  is a convention for naming datapoints, which can be easily integrated on a further issue. Thank you @MirkoEngelpracht for the issue please proceed.

**Comment by PMehrfeld** [comment]
Alright, then I am fine with it.

So, maybe we have to adapt the variable names a bit afterwards?

**Comment by tstorek** [comment]
@PMehrfeld yes indeed. That could happen. However, that will be only a minor issue (Good First?)

**Comment by PMehrfeld** [comment]
Only as long as it does not come to conversion scripts ;-)

**Comment by PMehrfeld** [comment]
Does #483 really solve all problems in this issue, @tstorek? 
Because you said so in your [last comment](https://github.com/RWTH-EBC/AixLib/pull/483#issuecomment-339741566).

**Comment by PMehrfeld** [comment]
Like in #407 
@cvering and @tstorek : I know 30 May is ambitious, but maybe this promising project can be pushed forward ;)

**Comment by mlauster** [comment]
@cvering, is this covered by one of the open PRs?

**Comment by cvering** [comment]
Thank you all for your kind support! We will close this issue and bring it together in the new vapor compression cycle package: #739
