### ISSUE TITLE
Parameters in HeatConvPipeInside must be set

### ISSUE THREAD

**Issue by SebastianStinner** [RWTH-EBC/AixLib#495]
## What is the problem?

- Parameters in this model are fixed and not taken from the upper level.

## Why do we want to solve it?

- Because changes in upper level parameters do not influence the parameters in this component.

## How do we want to solve it?

- Take the parameters of the upper level.

**Comment by DaJansenGit** [comment]
problem should be solved with this commit: [fixed problem with parameters in heatcoil ](https://github.com/RWTH-EBC/AixLib/commit/248e3d3c52f3b74213ab7e853a00911a4a6f0b67)
@SebastianStinner
