### ISSUE TITLE
Use dymola-python interface in Ubuntu system

### ISSUE THREAD

**Issue by JayHuLBL** [RWTH-EBC/AixLib#503]
This is a general question about using Dymola Python Interface. Since you have a Wiki page introducing how to use the interface in Windows system, I wonder if you have used the interface in Linux system like Ubuntu.

In order to run the interface, I did following modification:
1. Add following section into `.bashrc` file 
```
###### For Dymola-python interface to run ###############
DYMOLA_EXE=/opt/dymola-2018FD01-x86_64
export PYTHONPATH=$PYTHONPATH:$DYMOLA_EXE/Modelica/Library/python_interface/dymola.egg
export LD_LIBRARY_PATH=$DYMOLA_EXE/bin/lib:$DYMOLA_EXE/bin/lib64
```
2. Updated the `DymolaExample.py` file (find it in folder `/opt/dymola-2018FD01-x86_64/Modelica/Library/python_interface/examples`):
change `dymola = DymolaInterface()` to `dymola = DymolaInterface("/opt/dymola-2018FD01-x86_64/bin64/dymola")`

I am using Python 2.7, Dymola 2018FD01-x86_64. 

Thanks!

**Comment by marcusfuchs** [comment]
@JayHuLBL 
Thanks for sharing your approach. Unfortunately, we have so far only used the interface on Windows systems. Therefore, I am afraid we can't test your modifications. Is your modification working on your setup? If so, we could add it to the Wiki post.

**Comment by JayHuLBL** [comment]
@marcusfuchs It's unlucky that the modification is still not working. It gives following error message:
```
Simulation failed. Below is the translation log.
Translation of <a href="Modelica://Modelica.Mechanics.Rotational.Examples.CoupledClutches">Modelica.Mechanics.Rotational.Examples.CoupledClutches</a>:
Did not find model Modelica.Mechanics.Rotational.Examples.CoupledClutches
Error: ERRORS have been issued.
 = false

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/home/jianjun/Desktop/test/DymolaExample.py in <module>()
     31 finally:
     32     if dymola is not None:
---> 33         dymola.close()
     34         dymola = None

/opt/dymola-2018FD01-x86_64/Modelica/Library/python_interface/dymola.egg/dymola/dymola_interface.py in close(self)
    108         ``None`` afterwards.
    109         """
--> 110         return super(DymolaInterface, self).close()
    111 
    112     def getLastErrorLog(self):

/opt/dymola-2018FD01-x86_64/Modelica/Library/python_interface/dymola.egg/dymola/dymola_interface_internal.py in close(self)
    248             exit_code = self._dymola_process.wait()
    249         if self._dymola_process is not None:
--> 250             self._dymola_process.terminate()
    251             self._dymola_process = None
    252         self._print_debug_message("Dymola has exited. Return value " + str(exit_code) + ".")

/usr/lib/python2.7/subprocess.pyc in terminate(self)
   1565             """Terminate the process with SIGTERM
   1566             """
-> 1567             self.send_signal(signal.SIGTERM)
   1568 
   1569         def kill(self):

/usr/lib/python2.7/subprocess.pyc in send_signal(self, sig)
   1560             """Send a signal to the process
   1561             """
-> 1562             os.kill(self.pid, sig)
   1563 
   1564         def terminate(self):

OSError: [Errno 3] No such process
```

Although in the Dymola user manual says that we just need to modify the path environments and nothing else needs to be changed, I am sure that Dassault did do the implementation in Ubuntu system but with other minor changes without explicitly introduced in the annual. I may follow up with them and share my learnings later with you.

**Comment by marcusfuchs** [comment]
Thanks for the update and sorry that we cannot help here. If you find a solution, we would of course be happy to include it in our Wiki.

**Comment by TobiasBlacha** [comment]
Sorry, this is a typing error. The commit  for correction of the documentation of HeatPumpDataBaseDefinition refers to the branch #508

**Comment by BurningTrapezoid** [comment]
I stumbled across this issue while trying to get the dymola-python interface running on Manjaro Linux and this:

> In order to run the interface, I did following modification:
> 
> 1. Add following section into `.bashrc` file
> 
> 
> ```
> ###### For Dymola-python interface to run ###############
> DYMOLA_EXE=/opt/dymola-2018FD01-x86_64
> export PYTHONPATH=$PYTHONPATH:$DYMOLA_EXE/Modelica/Library/python_interface/dymola.egg
> export LD_LIBRARY_PATH=$DYMOLA_EXE/bin/lib:$DYMOLA_EXE/bin/lib64
> ```
> 
> 2. Update the `DymolaExample.py` file (find it in folder `/opt/dymola-2018FD01-x86_64/Modelica/Library/python_interface/examples`):
>        change `dymola = DymolaInterface()` to `dymola = DymolaInterface("/opt/dymola-2018FD01-x86_64/bin64/dymola")`

did actually help in my case. 
Don't know if this is still relevant for this repo, just wanted to share this in case someone else stumbles across this like I did. :)
