### ISSUE TITLE
Number of Events ventCont

### ISSUE THREAD

**Issue by GemsHSLU** [RWTH-EBC/AixLib#504]
Generation of Event for Tamb_mean <= 2723.15K even with useConstantOutput = true

Code AixLib.Controls.VentilationController.VentilationController:
 if useConstantOutput then
    userACH = 0;
    dToh = 0;
    overheatingACH = 0;
    dTamb = 0;
    dTmin = 0;
    redFac = 0;
    summerACH = 0;
  else

...

    summerACH = if dTamb > 0 then min(dTamb*maxSummerACH[1], maxSummerACH[1])
       else 0;
  end if;

Eingabe:
    useConstantACHrate = true,

Solver Output Dymola, Events during simulation:
      during event at Time :  837304.4292473897
Expression Wohngebaeude.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became false ( (Wohngebaeude.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = 5.68434e-014 )
Expression Verwaltung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became false ( (Verwaltung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = 5.68434e-014 )
Expression Mischnutzung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became false ( (Mischnutzung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = 5.68434e-014 )
Iterating to find consistent restart conditions.
      during event at Time :  838586.9830007545
Expression Wohngebaeude.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became true ( (Wohngebaeude.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = -2.73151e-008 )
Expression Verwaltung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became true ( (Verwaltung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = -2.73151e-008 )
Expression Mischnutzung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean <= 273.15 became true ( (Mischnutzung.building.multizoneEquipped.zone[1].ventCont.Tamb_mean)-(273.15) = -2.73151e-008 )
Iterating to find consistent restart conditions.
      during event at Time :  853036.9352990683

## Why do we want to solve it?

- Reduce simulation time

I allready reduced the simulation time by setting strict = true in the Advanced Tab of AixLib.Building.Components.Sources.InternalGains.Humans.HumanSensibleHeat_VDI2078.

The same measure didn't work for the AixLib.Controls.Continuous.PITemp.

Btw. I used the WeatherData.ReaderTMY3 separated for every building. Do you think this could be the reason for the higher simulation time? Would it be better to only use one central WeatherData.RederTMY3 for all buildings?

Kind regards
Stefan Gemperle

**Comment by thorade** [comment]
The Dymola User Manual Volume 1 describes on pages 622-623 (and: 502, 749) how to analyze events and numerics. Maybe this could give additional insight?

The two screenshots below should also show how to find the event log.

**Step 1:** Turn on the logging:

![debug_event_integrator](https://user-images.githubusercontent.com/314571/33610651-5ae0d596-d9cc-11e7-9ae8-1c9d08a882f2.png)


**Step 2:** In the variable browser, right-click on the top level node:

![analyze_numerics](https://user-images.githubusercontent.com/314571/33610551-1c92da28-d9cc-11e7-89ae-50620b26fcf1.png)

**Comment by GemsHSLU** [comment]
I already did this. The problem is, that the VentilationController stil generates an event every time Tamb_mean <= 2723.15K, even  with useConstantOutput = true. From your code, I think it should now longer generate an event in this situation.

**Comment by PMehrfeld** [comment]
@GemsHSLU : Any update here?
After next milestone's due to date, which ist 30 May 2018, I will close this issue. Of course it can be reopened at any time :)
