### ISSUE TITLE
Incorrect documentation of the HeatPumpBaseDataDefinition

### ISSUE THREAD

**Issue by TobiasBlacha** [RWTH-EBC/AixLib#508]
## What is the problem?
The description of the HeatPumpBaseDataDefinition records in the documentation is not correct. The power values depending on the condenser outlet temperature and the evaporator inlet temperature, not on evaporator inlet and outlet temperature.

## How do we want to solve it?
Correction of documentation.

**Comment by PMehrfeld** [comment]
Closed via #509
