### ISSUE TITLE
Accessing Output of airload

### ISSUE THREAD

**Issue by atharkamal** [RWTH-EBC/AixLib#51]
Dear AixLib,
                   I am really confused about this. I want to use the simulated airload Temperature ( reducedOrderModel.airload.T ) of "AixLib.Building.LowOrder.Examples.LOEM" and use it to get an estimate of Cooling required using the equation ( Q=m.c.dT) where dT=AT-ST
AT=Airload Temperatue
ST=Set Temperature. 

How do i access AT, the simulated airload temperatue?

**Comment by PRemmen** [comment]
The path of the airload temperature is "LowOrder.Example.thermalZone.thermalZonePhysics.reducedOrderModel.airload.T".  
Please note that you will already find the cooling demand and cooling load in  "idealHeaterCooler.coolMeter.q_kwh" and "idealHeaterCooler.coolMeter.p"  (with given setTemperatures from CombiTimeTable "heatingCooling")
I hope this is the requested answer.
