### ISSUE TITLE
HeatPumpDetailed --> mistake in calculating Qdot_con(Out)

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#510]
## What is the problem?

- The model `AixLib.Fluid.HeatPumps.BaseClasses.CycleHP` transfers a heat flow into the condenser, while this heat flow is limited according to a maximal temperature. This is achieved by multipliying `Qdot_con` with a pre-factor 0..1. The resulting `CoP_out` is calculated with `Qdot_con` but only the corrected `Qdot_conOut` is transferred to the condenser.

## Why do we want to solve it?

- Electricity consumption does not fit to the gained heat flow.

## How do we want to solve it?

- Since the maximum temperature is a limitation of the actual refrigerant cycle, this parameter should remain in the `CycleHP` model. Instead of reducing `Qdot_con` the speed or on-off-signal should be controlled as this consequently adapts the resulting Q_th and P_el.
- If the heat pump is speed controlled: Regulate speed as low as possible to not exceed maximum temperature. If lower speed limit is reached, heat pump is switched off. An on-off-controlled heat pump directly has to be switched off.
- Introduce parameters for time span that has to be between to compressor starts (typically appr. 20 min) and between a stop and a next start (typically appr. 10 min).

**Comment by PMehrfeld** [comment]
This is the problematic part:

![grafik](https://user-images.githubusercontent.com/11769433/33317608-f281e146-d437-11e7-9ff7-1b4fccdbd911.png)

**Comment by PMehrfeld** [comment]
Started working on branch [issue510_HPDetailedQCon](https://github.com/RWTH-EBC/AixLib/tree/issue510_HPDetailedQCon). In a first step I deleted some unnecessary variables to clean up the model.

**Comment by PMehrfeld** [comment]
- [ ] convert N to relative compressor speed (with conversion script!)
- [ ] distinguish clearer between polynom and table (probably with an extra replaceable model / block)

**Comment by PMehrfeld** [comment]
Should be solved with #577.

**Comment by PMehrfeld** [comment]
After some testing phase of the new heat pump model, I will probably remove the heat pump detailed model and maybe the simple model.
Until this point, I leave this issue open.

**Comment by LauraMaier** [comment]
@PMehrfeld Will you remove the heat pump detailed model from AixLib? :)

**Comment by PMehrfeld** [comment]
@LauraMaier : Since the IBPSA Lib created an `Obsolete` package in mid of may, I propose to use this new structure. As a conclusion, I am going to move this model and the `HeatPumpSimple` into the `Obsolete` package.

**Comment by cvering** [comment]
Yes, go for that!

**Comment by PMehrfeld** [comment]
I delete the branch, since we only move the model to `Obsolete`. See #746
