### ISSUE TITLE
Travis CI blocks merge because of html errors

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#511]
## What is the problem?
- the Travis CI routine doesn't accept some html code that is automatic created by dymola.
- on the other side correct html code isn't accepted by dymola
 
## Why do we want to solve it?
- no merge is possible without reviewing the html code of every model by hand
## How do we want to solve it?
- creating a script that automatic discovers wrong html code in models and converts it to html and "dymola conform" html code

#issue511_HTML

**Comment by DaJansenGit** [comment]
The script is now finished, feel free to use it! Download Link below.
If you encouter any errors, pleace contact me!


[html_tidy.zip](https://github.com/RWTH-EBC/AixLib/files/1612441/html_tidy.zip)

**Comment by marcusfuchs** [comment]
@DaJansenGit This looks really useful - maybe even for people beyond AixLib development. The only thing that bothers me a bit is to provide it via a zip file. Wouldn't this justify having its own repo here on GitHub and possibly also putting it on [PyPI](https://pypi.python.org/pypi)?

**Comment by DaJansenGit** [comment]
@marcusfuchs 
Ok i made a repo on github, you can find it [here](https://github.com/DaJansenGit/HTML-Tidy-Modelica)

**Comment by mschumacher247** [comment]
@DaJansenGit Thanks for the great effort David. I think we should transfer this project to the RWTH-EBC organization. This way it might be easier to find for our Modelica users.

**Comment by DaJansenGit** [comment]
Ok the Repository is now transferred to RWTH-EBC. You can find it [here ](https://github.com/RWTH-EBC/HTML-Tidy-Modelica)

**Comment by PMehrfeld** [comment]
Thanks again for this valuable contribution.

However, we need to give this script more visibility. I have to suggestions:

1. Create a wiki page with a link to the repository
2. Copy the script into [AixLib/Resources/Scripts](https://github.com/RWTH-EBC/AixLib/tree/master/AixLib/Resources/Scripts) and delete the HTML-Tidy-Repository. Additionally, a wiki page with the readme can be created and/or a readme file can also be placed in the folder [AixLib/Resources/Scripts](https://github.com/RWTH-EBC/AixLib/tree/master/AixLib/Resources/Scripts).

I vote for 2.

**Comment by DaJansenGit** [comment]
As discussed with @PMehrfeld, I want to create a new version of this script that integrates the input of @pema1 and also some other features. Me and @MichaMans also talked about integrating this directly into the CI. If there is progress, I will enter the information here.

**Comment by Dawac** [comment]
Hi @DaJansenGit, how is this issue progressing? Shall we make an effort at the upcoming Hackday or should we set a goal in the future?

**Comment by DaJansenGit** [comment]
This will be done by @SvenHinrichs, maybe he will participate at our Hackday on thursday ;)

**Comment by DaJansenGit** [comment]
all the points mentioned here were solved in #802
