### ISSUE TITLE
Merge latest IBPSA into AixLib (new release)

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#513]
The [Modelica IBPSA Library](https://github.com/ibpsa/modelica-ibpsa) has reached a new milestone: We have finally [merged the plug flow pipe model](https://github.com/ibpsa/modelica-ibpsa/pull/824) into the master branch! 

As we would have many use cases for this pipe model in AixLib, I would like to propose a new release which includes the latest state of the IBPSA Library. 

I'll prepare a branch with a new [IBPSA merge](https://github.com/RWTH-EBC/AixLib/wiki/AixLib-and-Modelica-IBPSA-Library-(former-Annex-60)#how-to-merge-the-current-modelica-ibpsa-library-into-aixlib). Open Questions:

1. Are there any open [Pull Requests](https://github.com/RWTH-EBC/AixLib/pulls) that you want to include in this release?
1. Should we tag this new release `v0.5.3` or `v0.6.0`?

Any other comments or requests?

**Comment by PMehrfeld** [comment]
Speaking for myself, I do not have any urgent PR for the next release.

Maybe we should collect here the topics that would represent the release notes. Then we decide depending on the length of the list wether it is worth to name the release `v0.6.0` or just set the version number to `v0.5.3`.

I start with an obvious one:

- Merge of current Modelica IPBSA Libraray

**Comment by marcusfuchs** [comment]
Last call: If you want other open PRs included in this release, please give us a note until tomorrow. Afterwards, I'll prepare the release.

**Comment by marcusfuchs** [comment]
There was a [bugfix for the pipe model](https://github.com/ibpsa/modelica-ibpsa/pull/870) in the Modelica IBPSA Library. I'll update the branch to the latest version if the MIL and create a pull request.

**Comment by PMehrfeld** [comment]
Closed by #515
