### ISSUE TITLE
Change parameter in record over FMU

### ISSUE THREAD

**Issue by GemsHSLU** [RWTH-EBC/AixLib#514]
An automatically simulation of the model MultizoneEquipped is needed for a sensitivity analysis. The standard solution is to do this over an FMU and change there the variables. But this dos not work, because they are written in a record. Do you have any experience how to solve this problem? Or do I need to change the model and erase the variables I want to change from the record?

This problem should be solved so that future automatically simulations do not have the same issue.

**Comment by mlauster** [comment]
@GemsHSLU, are you sure this is because the are written in a record or because the model is structurally dependent on these parameters? Which parameters would you like to change?
I think this issue is hard to solve. Could you change your workflow and generate a new FMU once you changed parameters?

**Comment by GemsHSLU** [comment]
@mlauster no, I'm not 100% sure. This is my first attempt in automatic simulation over an FMU. I tried it with a simple model and it worked. And I tried it with different parameters from the record (some defined as fixed, constant or variable in the FMU) and none of them worked. 
I want to change : gWin, lightingPower, RExt and RExtRem, RFloor and RFloorRem, RRoof and RRoofRem and RWin.
I'm working with the PyFMI library, with this it is not possible to change the workflow. It would probably be necessary to go a whole different way. My problem is, that this is the final task of my master thesis an I'm running out of time.
Could it be a possibility to change the model in a way, that those parameters are no longer part of the redord?

**Comment by mlauster** [comment]
Hm, not all of them a structural parameters, so it should work. To get rid of the record, I would propose to duplicate the MultizoneEquipped model and then replace all assignments by explicit definitions of parameters. As these are defined on a lower level (thermal zone), this is a bit of work and you need to be careful to link them all correctly to the upper level, where you then might have vector structures. But I can't oversee the entire dimension of this reworking, so I can't predict what problems might be on your way.

**Comment by GemsHSLU** [comment]
Ok. Thank you very much. I'm looking right now for solution within the record. But for the case that I would find nothing, this would have been my next step to solve the problem.
And you would say this should work with all of the above-mentioned variables?

**Comment by mlauster** [comment]
That's hard to predict, but generally areas and volumes are structural parameter. That means, the size of the system of equation changes in dependence of their value (parts of the model are removed if they are zero). FMUs are compiled versions of the model and the system of equation is fixed while compilation. Thus, you can only change non-structural parameters for an FMU.

**Comment by GemsHSLU** [comment]
That's what I thought, so it should hopefully be no bigger problem.
Thank you for the answers. If you are interested in the outcome, I will happily inform you.

**Comment by marcusfuchs** [comment]
@GemsHSLU Would be great if you could share some information on the outcomes! Thanks!

**Comment by PMehrfeld** [comment]
@GemsHSLU : I assume this issue can be closed. 

If anyone disagrees, please reopen the thread.
