### ISSUE TITLE
Moving boundary heat exchanger for modular heat pumps

### ISSUE THREAD

**Issue by MirkoEngelpracht** [RWTH-EBC/AixLib#516]
## What is the problem?

This issue is a work package for issue #407.
For modelling the modular heat pump that is developed in #407, we need dynamic heat exchanger models. Therefore, we want to add a moving boundary heat exchanger that also supports switching between different flow states.

## Why do we want to solve it?

Moving boundary heat exchangers are both accurate and fast. Thus, this modelling approach seems to be a good tradeoff between the finite element method and lumped parameter method.

## How do we want to solve it?

We did a literature review and checked out various publications describing moving boundary heat exchangers. In particular, our modelling approach is based on:

1. J. M. Jensen and H. Tummescheit. Moving Boundary Models for Dynamic Simulations of
Two-Phase Flows. In Proceedings of the 2nd InternationalModelica Conference, pages 235–244, 2002. URL: https://www.researchgate.net/publication/2521077.
2. H. Tummescheit. Design and Implementation of Object-Oriented Model Libraries using Modelica. Dissertation, Lund Institute of Technology, Lund, Sweden, 2002. URL: http://portal.research.lu.se/ws/files/4779081/8571901.pdf.
3. J. Bonilla, L. J. Yebra, S. Dormido and F. E. Cellier. Object-OrientedModeling of Switching
Moving BoundaryModels for Two-phase Flow Evaporators. IFAC Proceedings Volumes, 45(2):
1069–1074, 2012. DOI: 10.3182/20120215-3-AT-3016.00189.
4. J. Bonilla, L. J. Yebra, S. Dormido and F. E. Cellier. Object-oriented library of switching moving
boundarymodels for two-phase flowevaporators and condensers. In Proceedings of the 9th International
MODELICA Conference, volume 76, pages 71–80, 2012. DOI: 10.3384/ecp1207671.
5. J. Bonilla, S. Dormido and F. E. Cellier. Switching moving boundary models for two-phase
flow evaporators and condensers. Communications in Nonlinear Science and Numerical
Simulation, 20(3):743–768, 2015. DOI: 10.1016/j.cnsns.2014.06.035.
6. Wei-Jiang Zhang and Chun-Lu Zhang. A generalizedmoving-boundarymodel for transient
simulation of dry-expansion evaporators under larger disturbances. International Journal of
Refrigeration, 29(7):1119–1127, 2006. DOI: 10.1016/j.ijrefrig.2006.03.002.

**Comment by PMehrfeld** [comment]
Like in #407
@cvering and @tstorek : I know 30 May is ambitious, but maybe this promising project can be pushed forward ;)

**Comment by cvering** [comment]
Thank you all for your kind support! We will close this issue and bring it together in the new vapor compression cycle package: #739
