### ISSUE TITLE
Minor refactoring of Database.Profiles

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#518]
## What is the problem?

Very minor problem, but maybe a good first issue - the `Database.Profiles` package could use some refactoring:

1. The file names currently include underscores (e.g. `Profiles_BaseDataDefinition`). It would be more in line with our [Naming guidelines](https://github.com/RWTH-EBC/AixLib/wiki/Namespaces#general) to use camel case instead.
1. The docstring of  `Profiles_BaseDataDefinition` reads `"Ventilation profiles"`, but within the package, this is also extended for set temperatures. We may want to change the docstring to something like `"Base record for one-value time-series profiles"`
1. The white-spaces in the `ASHRAE140` package are not consistent (e.g. `25200, 273.15+ 10;`, `25200,273.15+ 20;`, and ` 82800, 273.15+10;`

## Why do we want to solve it?

Just came across this and thought this may make a `good first issue`

**Comment by FWuellhorst** [comment]
I will take over this issue.

**Comment by PMehrfeld** [comment]
Closed via #576
