### ISSUE TITLE
Development of detailed, modular facade models

### ISSUE THREAD

**Issue by SebastianStinner** [RWTH-EBC/AixLib#520]
## What is the problem?

- Actual wall models do not allow for analysis of heat bridges and different setups for facades (e.g. facade-integrated PV modules).

## Why do we want to solve it?

- The Horizon 2020 project Plug 'n' Harvest analyzes modular facades with included PV modules.

## How do we want to solve it?

- Extend the actual wall model with models for heat bridges and facade-integrated PV modules.

**Comment by mlauster** [comment]
@TimRoeder, any updates on this?

**Comment by KremerMartin** [comment]
@TimRoeder Are there any updates on this issue?

**Comment by Dawac** [comment]
@SeRemy: Is there an effort to integrate the Plug 'n' Harvest models into Axlib? Maybe this would be a task for the upcoming Hackday.
