### ISSUE TITLE
Missing component in HVACAgentBasedControl package

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#522]
Errors occurs in `AixLib.Controls.HVACAgentBasedControl.Examples.BuildingHeatingSystems.BuildingHeating` due to wrong class path of component `constantFactor`.

Solve the problem by changing the path to `CostFunctions.Economic.Constant_Economic_Cost`.

![grafik](https://user-images.githubusercontent.com/11769433/34481786-61641ee8-efb4-11e7-9b30-391fb6c136b3.png)

**Comment by RoozbehSangi** [comment]
Thank you Philipp!

**Comment by PMehrfeld** [comment]
Closed via #523
