### ISSUE TITLE
dataPointNamingSchema

### ISSUE THREAD

**Issue by MBaranskiEBC** [RWTH-EBC/AixLib#525]
## What is the problem?

- In practice, there are several data point designation principles. A uniform scheme would improve interoperability. 

## Why do we want to solve it?

- We would like to establish this naming scheme in Modelica as well. 

## How do we want to solve it?

- We will prepare a simple example based on an exisiting example to demonstrate the naming rules and see the possible difficulties in Modelica.

**Comment by mlauster** [comment]
@MBaranskiEBC, there does not seem to be too much progress here. Is this stale for now and we should close it?
