### ISSUE TITLE
 HVACAgentBasedControl Documentation Window

### ISSUE THREAD

**Issue by RoozbehSangi** [RWTH-EBC/AixLib#530]
## What is the problem?

- References in the HVACAgentBasedControl package are not correct (Path: AixLib.Controls.HVACAgentBasedControl).

## Why do we want to solve it?

- To improve the documentation of the model.

## How do we want to solve it?

- By replacing the current references with the correct ones.

**Comment by PMehrfeld** [comment]
Closed by #532
