### ISSUE TITLE
Revision of ActiveWalls

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#531]
## What is the problem?

- `Fluid.HeatExchangers.ActiveWalls` is in development but still need some revision (related issue #336, related PR #459) 

## Why do we want to solve it?

- Naming conventions not correct.
- Check documentation
- Harmonize both main models: `Panel_Dis1D` and `Panelheating_1D_Dis`. Or even delete one as it might be obsolete.

**Comment by PMehrfeld** [comment]
I have delted `Panel_Dis1D` plus related sub-models in BaseClasses. The documentation clarified that the model is actually still under review and that the model comes along with dificulties in switching the modes heating and cooling.

**Comment by TobiasBlacha** [comment]
The structure and the naming of parameters in the records of floorheating will have to be revised.

**Comment by PMehrfeld** [comment]
Thanks @TobiasBlacha for the review and mentioning what to do next.
I will open a new issue for this.
