### ISSUE TITLE
Effect of sky temperature in high order building (Aixlib)

### ISSUE THREAD

**Issue by Amuntaseer** [RWTH-EBC/AixLib#540]
> Just stopping by to let us know about some issue you encountered with AixLib? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new models to AixLib, please make sure to briefly answer the following few questions. For more information on how to contribute to AixLib, see our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?

I have studied the 'AixLib' library from Dymola. From the library I am using the 'High order model
(Appartment_VoWo)'. The Problem I am facing is regarding the effect of sky temperature in energy consumption of the model. I saw that in the 'high order model' there is no seperate model for the radiative Exchange with the sky'. 

Can you suggest me how can I observe the effect of sky temperature in my model?

## Why do we want to solve it?

- ...

## How do we want to solve it?

- ...

**Comment by mlauster** [comment]
@Amuntaseer, thank you for your request. Still, I think this is more an application question and not related to the actual model development. I will close this issue after answering. Please reopen it if you add general extensions to the model that would add value to `AixLib`.
I assume you would like to consider longwave radiation to the outside of exterior walls and windows. For that, I see two different options.
1. Adapt the Equivalent Air Temperature model for ThermalZones.ReducedOrder. This model considers longwave radiation and calculates a virtual outside air temperature for heat exchange. However, it comes with other limitations such as fixed convective heat transfer coefficient.
2. Add a star port on the outside of windows and walls and model the sky as a prescribed temperature source with a star port. Connect them accordingly.
