### ISSUE TITLE
Warning about incompatible types in AixLib.FastHVAC.Components.Storage.BaseClasses.PartialHeatTransferLayers

### ISSUE THREAD

**Issue by ghorwin** [RWTH-EBC/AixLib#543]
Opening AixLib (development, 2018-03-13) in SimulationX gives the following warning/error:

"Die Modelica-Klassen von AixLib.FastHVAC.Components.Storage.BaseClasses.PartialHeatTransferLayers.Medium (package) und der Basisklasse AixLib.FastHVAC.Media.WaterSimple (record) sind nicht kompatibel.
Message: Modelica.IncompatibleBaseClass
"

In fact, AixLib.FastHVAC.Media.WaterSimple is a record, yet requested to be a replaceable package.

Simple fix: use same type for replaceable.

**Comment by PMehrfeld** [comment]
@ghorwin : Should be solved now in development via #567. 
Could you please test it in SimulationX? If it works properly, feel free to close this issue.
