### ISSUE TITLE
Different Weather Models in AixLib don't give the same results

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#548]
This issue is a note for myself to investigate the two models later! But if you have any information on this topic feel free to share them.
## What is the problem?
The two Weather Models from 
-"AixLib.Building.Components.Weather.Weather" 
and
-"AixLib.Boundary.Cinditions.WeatherData.ReaderTMY3"
seems to give different results when calculating the solar radiation on tilted surfaces. 
![screenshot_radiation](https://user-images.githubusercontent.com/27726960/38024371-1b5906f2-3285-11e8-8922-202c910d510e.PNG)

## Why do we want to solve it?
To have a better comparism

## How do we want to solve it?
investigate the models and look for differences

**Comment by mlauster** [comment]
@DaJansenGit, we did some extensive comparison of the models. After perparing all inouts for the new new model (TMY3) in the correct way, we could that they match nearly perfect. I can check where we put the results and we can have a talk abotu that topic.

**Comment by mlauster** [comment]
Some information is at #181

**Comment by PMehrfeld** [comment]
However, the results clearly show differences between both models. Therefore, the origin/reason must be identified, since both models are related to literature of Perez.

**Comment by DaJansenGit** [comment]
@mlauster, at the moment I'm low on time due to finishing my thesis. Thank you for the fast response. I will have a deeper look into this later and contact you
