### ISSUE TITLE
Parameter value changing using script

### ISSUE THREAD

**Issue by Amuntaseer** [RWTH-EBC/AixLib#549]
> Just stopping by to let us know about some issue you encountered with AixLib? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new models to AixLib, please make sure to briefly answer the following few questions. For more information on how to contribute to AixLib, see our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?
I am using the One Family House model in 'AixLib' library. My aim is to do the local sensitivity Analysis of different Parameters. I wrote a script where I am keeping a constant value for all  Parameters (keeping one variable) and trying to simulate it multiple times . After the Simulation , the values are changing but there is no effect shown in the total energy consumption. Can anyone give suggestions regarding this issue.
- ...

## Why do we want to solve it?

- ...If this issue is solved, than it will be an efficient way to do the 'local sensitivity Analysis.'

## How do we want to solve it?

- ...

**Comment by PMehrfeld** [comment]
@Amuntaseer: Did you already perform 2 exemplary simulations manually? Did you then see differences in the total energy consumption? Otherwise, it might be possible that your paramters do not even influence the building's energy consumption (but maybe the thermal power during a day?!).

**Comment by Amuntaseer** [comment]
@PMehrfeld : I have performed various cases manually, where I changed the values of the Parameter directly from the model and it was showing changes in the energy consumption. But whenever I am writing a script to change the values it is showing no effect in the energy consumption. I have attached one of the script, I am giving the Input in this way.
[Script_Parameter change.txt](https://github.com/RWTH-EBC/AixLib/files/1870533/Script_Parameter.change.txt)

**Comment by PMehrfeld** [comment]
@Amuntaseer: I think you should try using DymolaCommands that are directly made for parameter analyses. You can find them in the sub package `DymolaCommands.SimulatorAPI....`.

Here the following functions should be interesting:

- `simulateExtendedModel`

- `simulateMultiExtendedModel`

- `simulateMultiResultsModel`

Have a look at the functions' documentations.

**Comment by Amuntaseer** [comment]
@PMehrfeld : I have tried with the function as you suggested. I followed the documentation and example of Couple Clutched. But it is showing error "undeclared variable or command". Is it possible to provide a tutorial of how to use this function, because I have to vary the Parameters?

**Comment by PMehrfeld** [comment]
@Amuntaseer: Unfortunately, I also have no experience with these functions. So, you probably have to find the solution for this error by yourself ;) Check all declared paramters in your script. Best way to do this, is to execute your script line by line in the Dymola command window until the error occurs.
