### ISSUE TITLE
Revisions of ActiveWall / FloorHeating

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#554]
**This is the continuation of #531** 

## What is the problem?

- Especially Records still have potential to be improved, e.g. regarding capacity parameters as well as naming revisions (e.g. isolution -> insulation, CamelCase, ...).

## Why do we want to solve it?

- Reach understandable parameters in records

## How do we want to solve it?

- [ ] Correct naming, including conversion scripts

- [ ] Bring consistency into the model (e.g. star/therm at top and down side)

- [ ] Optional: Validate the model for surface cooling applications

**Comment by KremerMartin** [comment]
@PMehrfeld Are there some updates on this issue? Could this issue be something for the hackday next week?

**Comment by PMehrfeld** [comment]
@KremerMartin: Good reminder ;)
This will not be solved during hackday. Unfortunately, I cannot participate. Furthermore, @StGoebel is also going to have a look into this issue.

**Comment by Dawac** [comment]
@PMehrfeld and @StGoebel : What is the status on this issue? The upcoming Hackday might be a good opportunity to progress ;-)

**Comment by PMehrfeld** [comment]
@Dawac: Thanks for the reminder. This issue will be my ToDo during upcoming Hackday :+1:

**Comment by PMehrfeld** [comment]
Related to new issue #890

**Comment by MartinRaetz** [comment]
@PMehrfeld 
It seems that this issue is continued in another issue.
I labeled this one "Stale", feel free to undo this action.

**Comment by PMehrfeld** [comment]
You are right. I'll close this issue, since all points from the initial comment should by covered in #890.
