### ISSUE TITLE
name clash: HVAC used twice

### ISSUE THREAD

**Issue by thorade** [RWTH-EBC/AixLib#56]
Your [`AixLib.package.mo`](https://github.com/RWTH-EBC/AixLib/blob/master/AixLib/package.mo#L3) has an annotation which libraries it uses:
```Modelica
annotation(uses(Modelica(version = "3.2.1"), HVAC(version="2.2")));
```
But HVAC is also used for `AixLib.HVAC` (and for the directory that contains that sub-package), resulting in an error message when opening AixLib in Dymola. Maybe the library should be renamed `LibHVAC` or something more meaningful and unique. 
Maybe you want, in addition, completely remove the uses HVAC annotation, because most users of AixLib do not have access to that library.

**Comment by thorade** [comment]
Also, you are using pathes starting with HVAC 62 times (in 12 files). 
Which one of the two HVACs do you mean?

See e.g. line 20 of [CoolerDehumidifier.mo](https://github.com/RWTH-EBC/AixLib/blob/master/AixLib/HVAC/HumidifierAndDehumidifier/CoolerDehumidifier.mo)
versus line 26 of [OneAppartment_Radiators.mo](https://github.com/RWTH-EBC/AixLib/blob/master/AixLib/Building/HighOrder/House/MFD/BuildingAndEnergySystem/OneAppartment_Radiators.mo)

**Comment by mlauster** [comment]
This is an old reference we missed to modify. In AixLib there is only AixLib.HVAC. We will correct that.
