### ISSUE TITLE
VentilationController

### ISSUE THREAD

**Issue by mschumacher247** [RWTH-EBC/AixLib#560]
The ventilation controller within thermalZoneEquipped leads to quite high ventilation rates, esp. during summer nights. This is caused by the Fanger function. The result is that an ideal heaterCooler would try to heat against this high ventilation, leading to substantial heat demand during the summer time. This is not very reasonable in my opinion.

**Comment by mlauster** [comment]
Why is it heating against the ventilation rate? Because of a high User ACH? SummerACH and OverheatingACH shouldn't be an issue in that context. What is your value for the UserACH?

**Comment by mlauster** [comment]
One way to deal with that could be to integrate some kind of shut off of the heater by setting the set temperature in summer time to 10°C.

**Comment by PMehrfeld** [comment]
Was the suggestion, made by @mlauster, successful? If so, please close this issue, @mschumacher247

**Comment by TobiasBlacha** [comment]
One possible solution is the introduction of a heating limit temperature. If the outdoor temperature is above the heating limit temperature, the heating is switched off. In this case, the high ventilation rates do not affect the heat demand calculation.
The heating limit temperature can be calculated according to DIN V 18599-5 or standard values can be selected (10 °C for extremely well insulated buildings, 12 °C for buildings that meet the requirements of the applicable energy saving law, 15 °C for all other buildings).

**Comment by DaJansenGit** [comment]
thanks for the work! Are you currently working on this @PRemmen? Otherwise I would assign it for v0.9.0 :)

**Comment by Dawac** [comment]
Hi @PRemmen, this seems to be an important issue. Is someone currently working on it (there's no branch liked to the issue)? The upcoming Hackday might be a good opportunity for implementation.

**Comment by MartinRaetz** [comment]
I think the behavior of the VentilationController and the set temperature of the ideal heater are correct but can lead to unexpected results.

In my opinion, changing the control strategy of the ideal heater leads to even more complexity and makes it difficult for the user to understand their simulations.
A more sophisticated and specific heating strategy should rather be implemented in the working copy of the user. An easy way to avoid this behavior would be to reduce "hHeat" the maximum power of the heater.

I cannot assess whether the model of the "window opening by the user" is correct. If it does overrate the likelihood of a user to open the window in the summertime, changes should be implemented there.

As the window opening has a quite intense and often unforeseen influence on the model results, I suggest setting the default value of "use_constant_ach_rate" to true. In that manner, the default model behaves more logically. Those in need of window opening should activate it knowingly. In that case, the corresponding parameter for the window opening should be assessed anyways. 

My suggestion: setting the default value of "use_constant_ach_rate" to true

(I will not touch the parameter defaults in Teaser)

**Comment by MartinRaetz** [comment]
Setting the default value to true is not beneficial. The examples would produce different results and CI unit tests would not detect changes in the window opening behavior of the user.

I will try to make things more clear in the infobox and close this issue.
