### ISSUE TITLE
Add new pump model

### ISSUE THREAD

**Issue by pema1** [RWTH-EBC/AixLib#563]
## What is the problem?

- The current pump uses pure Affinity laws. However, normal pumps show deviations from this law.
- Also, normal pumps oftentimes use power limitation in order to reduce the maximum power consumption of the motor.
- Generating parameter sets for the pump model is not easy and requires manual curve fitting and implementation of the resulting data into Modelica code.

## Why do we want to solve it?

- In the Zugabe project a new pump model was developed that solves the above mentioned issues.

## How do we want to solve it?

- We will transfer the model from the Zugabe library into AixLib.
- The pump model uses polynomial functions to calculate pump head and power.
- The pump model uses records that store all necessary data to define the pump.
- Control and physics are separated.
- We will add a script that allows to generate pump parameters (record) more easily.

**Comment by pema1** [comment]
The pump models will be used with the new HydraulicModules in #462 

* [ ] Add new pump models
* [ ] Add a set of pumps

**Comment by PMehrfeld** [comment]
- [ ] Be aware of the pump controller (+ bus), which is currently in the package for the hydraulic modules #462. Bus interface should probably be inserted in the pump package. (@alexanderAKU and @pema1).

**Comment by DaJansenGit** [comment]
@alexanderAKU could you have a look at this? I heard you are using the model.

**Comment by KremerMartin** [comment]
@alexanderAKU Could this issue be something for the hackday? If not, you can just remove the label hackday. ;)

**Comment by alexanderAKU** [comment]
merged into development
