### ISSUE TITLE
Restructuring of the AixLib.FastHVAC.Components package

### ISSUE THREAD

**Issue by TobiasBlacha** [RWTH-EBC/AixLib#564]
## What is the problem?
Restructuring of the FastHVAC package, in the Components package the models are not sorted alphabetically.

## Why do we want to solve it?
Alphabetical sorting increases the clearness

## How do we want to solve it?
New order of the models in the AixLib.FastHVAC.Components package

**Comment by DaJansenGit** [comment]
we should restructure the fasthvac like the way the fluid is structured. Therefore I will
* [ ] move all components from Components package to top folder of the FastHVAC
* [ ] move examples from the central example package to the different components

**Comment by Dawac** [comment]
@DaJansenGit can we close this issue, as you seem to have solved it.

**Comment by DaJansenGit** [comment]
yes the restructered package order is included in the branch [issue309_makeFastHvacGreatAgain ](https://github.com/RWTH-EBC/AixLib/tree/issue309_makeFastHvacGreatAgain). I referenced this issue in the belonging issue #565. We can close this issue now.
