### ISSUE TITLE
Developing a building model for a benchmark for control strategies

### ISSUE THREAD

**Issue by BAG1993** [RWTH-EBC/AixLib#575]
## What is the problem?

- Currently there is no standardized building model to benchmark control strategies and to compare it to other control strategies. 

## Why do we want to solve it?

- It would open up the possibility to compare different control strategies quantitatively.

## How do we want to solve it?

- We will develop a building with exisiting and adapted modells.

- The building will include a moderate complex energy system, a weather data set, internal loads and the judging criteria

**Comment by AnaConstantin** [comment]
Hello @BAG1993 I find the ideea very good. We actually have such a residential building (the one family dweling) including energy system which did not make it to AixLib yet. It would be a great opportunity to do this.
This building in question has one energy delivery system based on radiators and one with floor heating.
This are selectable. The generation system is a boiler, the distribution a pump.
If you build a branch I could try to upload the model and replace any older models with newer ones and also reference the documentation. However I will not invest too much time in getting the system to work if it does not do this imediately. This might be time consuming and I do not have this time. What is your time plan on this issue?
I additonaly suggest asking @PMehrfeld on his opinion on how to structure an energy system. To my knowledge he structures it according to generation, distribution, delivery modules, which can then be replaceable. I find this approach very good.

**Comment by PMehrfeld** [comment]
@BAG1993 : Especially regarding a building model we have different options in `AixLib` (`Reduced Order Model` and `High Order Model`). As @AnaConstantin mentioned, we already have suitable models for hydronic systems. However, I can also provide a tool with which it is easy to create in a semi-automatic process new hydronic networks that fit to your building model and heat transfer system.

**Comment by BAG1993** [comment]
Hello @AnaConstantin and @PMehrfeld at first thanks for your feedback.
I'm writing my bachelor thesis about this model, so i hope that this model will work as soon as possible. The next step is to register the thesis and then i have 10 weeks.
I read previously about benchmarking and normaly you don't use just one model to benchmark your control strategie, because every model has a different focus. So it would be great to have a range of different models like a residentatial building or a industrial buidling up to an office building which i am developing right now. My plan is to develop a ready to simulate model, if a control strategie is implemented. So all systems without the control strategie should be more or less fixed.
I thought about the structure of the model and talked with @alexanderAKU and @fstinner and worked out a first draft of the structure. The generation system should consist of a heatpump, a CHP, a boiler and a geothermal field, with three different temperature levels. The delivery system shoud be an air-based HVAC system and a thermal component activation. I think the structure you mentioned @AnaConstantin is a good approach and i will implement my model with this structure.
I build the branch today so you can add the models and tools so i can get to know the models and tools. In addition i will scan the library for suitable models.

**Comment by PMehrfeld** [comment]
@BAG1993 : This sounds like a planned approach for your thesis. Anyway, I would like to bring [this Wiki page](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Structure-a-Building-Performance-Simulation) to your attention. It is so far just a first shot of explaining how to generally structure a whole building + HVAC simulation. I think in your case it is important to separate the control models from the HVAC models where possible.

**Comment by BAG1993** [comment]
@PMehrfeld thanks for the link, we though about adding a "Control Bus" so a new control strategie just need to connect the bus to avoid matching the right connector for the different variables the control get and manipulate. Because we don't know jet if we enable the full controll over all pumps and valves or just give some operating modes, the control model size isn't clear jet. I think later in the development process the question will be answered.
But I will try to stik to the structure.

**Comment by PMehrfeld** [comment]
I just came across the quite old issue #354 and the according branch [`issue354_controllerInterfaces`](https://github.com/RWTH-EBC/AixLib/tree/issue354_controllerInterfaces). Maybe some previous work can be used here?!

**Comment by FabianBekemeier** [comment]
Hello everyone,
I am working on my Bachelor-Thesis supervised by @alexanderAKU and will use the benchmark-model. The aim is to compare two different control strategies (modus-based and MPC). Beforehand I am going to edit the benchmark-model by modularizing some components to make it more flexible and easier to use. 
Since the issue575_benchmarkModel-branch has not been updated for some time, several important changes are not inherited. Trying to merge the issue575_benchmarkModel- and development-branches resulted in too many conflicts.
Therefore, I created a new branch issue575_benchmarkModel_reworked in order to work with the benchmark model.

**Comment by BAG1993** [comment]
Hallo Fabian,

Ich kenne die Änderungen der aixlib nicht genau, du solltest die aber unbedingt das Wettermodel anschauen, da die Wetterdaten in der jetzigen Form ungeeignet sind.

Viele Grüße,
Bastian

Am 09.07.2019 16:37 schrieb FabianBekemeier <notifications@github.com>:

Hello everyone,
I am working on my Bachelor-Thesis supervised by @alexanderAKU<https://github.com/alexanderAKU> and will use the benchmark-model. The aim is to compare two different control strategies (modus-based and MPC). Beforehand I am going to edit the benchmark-model by modularizing some components to make it more flexible and easier to use.
Since the issue575_benchmarkModel-branch has not been updated for some time, several important changes are not inherited. Trying to merge the issue575_benchmarkModel- and development-branches resulted in too many conflicts.
Therefore, I created a new branch issue575_benchmarkModel_reworked in order to work with the benchmark model.

**Comment by alexanderAKU** [comment]
currenlty, the model is based on the development in #524 and reuses the same subsystem models
