### ISSUE TITLE
More examples for residential and non-residential buildings needed

### ISSUE THREAD

**Issue by PooyanJahangiri** [RWTH-EBC/AixLib#58]
Start a branch for building application examples for residential and non residential buildings

**Comment by marcusfuchs** [comment]
@AnaConstantin: Is this still open?

**Comment by AnaConstantin** [comment]
Would be nice to have but not relevant at the moment. Let's see how the HVAC package looks after we finish our work with it and then decide if we should build new example. What do you think @PooyanJahangiri?

**Comment by AnaConstantin** [comment]
I would close the issue, as we can formulate a more concrete one if needed
