### ISSUE TITLE
Systems Package

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#581]
## What is the problem?

- Modeling large systems is highly time consuming because the user needs to bring many small models together (such as pumps, sensors, valves, heatflows, volumes,...). Additionally, the user needs a lot of expertise to user fitting models and to set the right parameters (such as starting values, nominal flows, allowReversalFlow, ,..). 
Besides, many 'larger' models consists of different types of basic models (AirFlow, Fluid, Controls) and can't be grouped into one of these packages.

## Why do we want to solve it?

- We want to provide easy to use models of subsystems which consists of severel basic models (e.g. hydronic circuits, air handling units with hydronic circuits, subsystem consisting of well parametrized combination of boiler and storage,..).
Additionally, we want to collect reusable models of complete systems as examples in the systems package

## How do we want to solve it?

- We will create a new main level package named "Systems".

**Comment by alexanderAKU** [comment]
**First, we should discuss some basic rules concerning:**


1. Package strucure

2. Connections

3. Model structure

4. ...


**First suggestions:**
1. I suggest to define a subpackage e.g. AHU, with subpackages for control, baseClass, and example and maybe data.

2. We can use the busConnector for all data connections (temperaures, massflow, control signals)

3. I'm going to create a new branch with first models for the Systems package (models from isssue #462)

**Comment by PMehrfeld** [comment]
First step done with creating the package in #592

**Comment by PMehrfeld** [comment]
@alexanderAKU : Do you think we need to keep this issue opened? I think good first steps are done :)
