### ISSUE TITLE
Modular AirHandlingUnit Register

### ISSUE THREAD

**Issue by FelixStege** [RWTH-EBC/AixLib#583]
## What is the problem?

- One of the problems in modeling hydraulic systems is, that the user needs a lot of expertise about the specific physical parameters (such as heat capacity, pipe length/diameter, minor loss coefficient,...). If already installed systems are to be investigated, knowing the exact parameter values is essential for good simulation results. But it is often difficult to identify the parameter values for components that are already installed and linked. 
Therefor we want to develop an automated calibrator in Python that determines the exact parameter values of modular hydraulic systems. 

## Why do we want to solve it?

- The provision of modular hydraulic systems enables an automated calibrator for quick and good determination of parameter values, so that this time-consuming part no longer has to be done by the user.

## How do we want to solve it?

- This issue is based on issue #462, which provides specific standardized modules, such as injection circuit or admix circuit. These modules are used to create modular AHU registers for the calibrator. After models and calibrator have been successfully developed, they will be integrated in issue #581 for further use.

**Comment by FelixStege** [comment]
The following hydraulic modules will be developed:

- [ ] admix circuit 

- [ ] Throttle circuit

- [ ] injection circuit

**Comment by KremerMartin** [comment]
@alexanderAKU Maybe it would be wise to collect the issues #677 , #360 and this issue in one issue, as they are all tackling a similar issue.
Could you give us an update on which of the three issues will be solved or maybe have been solved?

**Comment by Dawac** [comment]
@alexanderAKU can we close this issue?
