### ISSUE TITLE
Encoding and non ASCII characters

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#587]
See [this comment](https://github.com/RWTH-EBC/AixLib/pull/586#issuecomment-411022931).

- [x] ~~CI for non ASCII characters~~

- [x] ~~All files to encoding UTF-8 without BOM (no ANSI, no UTF-8 with BOM) --> still checking wether w/ or w/o BOM~~

ToDos not done due to evolution within this issue thread.

**Comment by PMehrfeld** [comment]
Dymola has by default set the following flag:

`Advanced.AlwaysWriteUTF8 = true "If true write UTF-8 files even if only ASCII contents. Can be changed without new translation of model";`

With the small tool [EncodingChecker](https://archive.codeplex.com/?p=encodingchecker) you can identify Encoding of files in all sub directories.

We need to stick to one specific encoding!! (My proposal is above.)

The ouput looks like this:
![image](https://user-images.githubusercontent.com/11769433/55324237-ba064c00-5481-11e9-955c-fc69136ced74.png)

**Comment by MichaMans** [comment]
maybe we can enhance the buildingspy for that test, or ad-hoc implement a few lines in the ```bin/runUnitTest.py``` with the help of python charset

**Comment by PMehrfeld** [comment]
I agree, it will be possible with python, but I would not add the lines to that script, since it has nothing to do with unit testing.

**Comment by PMehrfeld** [comment]
https://stackoverflow.com/a/192086/5568719

This might help.

**Comment by MichaMans** [comment]
so just a naming issue? i don't see that as a barrier, because there are html only checks as well there. But as i said, quickly fork and implement that in the buildingspy should work. going for such an output:
![image](https://user-images.githubusercontent.com/15192234/55327308-15d4d300-548a-11e9-90b1-9a95c9c3b721.png)

Twoliner with chardet, needs to be tested 
```python
vals = chardet.detect(open(fil, 'rb').read())
            if not 'UTF-8' in vals['encoding']:
```

**Comment by PMehrfeld** [comment]
Yes, we should provide one script doing only one thing. And in this case it would be checking encodings with a hint how to handle wrong encodings (e. g. with notepad++ which is good for single file conversion).

**Comment by MichaMans** [comment]
I don't see why we should go for such a solution, first i would suggest that as an enhancement at the BuildingsPy, if they don't see that as a helpfull feature (i don't think so), we can discuss if we want to go for a dezentral, only available in aixlib solution

**Comment by PMehrfeld** [comment]
It might be an enhancement for BuildingsPy. 
However, as we just discussed personally, we will go towards multiple scripts for CI instead of on single, huge `runUnitTests.py`.

**Comment by mwetter** [comment]
We could add a method to `buildingspy.development.validator`, such as `validateEncoding(...)`. This would then in design and usage be similar to the existing method `validateHTMLInPackage`.

**Comment by FWuellhorst** [comment]
Some insides from the development of a script to detect and convert encodings. Note that i briefly dived into the topic. If some inside/conclusion is wrong, please correct me.

**Detecting encoding**
Taken from [here](https://stackoverflow.com/questions/436220/how-to-determine-the-encoding-of-text):
> Correctly detecting the encoding all times is impossible.
> There is the chardet library that uses that study to try to detect encoding. 

So, chardet will only attempt to find the correct encoding. In some cases, the confidence of chardet is quite low and the result is wrong. Especially when non-ASCII characters occur.
When detecting a files encoding it is worth noting, that (taken from [here](https://stackoverflow.com/a/4983999/9212441)):

> ASCII is a subset of UTF-8, so if a document is ASCII then it is already UTF-8. 

To check the correct type of encoding, use Windows Editor, git or notepad++. The default Editor on Windows and git will detect ASCII when notepad++ states it's utf-8. However, all three don't seem to have problems detecting the correct encoding with non-ASCII characters.

**Converting Encoding**
Works pretty well using codecs. Note: When checking if conversion was successful, a correct converted file without non-ASCII characters will be detected as ASCII. 

**Conclusion**
Eliminating all non-ASCII characters first, and then using the created detector_converter script i created, will result in all files being in ASCII (and thus utf-8).

**Comment by PMehrfeld** [comment]
As discussed with @MichaMans:

1. We are going to allow non ASCII characters, since UTF-8 kind of implys to allow them (and we are not in 1970 anymore).
1. We will convert encoding of the *.mo files just before a master merge and release.
1. Version number at second level will be raised.

(Furthermore, I edited the ToDos in my initial post)

**Comment by PMehrfeld** [comment]
Furthermore, I want to add the open point of newline:
LF vs. CRLF

Following git config might be interesting:
[core]
`  autocrlf = false` or true

**Comment by PMehrfeld** [comment]
## Summary

Problem: Sometimes it is necessary to just save the whole package with one click (e.g. lots of renaming changes). Afterwards, we need to do a commit with several changes. There occur several issues:

**LF vs. CRLF**
If having set `git config core.autocrlf input` (or best: `git config --global core.autocrlf input`) switching between LF and CRLF is not marked as differences in git. Also not shown as changes in GitHub's web diff viewer. Furthermore, when cloning the repo clean from remote, all line breaks are `LF` again although file was committed with `CRLF` just a few seconds before.
--> Thus, we don't concern about this issue

**Dymola**
Changes due to Dymola's "tidying up strategy" (I just sent a request to the support, but if I remember correctly we already looked for a solution once and there didn't exist one).
--> This is annoying and needs to be resolved

**Encoding (Dymola)**
Dymola's flag `Advanced.AlwaysWriteUTF8` is important.
If `true` and file has no `BOM`, `BOM` is added.
If `true` and file has `BOM` it remains.
If `false` and file has no `BOM`, it remains.
If `false` and file has `BOM`:
1. `BOM` is removed, if file contains only ASCII characters
1. remains with `BOM`, if file contains non-ASCII characters

Examples for:
with BOM: AixLib.Controls.HVACAgentBasedControl.Examples.BookTrading.BookTrading (contains an ü in Bünning)
w/o BOM: AixLib.Controls.HVACAgentBasedControl.Examples.BookTrading.NetworkCommunication1

Further addition (flag is still false):
Starting point: file with BOM contains ü --> change in Dymola to ue --> save --> file now without BOM. 
Option 1: change ue back to ü in Notepad++ --> file UTF-8 but without BOM
Option 2: change ue back to ü in Dymola (flag still false!) --> UTF-8 with BOM

@mwetter : Do you take care of these issues in the IBPSA library? Since we of course merge this library into AixLib, we should stick to your rules. From a first check, it seems as if you never have BOM at your files.

## Suggestion for a solution
Normally, I would say, we set Advanced.AlwaysWriteUTF8 = true, because then all files have BOM. Dymola's default is false. But we will get a mixture anyway, since different commits will be made converting or not converting encoding. Furthermore, IBPSA library seems to have no BOM in files.
As a conclusions, we should leave `Advanced.AlwaysWriteUTF8 = false` but, before doing e.g. a refactoring where multiple files are changed in a branch, proceed as following (assuming you are already working in a branch called `issue123_featureDev`):
1. branch away from `development` calling the branch e.g. `issue123_librarySaveAutomaticRestructuring`
1. save the whole AixLib and make a single commit 
1. merge branch back into `development`
1. update your branch `issue123_featureDev` by merging `development` into your branch
1. do refactoring + write conversion script

Then we will be able to differentiate between Dymola's encoding conversions and "tidy up changes" and the **files that were really changed due to your new feature**.
We should also do a single library save before a new master release.

- [ ] Link from AixLib wiki to this post, if some people agree (what do you think @MichaMans, @FWuellhorst)

**Comment by MichaMans** [comment]
@PMehrfeld

**Comment by FWuellhorst** [comment]
Regarding BOM: I would also suggest to set the flag `Advanced.AlwaysWriteUTF8 = false`. This way, all files with non-ASCIIS will have a BOM. This BOM can easily be automatically detected and converted to utf-8.
If we set it to true save all files with BOM, the script could also convert all files to utf-8, however will take longer as all files would have to be converted.

**Comment by PMehrfeld** [comment]
Example: #710 
Furthermore, I introduced a new label [`DymolaAutoFormat`](https://github.com/RWTH-EBC/AixLib/labels).

**Comment by PMehrfeld** [comment]
Final decision so far:
1. Dymola's auto formatting does not allow to achieve a clear versioning.
1. Thus, we go with my 5-step proposal above (I will write a wiki page)
1. Currently, we are not going address the file encoding, since this will be "destroyed" by Dymola's library saving anyway. Nonetheless, thanks @mwetter for your proposal to include a function in BuildingsPy, but from current status we do not need such a function anylonger.

**Comment by PMehrfeld** [comment]
https://github.com/RWTH-EBC/AixLib/wiki/Problems-during-contribution-process
