### ISSUE TITLE
Expansion valves for modular heat pumps 

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#590]
### **What is the problem?**

The issue refers to/is a partial solution for issue #457. 

We want to extend an existing model of an expansion valve by integrating compression effects.

### **Why do we want to solve it?**

We want to solve this in accordance with issue #457: The expansion valve can be used in closed loop systems such as heat pumps.

### **How do we want to solve it?**

Regarding the expansion valve model:

- We will model an isenthalpic expansion valve
- The mass flow characteristic is based on the Bernoulli equation m_flow = f(C,p_in,p_out).
- Bernoulli equation is modified to m_flow=f(C,p_in,p_th).
- Different models of metastability coefficients (C_meta) are implemented. 
- Model in consideration of compression effects (Y=f(p_in,p_out,kappa)).
- We will test the model in terms of simulation speed, robustness and number of equations

**Comment by cvering** [comment]
Thank you Sven for your input! We are curious of your results!

**Comment by cvering** [comment]
Thank you all for your kind support! We will close this issue and bring it together in the new vapor compression cycle package: #739
