### ISSUE TITLE
Add System package for exemplary BES

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#591]
**What is the problem?**

- The upcoming package `Systems` should receive valuable sub packes

**How do we want to solve it? Describe the solution you'd like**

- Add an example according to [this description](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Structure-a-Building-Performance-Simulation).

**Components that will be included:**
- heat pump
- buffer storage (for space heating)
- DHW model
- DHW tank
- hydronic network
- heat transfer system (radiator and/or under floor heating)
- building envelope (high order model)
- control for HVAC
- boundary condtions (weather, TSet, internal gains, air change rate, ...)

**Comment by KremerMartin** [comment]
@PMehrfeld Is there an update on this issue? Maybe this could be something for the hackday next week.

**Comment by PMehrfeld** [comment]
@KremerMartin: I set it to `Deep Future` milestone ;)

**Comment by alexanderAKU** [comment]
@PMehrfeld have a look in the branches to #524 and #575 
The models are organized in your proposed structure.

**Comment by PMehrfeld** [comment]
Sounds good for me. Thanks for the hint.
