### ISSUE TITLE
Add CondensingBoilerPhysics model

### ISSUE THREAD

**Issue by LucaVedda** [RWTH-EBC/AixLib#597]
### What is the problem?

- The AixLib 'Boiler' model is very simple and its functionality restricted, e.g. it's working without any boiler efficiency factors.

### Why do we want to solve it?

- We want AixLib to provide a boiler model for a broader variety of user cases.

### How do we want to solve it?

- We will create a new 'CondensingBoilerPhysics' model in AixLib which partially works with AixLib submodules.

**Comment by PMehrfeld** [comment]
@LucaVedda : Thanks for the issue. This sounds like a promising enhancement.
Is this model really limited to condensing boiler applications? Or can it also be parametrized to function as a conventional boiler (without condensing effect)? If it is possible, the name should probably be revised.

**Comment by LucaVedda** [comment]
Right now, the model is just for condensing boiler purposes. However, it can be changed to work without condensing effect in the future. The model is referred from the BuildSysPro library and based upon the literature "Règles de modélisation des systèmes énergétiques dans les bâtiments basse consommation". It uses different manufacturers database from ATITA.

**Comment by Dawac** [comment]
@alexanderAKU what is the plan with this model? The Building Library offers a detailed Boiler Model aswell, furthermore for simple application condensing boilers could probably be approximated by the efficiency tables.

**Comment by alexanderAKU** [comment]
I will check the Building library model. The boiler model that we wanted to add is based on many different records. However, these records are not publicly availably anymore.

**Comment by KremerMartin** [comment]
@alexanderAKU @Dawac Could this be something for the Hackday next week?

**Comment by alexanderAKU** [comment]
Merged into development
