### ISSUE TITLE
Release 0.6.1 with merge of IBPSA Lib

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#603]
There was a bugfix regarding `FourElement` model in IBPSA Lib, see https://github.com/ibpsa/modelica-ibpsa/pull/1004. To get this into AixLib and have the latest version of IBPSA Lib merged, I will do such a merge and afterwards release version 0.6.1. Since we have some slight changes already in AixLib compared to the latest release, that are ready to see the master, I will work on the development and merge the development into the master.

**Comment by PMehrfeld** [comment]
@mlauster : I have merged the branch and deleted it.
I close this issue.
