### ISSUE TITLE
Rotating piston compressor for modular heat pumps based on physical equations

### ISSUE THREAD

**Issue by StGoebel** [RWTH-EBC/AixLib#609]
**What is the problem?**
This issue is a work package for issue #407 

Currently, there are no compressor models based on physical equations or ones that consider the geometry of the compressor (i.e. roller size, cylinder size)

**Why do we want to solve it?**
Compressor models based on physical equations are probably more accurate and need less validation data. Those models could be used for instance to analyse the effect of different refrigerating media in a refrigerant circuit.

**How do we want to solve it?**

- The model will be based on the principles of the mass and energy conversation equations

- We will create models for the mechanical part of the compressor (i.e. moment of friction force) to calculate the mechanical losses

- Temperature and pressure of the refrigerant will be calculated with the rotation of the crankshaft

- The mass losses will be calculated with the pressure difference between the suction chamber and the compression chamber

- The model will consider heat transfer to the refrigerant in the case and in the chambers

**Comment by cvering** [comment]
Thank you all for your kind support! We will close this issue and bring it together in the new vapor compression cycle package: #739
