### ISSUE TITLE
Modell modification for better calibration

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/AixLib#610]
**What is the problem?**
Some models do not include some physics which are important for representing 
dynamic system behaviour and give the option to adapt them based on real building data.

**How do we want to solve it? Describe the solution you'd like**

We add physical delays and calibrate them based on real data

**Describe alternatives you've considered**

We did not consider any alternatives because we want to use as much AixLib models as possible

**Comment by LauraMaier** [comment]
Hi @tstorek, what is the current status? :)

**Comment by KremerMartin** [comment]
@tstorek What is the current status of this issue? Could this be something for the hackday next week?

**Comment by Dawac** [comment]
@tstorek we would like to close this issue on the upcoming Hackday.
