### ISSUE TITLE
Enhancements to the new HP Model

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#615]
**What is the problem?**
As mentioned in #577, a new heat pump model was implemented. The first version of the model is now in the current devolopment and works.
There are a few points i will change / add in the near future. Some may also be suggestions to future development of the model.

**How do we want to solve it?**
- [x] Add a function for the icing factor based on an existing model
- [x] The polynomal approach in the IBPSA HP Model Carnot_y shall be used as an example function for the new model
- [x] Propagate and test the ND-DataTables model
- [x] Add an example .sdf file to demonstrate usage of ND-DataTables
- [x] Add a base record for chiller data. This data will also be based on the EN 14511. So far no data is inside the AixLib, thus the chiller function of the model can't be tested
- [x] The scaling factor may be included into the nominal pressure loss parameter as well as the nominal heat transfer coefficient both on evaporator and condenser side
- [x] Make the boundary map model icon dynamic based on the table data provided
- [x] Documentation and revisions have to be added

If anyone is using any model related to the new heat pump model, such as models from these packages
- `Systems.HeatPumpSystem`
- `Controls.HeatPump`
- `Fluid.HeatPump.BaseClasses`

and has suggestions for improvements or encountered bugs, please refer to this issue.

**Comment by FWuellhorst** [comment]
Besides the points mentioned above, i will also change/implement the following features:

- [ ] Add a hysterese to the operation envelope and defrost model
- [ ] Change the week-based aproach in the `antiLegionella` model to a more user-friendly approach(e.g. daily, hourly, weekly etc.)
- [ ] Create a nominal point and make all parameters dependend on this nominal point. New Parameters will be defined to create this nominal point: nominal heat flow, supply temperature, percentage of heat losses, pinch temperature and temperature delta over the heat exchangers.
- [ ] Add the coefficients for the polynom-based approach to all baseRecords of heat pumps and move the functions package to `AixLib.DataBase.HeatPump`

After completing all of these points (and the documentation), this issue is considered finished and the branch can be merged into the development.

**Comment by FWuellhorst** [comment]
I did implement the function for the polynom based approach. However i didn't add the coefficients to the base data, as the deviations from the actual table data are unreasonable high.

**Comment by PMehrfeld** [comment]
Closed via #668
