### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by munadel4** [RWTH-EBC/AixLib#616]
<img width="272" alt="screen shot 2018-10-02 at 10 09 04 am" src="https://user-images.githubusercontent.com/2528482/46334470-e48b5f80-c62c-11e8-9dae-ba420c26372a.png">
<img width="1440" alt="screen shot 2018-10-02 at 10 10 25 am" src="https://user-images.githubusercontent.com/2528482/46334471-e48b5f80-c62c-11e8-99c7-bcbc2e4cdc71.png">
<img width="1440" alt="screen shot 2018-10-02 at 10 11 12 am" src="https://user-images.githubusercontent.com/2528482/46334473-e523f600-c62c-11e8-9b24-e0ea8b85c008.png">
<img width="905" alt="screen shot 2018-10-02 at 10 11 32 am" src="https://user-images.githubusercontent.com/2528482/46334474-e523f600-c62c-11e8-8c70-76039d657437.png">
<img width="1237" alt="screen shot 2018-10-02 at 10 13 10 am" src="https://user-images.githubusercontent.com/2528482/46334475-e523f600-c62c-11e8-940e-2b47907b45f3.png">
![simulator screen shot - ipad air 2 - 2018-10-02 at 01 50 05](https://user-images.githubusercontent.com/2528482/46334476-e523f600-c62c-11e8-9be9-ae1f368be33e.png)

**Comment by mlauster** [comment]
@munadel4, for what do you need these images? I think there are already alternatives to upload them... Anyway, I will close this issue, you can still use the images then.
