### ISSUE TITLE
Reworking FourPortHeatMassExchanger

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#623]
**What is the problem?**

I want to create a simple heat exchanger model which has a dynamic behavior. Thus, I want to use n volumes for fluid 1 and n volumes for fluid 2 and connect the heat ports to a heat transfer function.
I found a base class in Fluid.Interfaces.FourPortHeatMassExchanger. I think a good way is to extend from this class. Nevertheless, this base class has only one volume for each fluid.

**How do we want to solve it? Describe the solution you'd like**

I want to extends this base class, so that the number of volumes could be set by a parameter n.

**Describe alternatives you've considered**

I could model the heat exchanger without extending the base class, but using existing base classes is recommended.

**Comment by alexanderAKU** [comment]
I'm going to change the following things:

- [ ] rework the layout (small changes, adjusting some lines)
- [ ] adding n volumes and connect the ports with a loop

**Comment by PMehrfeld** [comment]
closed via #624
