### ISSUE TITLE
AixLib/Media/Refrigerants contains "duplicate" packages: R410a and R410A

### ISSUE THREAD

**Issue by adrpo** [RWTH-EBC/AixLib#640]
**Describe the bug**
Both R410a and R410A packages are present which creates problems on both case sensitive and case insensitive file systems.

**To Reproduce**
Load the library in OpenModelica OMEdit.

**Expected behavior**
Merge R410A into R410a (or just remove R410A).
The naming of R134a suggest small caps for last letter.

**Desktop (please complete the following information):**
 - OpenModelica v 1.13.0 nightly builds

**Comment by PMehrfeld** [comment]
@adrpo: Thanks for reporting the bug. 
On Windows we did not really encounter that problem, since case sensitivity is ignored.
I removed the folder on a linux system. In `development` and `master` branch the folder with lower case "a" does not exist anymore. We solved this in #641 and #643.
