### ISSUE TITLE
Simple dynamic heat exchanger model

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#650]
**What is the problem?**

The aixlib contains some heat exchanger. Nevertheless, they don't cover a dynamic behaviour. Thus, is simple heat exchanger model will be developed that bases on the interface FourPortMassExchanger (see #623 )

**How do we want to solve it? Describe the solution you'd like**

The new heat exchanger model extends the FourPortMassExchanger and adds a simple heat transfer

**Describe alternatives you've considered**

There is a simple dynamic heat exchanger model (basicHX) in the modelica standard library that consist of two pipes connected by a heat transfer (wall). Since two pipes are used, the parametrization is not user friendly. Additionally, dehumidification is not considered, which can be a part of a later implementation of the new heat exchanger model

**Comment by alexanderAKU** [comment]
In a first step, a fixed heat transfer will be used. Later developments could integrate a volume flow dependent heat transfer.

**Comment by LauraMaier** [comment]
Hi @alexanderAKU, what is the current status of this issue ? :)
