### ISSUE TITLE
Revisions in window models

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#651]
**Description**

- Model `twoStar_RadEx` in `AixLib.ThermalZones.HighOrder.Components.WindowsDoors.WindowSimple` seems to be redundant. 

- WindowTyp.Emissivity needs to be kept, since it is still used in `Window_ASHRAE140`, where model `twoStar_RadEx` is at correct and necessary position.

- In model `Window_ASHRAE140` the parameters `eps_out` and `phi` seems to be not in use.

**Screenshots**
Testing first issue mentioned above leads to following results in example `AixLib.ThermalZones.HighOrder.Examples.OFD_1Jan` (simulation time 10 d).
Dashed lines do not have component `twoStar_RadEx` in `WindowSimple`.
![image](https://user-images.githubusercontent.com/11769433/47285011-ad83ea80-d5e9-11e8-9e4d-6e5d7753348d.png)

**Desktop (please complete the following information):**
 - Dymola 2019, Windows 10, VS 2017, no DDE

**Additional context**
@FWuellhorst: Please check pedantically, especially if removing the whole component `twoStar_RadEx` in `WindowSimple` leads to different results.

**Comment by FWuellhorst** [comment]
`twoStar_radEx ` has no impact on the `star.T` and `star.Q_flow`. However, the temperature `predescribedHeatFlow.port.T` changes with the equation in `twoStar_radEx `. The temperature `Star.T` is defined by `AixLib.Utilities.Interfaces.Adaptors.HeatStarToComb[5].star.T` and not by `twoStar_radEx`. Therefore the temperature calculation inside `twoStar_radEx` has no impact on the model. Check of all walls\windows in `AixLib.ThermalZones.HighOrder.Examples.OFD_1Jan` confirmes these observations.

**Comment by FWuellhorst** [comment]
The parameters `eps_out` and `phi` are not being used and therefore have no impact on simulation results. They are removed as well.

**Comment by PMehrfeld** [comment]
Closed by #657
