### ISSUE TITLE
Integrate sun blind in the ReducedOrder Model

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#653]
**What is the problem?**

- Outer sun blinds are currently not implemented in current low order models

**How do we want to solve it? Describe the solution you'd like**

- I'll implement small sun blind block in the thermal zone equipped model which considers the total irradiation on the roof and compares this with a certain threshold in the zone parameters. After exceeding the certain threshold the long-wave and shortwave irradiation to the windows are reduced by a fixed factor.

**Describe alternatives you've considered**

There are two alternatives considered and maybe used for a future "clean" Implementation:
- The old sun blind model with the old connectors --> converting to the new connectors
- The shaded window model from @StanleyRisch could be used for this as well

**Additional context**

I'll go for my own quick and dirty implementation for the first try.

**Comment by PMehrfeld** [comment]
Maybe think of using the `smooth()` function or adding a filter (like in the mover or valve models) that can optionally be disabled. With this approach you will keep the equation 
continuously differentiable.  
I am not sure what approach `Buildings` uses. But it might be worse to have a look into their modelling work ;)

**Comment by Dawac** [comment]
@MichaMans could you give an update on this issue? There is currently no branch connected directly to this. Is this an issue that still should be tackled at the upcoming Hackday?

**Comment by PRemmen** [comment]
I made a new proposal for a very simple external shading here: https://github.com/RWTH-EBC/TEASER/commit/f28ebf833e912d939a003dc234f60f335e83d0b5 and here: https://github.com/RWTH-EBC/AixLib/commit/5d37835841b9ed8cbbc8baa25217f8bf3a6dd305. There is on issue left for AixLib, any help appreciated:
![grafik](https://user-images.githubusercontent.com/8124013/72838899-85be7f00-3c91-11ea-9746-de1685dbbb0f.png)

**Comment by PRemmen** [comment]
the new model wasn't conditional while the connected models are. I fixed this.

**Comment by MartinRaetz** [comment]
This issue is solved with https://github.com/RWTH-EBC/AixLib/pull/861.
If that is not the case, please re-open the issue.
