### ISSUE TITLE
Issue309 New heatpump model

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#660]
**What is the problem?**

With #577 a new heatpump model was developed for the AixLib. Gratefully the new model uses a blackbox approach for the refregeriant cycle so we should be able to simply reuse it in the fastHVAC lib.

**How do we want to solve it? Describe the solution you'd like**

Switch the fluid depending elements (ports, volumes) to fastHvac elements.

**Comment by FWuellhorst** [comment]
Please also see #615, some implementations are still missing. I will implement them in the next two weeks.

**Comment by nhuelsenbeck** [comment]
The heatpump model was adapted to the FastHVAC library. It was named HeatPump2. The following components were added to the FastHVAC lib for successful completion:
- Components\HeatGenerators\HeatPump2
- BaseClasses\EvaporatorCondenserWithCapacity
- Interfaces\TwoPortHeatMassExchanger
- Examples\HeatGenerators\HeatPump\ValidationHeatPump2

**Comment by DaJansenGit** [comment]
with #683 the implementation is finished. Thanks @nhuelsenbeck
