### ISSUE TITLE
Integrate decentralized ventilation unit to HighOrder Model

### ISSUE THREAD

**Issue by ghost** [RWTH-EBC/AixLib#664]
**What is the problem?**

Ventilation is only realized via constant volume flows, either by infiltration or natural ventilation. Since, the deliverable volume flows of decentralized ventilation devices are strongly dependent on wind conditions at the building, a new model must be generated.

**How do we want to solve it? Describe the solution you'd like**

The HighOrder Wall model will be extended by optional Fluid-Connectors and an integrated ventilation device. Its behaviour due to wind pressure condition is applied by a characteristic curve. Therefore, the room air volume is also extended by optional Fluid-Connectors.

**Comment by KremerMartin** [comment]
@TimRoeder Are there any updates on this issue?
