### ISSUE TITLE
Refrigerants R744 (CO2) and R32 for modular heat pumps 

### ISSUE THREAD

**Issue by StGoebel** [RWTH-EBC/AixLib#665]
**What is the problem?**

This issue is a work package for issue #407 
Currently, there are just two refrigerants within the AixLib library. Therefore, we want to add two different refrigerants (R744 (CO2) and R32).

**How do we want to solve it? Describe the solution you'd like**

We will use the approach presented by Sangi et al. (see paper “A Medium Model for the Refrigerant Propane for Fast and Accurate Dynamic Simulations”; http://www.ebc.eonerc.rwth-aachen.de/go/id/dncb/file/227214). Sangi et al. calculated functions for the density, specific enthalpy and specific entropy for the three different regimes supercooled, superheated and two-phase. Additionaly, we added four regimes for the supercritical phase for R744 (CO2). These functions were polynomial and fitted to the inverse energy equation of state.

**Who do we think will benefit from our solution?**

We think that everyone will benefit from the models who needs refrigerants without using external media libraries. Moreover, the presented approach allows a fast and accurate simulation and, therefore, contributes to everyone who will focus the simulation speed.

**Comment by cvering** [comment]
Thank you all for your kind support! We will merge our refrigerant models in the IBPSA Library. Further developments are discussed in this issue now: https://github.com/ibpsa/modelica-ibpsa/issues/1093
