### ISSUE TITLE
Development of physical, modular CHP models

### ISSUE THREAD

**Issue by JulianMatthes** [RWTH-EBC/AixLib#667]
**What is the problem?**

The existing models of CHP units inside energy building systems are black-box-models. They do not take into account physical and chemical equations. Therefore they are not able to calculate the energetic/material balances and cannot show the starting and stopping operation precisely. Moreover the implemented control algorithms do not reproduce the current state of the institute main building. Some efforts are planned to be done here as well. 

**Why do we want to solve it?**

Accurate models that take energetic balances and substance compositions into account help to evaluate control strategies due to the carbondioxide outlet.

**How do we want to solve it?**

Based on literature research I want to build new grey-box-models for the main components of CHP units. They need to be founded on physical approaches extended by purposeful assumptions and empirical equations to ensure good simulation performance. Furthermore a hierachical structured model for the HTC of the Institute main building should be created.
The PowerUnit will be modeled as an ICE containing submodels for the combustion calculation, the heat flow from the combustion chamber to the cooling circle, the exhaust heat exchanger and the asynchronous electric machine. This also includes base records for ICEs and different fuel types.

**Comment by DaJansenGit** [comment]
with the merge of #714 the model is merged into development. I will close this issue for now, it can be reopened at any time for further improvements of the modular CHP model.
