### ISSUE TITLE
Dynamic Distributor model

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#673]
**What is the problem?**

The model `AixLib.Fluid.HeatExchangers.ActiveWalls.Distributor` is limited to exactly six floor heating circuits. Some models (e.g. MoNetGen) need a dynamic number of floor heating circuits.

**How do we want to solve it?**
Within the project of the MoNetGen a dynamic distributor was created. We will take this model, change some minor things to match the `AixLib` guidelines and integrate it into the `AixLib`.

**Comment by FWuellhorst** [comment]
@PMehrfeld :
I suggest to rename some ports and elements:
`volume` to `vol_flow`
`volume1` to `vol_return`
`MAIN_FLOW` to `main_flow`
`MAIN_RETURN` to `main_return`
Or is this caps-version according to some styleguide?

**Comment by PMehrfeld** [comment]
Closed by #705
