### ISSUE TITLE
Improvement of hydraulic module controllers

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#675]
**What is the problem?**

- The controls of the hydraulic modules are not generic (e.g. reverse action not implemented) and not available for all modules

**How do we want to solve it? Describe the solution you'd like**

- We need to imporve the existing controllers and add new ones

**Describe alternatives you've considered**

- There are no alternatives

**Comment by alexanderAKU** [comment]
- [ ] add reverse action
- [ ] add T_set Input
- [ ] add additional controller

**Comment by PMehrfeld** [comment]
Closed by #676
