### ISSUE TITLE
Chiller Examples in OpenModelica give errors

### ISSUE THREAD

**Issue by dgusain1** [RWTH-EBC/AixLib#678]
Hi!

Simulating any example that contains the chiller model from Fluid library gives the following error:

`Variable chi: Cyclically dependent constants or parameters found in scope Buildings.Fluid.Chillers.Carnot_TEva$chi: {COP_nominal,etaCarnot_nominal} (ignore with -d=ignoreCycles).`

Is this a known problem?

**Comment by dgusain1** [comment]
I already tried giving the -d=ignoreCycles as a flag during Simulation Setup; it doesn't work.

**Comment by PMehrfeld** [comment]
Hi @dgusain1, 

Thanks for letting us know about this issue in OpenModelica.
Unfortunately, I do not know this problem.

Anyway, I must refer to the [IBPSA Library](https://github.com/ibpsa/modelica-ibpsa), from which the model originates. 'AixLib' is one of 4 libraries that merges from time to time the core library (IBPSA Library).

Thus, you should open an issue in that repository.

For further information regarding the former project Annex60, which is continued in Project1, and the IBPSA library, have a look at [our wiki page](https://github.com/RWTH-EBC/AixLib/wiki/AixLib-and-Modelica-IBPSA-Library-(former-Annex-60)).

If you have any further question, just reopen this issue.
