### ISSUE TITLE
Two Radiation HeatToStar models

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#689]
Is there any difference between the two models:

- `AixLib.Utilities.HeatTransfer.HeatToStar`
- `AixLib.Utilities.HeatTransfer.HeatToStar_Avar`

The `_Avar` model seems to still have the old equation, whilst in the first model we tried to compensate negative solutions with max()-function. See here: #535 .

Can we write a conversion script and delete the `_Avar` model?

**Comment by LauraMaier** [comment]
After comparing the mentioned models, I identified one problem: in AixLib.Utilities.HeatTransfer.HeatToStar_Avar the area A is given by an interface whilst in AixLib.Utilities.HeatTransfer.HeatToStar the area is a parameter. Thus, no simple conversion script can be developed. Despite this, the models' functionality is the similar except for the max() function discussed in #535.

I only see four possibilities to solve the issue:
A. AixLib.Utilities.HeatTransfer.HeatToStar_Avar is deleted --> probably effects many models
B. AixLib.Utilities.HeatTransfer.HeatToStar_Avar is deleted and AixLib.Utilities.HeatTransfer.HeatToStar gets an interface for the area A like the old model
C.  AixLib.Utilities.HeatTransfer.HeatToStar_Avar is adapted according to #535 and the new model AixLib.Utilities.HeatTransfer.HeatToStar is deleted --> still effects other models but probably not as many
D. We still keep both models and AixLib.Utilities.HeatTransfer.HeatToStar_Avar is adapted according to #535 

What would you suggest?

**Comment by KremerMartin** [comment]
@LauraMaier What is the current status of this issue? Could it be something for the hackday next week?

**Comment by PMehrfeld** [comment]
@LauraMaier: Although I really don't like almost doubled classes it would be quite annoying for people if one model was deleted. Thus, I think you can go for option D.

**Comment by LauraMaier** [comment]
@PMehrfeld @KremerMartin Ok, this issue will be solved on the Hackday

**Comment by DaJansenGit** [comment]
I will close this, due to the merge of #743. @PMehrfeld

**Comment by DaJansenGit** [comment]
The original HeatToStar model

**Comment by PMehrfeld** [comment]
@DaJansenGit: I think you were right with closing this issue. Or are there any reasons why you reopened the issue again?

**Comment by DaJansenGit** [comment]
@PMehrfeld 
Yes, with #746 we moved `HeatToStar `modell to obsolete package. But some of the internal gains model still use it. E.g.

- AixLib.Utilities.Sources.InternalGains.Lights.LightsAreaSpecific
- AixLib.Utilities.Sources.InternalGains.Lights.Lights_simple
- AixLib.Utilities.Sources.InternalGains.Machines.MachinesAreaSpecific
- AixLib.Utilities.Sources.InternalGains.Machines.Machines_DIN18599
- AixLib.Utilities.Sources.InternalGains.Machines.Machines_simple

Isn't it kind of too complicated to have the area only as an real input? Shouldn't we give the alternative to use a parameter for the area?

**Comment by PMehrfeld** [comment]
Perfect, you are right! :+1:
So we need a conditional input ([wiki page](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Conditional-input-connectors)) to optionally set a parameter instead of a variable input.

**Comment by DaJansenGit** [comment]
Ok, I will finish this later! Thanks for your input :)

**Comment by DaJansenGit** [comment]
closed with #803
