### ISSUE TITLE
HeatPump: Improvements and minor bugs

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#696]
While using the model `AixLib.Fluid.HeatPumps.HeatPump` I came across a few issues with the model and according controller parts:

- [x] Rethink `greaterLow` hysterisis in `AixLib.Controls.HeatPump.SecurityControls.BaseClasses.BoundaryMap` since heat pump should also start even if the evaporator outlet temperature drops below e.g. 10 degC
- [x] TSetToNSet seems to be not propagated properly
- [x] PI controller in `AixLib.Controls.HeatPump.BaseClasses.InverterControlledHP` needs a `yMax=1` and `yMin=0`.
- [x] Add Heating Limit Temperature (with T_oda moving average before) into `AixLib.Controls.HeatPump.BaseClasses.PartialTSetToNSet` and propagate it.
- [x] `Simulate and Plot` script for `Systems.HeatPumpSystem.Examples.HeatPumpSystem` does not show any operation of the heat pump. Must be revised so that more operation points are covered during simulation.
- [x] Just noticed that the scaling factor usage is not implemented for the ND table yet. Fix is provided in #761. Mark as done after merge. - Added by: @DaJansenGit 

~~to be continued...~~

**Comment by DaJansenGit** [comment]
As all tasks are completed I will close this issue for now. It can be reopened at any time.

**Comment by KremerMartin** [comment]
@alexanderAKU What is the current status of this issue? Has the work be done? As your list is completed, maybe we should do a PR.

**Comment by DaJansenGit** [comment]
We should check how we can improve the initial states of the heatpump model, especially for the condensor and evaporator blocks. The capacitys temperatures and der(T) could be improved with the current way @PMehrfeld is modeling the storage covers for the bufferstorage model:
``` 
Modelica.Thermal.HeatTransfer.Components.HeatCapacitor loadWall(
    final C=cWall*rhoWall*AWall*sWall,
    final T(
      stateSelect=StateSelect.always,
      fixed=(energyDynamics == Modelica.Fluid.Types.Dynamics.FixedInitial),
      start=TStartWall),
    final der_T(
      fixed=(energyDynamics == Modelica.Fluid.Types.Dynamics.SteadyStateInitial),
      start=0)) if not (energyDynamics == Modelica.Fluid.Types.Dynamics.SteadyState)
        "Heat capacity of wall"
```

**Comment by DaJansenGit** [comment]
We could improve the model also by 
[ ] make the boolean *modeSet* conditional by the boolean paramater use_rev so that it's not displayed if we have no reversible hp or chiller. We should apply these changes to both, the fluid and fastHVAC model

**Comment by Dawac** [comment]
Hi @PMehrfeld and @DaJansenGit, this might be a good issue to tackle during our upcoming Hackday ;-)

**Comment by DaJansenGit** [comment]
@Dawac Yes, @SvenHinrichs is informerd ;)

**Comment by FWuellhorst** [comment]
To finally resolve this issue, i have to do the following steps:

- [ ] Merge current development into this branch. Changes in this branch were made for the old heat pump model, not the new `PartialReversibleThermalMachine`
- [ ] Fix some annotations in the `PartialReversibleThermalMachine` model, not all are properly set
- [ ] Change parameter N in `ThermalMachineControlBus` to relative `n`. We don't use absolute values in our thermal machine models, and the bus is (aside from the new models) only used in the `AixLib.Fluid.Examples.GeothermalHeatPump.BaseClasses.GeothermalHeatPumpBase` model, which still uses the obsolete `HeatPumpSimple` and is thus outdated. 
```
Modelica.SIunits.Conversions.NonSIunits.AngularVelocity_rpm N "rotational speed compressor"
  annotation (HideResult=false);
```

Do you agree with the changes @PMehrfeld ?

**Comment by PMehrfeld** [comment]
Merged and now in `development`
