### ISSUE TITLE
Adding imgs to wiki

### ISSUE THREAD

**Issue by megatux** [RWTH-EBC/AixLib#699]
**Describe the bug**

Searching how to add images to the GH wiki, found [your page](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Add-images-to-the-Wiki) that says

> you have a better solution for adding images to the Wiki,

I found then [this page](http://mikehadlow.blogspot.com/2014/03/how-to-add-images-to-github-wiki.html) with an alternate method. I think it's the _right_ approach. Just my opinion, 5cents worth.

**Comment by MichaMans** [comment]
@megatux thanks for raising this one!
I [implemented](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Add-images-to-the-Wiki) your suggestion for the _right_ solution, which is indeed a cleaner and permanently guaranteed way

Please close this if you agree with that solution

**Comment by megatux** [comment]
That's great. Regards
