### ISSUE TITLE
HVACComponentsDevelopment

### ISSUE THREAD

**Issue by RoozbehSangi** [RWTH-EBC/AixLib#70]
A branch to develop new HVAC components

**Comment by marcusfuchs** [comment]
@RoozbehSangi: Is this still active?

**Comment by RoozbehSangi** [comment]
No!

Von: marcusfuchs [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. November 2015 15:16
An: RWTH-EBC/AixLib
Cc: Sangi, Roozbeh
Betreff: Re: [AixLib] HVACComponentsDevelopment (#70)


@RoozbehSangi<https://github.com/RoozbehSangi>: Is this still active?
