### ISSUE TITLE
Naming convention "equipped" in ThermalZone

### ISSUE THREAD

**Issue by KremerMartin** [RWTH-EBC/AixLib#707]
**What is the problem?**

There is a difference in the designation of the multi-zone model and the ThermalZone. Using the ThermalZone the suffix "equipped" means, that infiltration (natural, by window and mechanical) is considered. Otherwise no infiltration is considered (not even natural infiltration).
Using the multi-zone model the suffix "equipped" stands for the usage of an air handling unit for ventilation. The multi-zone model uses the ThermalZoneEquipped as default. 

As I see it, the suffix "equipped" is misleading in the ThermalZone-model. In addition to that the non-equipped ThermalZone suggests that ventilation is considered, as it inherits two connectors for the ventilation temperature and the ventilation rate. But the input has no influence on the results.

**How do we want to solve it? Describe the solution you'd like**

Maybe we should consider renaming the ThermalZoneEquipped into a model name more sufficient.

**Describe alternatives you've considered**

I am open to any suggestions. ;)

**Comment by DaJansenGit** [comment]
I agree, we might leave the multizone naming the way it is and change the **thermalZoneEquipped** to something like **thermalZoneAirExchange** ? I don't have a better name in mind. We might also think about move the **ventTemp** and **ventRate** inputs from the **thermalzone** to **thermalzone...**

What do you think about this @PRemmen & @MichaMans

**Comment by MichaMans** [comment]
As possible changes might introduce changes in the TEASER export as @DaJansenGit already said, i'll remove the gfi label.

**Comment by KremerMartin** [comment]
@DaJansenGit @MichaMans @PRemmen 
I would like to tackle this issue again. I think we should solve this issue by the next hackday. I think the name **ThermalZoneAirExchange** describes the function of the equipped ThermalZone well. I also agree with @DaJansenGit  to move the connectors **ventTemp** and **ventRate** to the equipped ThermalZone as they are not used in the non-equipped one.
Do you all agree with this? Then I will carry out the changes on the next hackday. But someone else has to carry out the corresponding changes in TEASER, as I am no expert in TEASER.

**Comment by DaJansenGit** [comment]
For me the name ThermalZoneAirExchange as well as moving **ventTemp** and **ventRate** to the **ThermalZoneEquipped** model is fine. I can do the necessary TEASER changes during the next hackday.

**Comment by KremerMartin** [comment]
@DaJansenGit 
I changed the name of the **ThermalZoneEquipped**. I also moved the RealInputs  **ventTemp** and **ventRate** from the **PartialThermalZone** to the **ThermalZoneAirExchange**.

In your opinion: Shall we merge the branch now or shall we wait till we merge the changes done for issue #690 and #695 as they all influence the **ThermalZone**.

**Comment by PMehrfeld** [comment]
@KremerMartin and @DaJansenGit : Do these name changes actually affect the IBPSA core library since ROM is part of the IBPSA library and not AixLib?

**Comment by DaJansenGit** [comment]
@KremerMartin I agree that we should merge all there PRs together or in straight raw. 
@PMehrfeld No the changes won't effect the IBPSA core, because we are only making changes for the multizone model which is not part of the IBPSA. Only the RC models (FourElements, TwoElements ...) are port of the IBPSA.

**Comment by KremerMartin** [comment]
closed by PR #816
