### ISSUE TITLE
Implementing HVAC from another Library

### ISSUE THREAD

**Issue by atharkamal** [RWTH-EBC/AixLib#71]
Dear AixLib Team,
                             I want to implement a HVAC system from another library inside one of the AixLib 
LowOrderModels. The Chiller model and all the components have flow ports(fluids) involved. Is there a way in which i can implement this by modifying the LowerOrderModel? Something like below but instead of getting the temperature from the temperature sensor.. include the chiller(through the flow ports) inside the building. 
I would really appreciate the help and any ideas regarding this. 

![fluid flow](https://cloud.githubusercontent.com/assets/10814607/7167809/8b226978-e3c9-11e4-8182-3c9e45ce7a58.png)

**Comment by mlauster** [comment]
As far as I see you currently use the outdoor air temperature for your chiller.
Anyway, you can couple a MixingVolume on the convective heat port for internal loads (representing the air node) or directly intgrate this volume into the zone model as in https://github.com/iea-annex60/modelica-annex60/tree/issue94_thermalZone

**Comment by marcusfuchs** [comment]
It seems like we can close this, right?
