### ISSUE TITLE
Enhance unit tests

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixLib#718]
As #697 is closed now and we integrated the unit tests, we can now improve our tests by:

- [ ] Integrate more tests / examples / increase the coverage
- [ ] Integrate some coverage report
- [ ] Rename and restructure the tests @PMehrfeld can provide some suggestions here

--- 

- [ ] Integrate new scripts for model not tested yet
- [ ] generate new results for these models

---

- [ ] integrate all test from modelica-buildings library (maybe jmodelica, html checks etc)
- [ ] Test integration of Antoine of funnel and html statistics in the buildingspy
- [ ] Be aware that unit tests from IBPSA library requires `PedanticModelica` enabled (see [here](https://github.com/ibpsa/modelica-ibpsa/blob/master/bin/runUnitTests.py#L85)).

---

~~@AnaConstantin As you volunteered to increase the test coverage, we can start working and discuss in an branch related to this issue~~

---

Related issues:

- #511 
- #738

**Comment by AnaConstantin** [comment]
@MichaMans I just added a new unit test for AixLib.Airflow.AirCurtain.Examples.AirCurtain. I supposed you build the example in the first place.
And I decided to write a Wiki-Page on how to do this: https://github.com/RWTH-EBC/AixLib/wiki/How-to-write-a-Unit-Test
Take a look and let me know if this is in line with what you envisioned.

**Comment by DaJansenGit** [comment]
some of the points mentioned here were already tackled in #802 . @SvenHinrichs Could you please have a look at this open bullets and move the ones not tackled yet to #802 so we have a cleaner overview. Thanks in advance! This issue can be closed afterwards.

**Comment by MartinRaetz** [comment]
@SvenHinrichs 
Please reopen the issue if you have not yet moved them to #802 and close it afterward.
