### ISSUE TITLE
Import of the Simple heat pump model into a C++ application

### ISSUE THREAD

**Issue by annebierhoff** [RWTH-EBC/AixLib#731]
Hello,

I am currently looking for a simplified heat pump model and came across this library, which may fit very well. First of all many thanks for providing the code.

I would like to embed the example of the _Simple heat pump model_ from _ValidationHeatPump.mo_ into my application. My application is written in c++. I would like to simulate the model from my C++ application with different _onOff_in_ signals for the heat pump (not just a repeating _BooleanPulse_). When it is simulated, I would like to make further calculations on the electrical power _Pel_out_ and the heat power _Q_flow_ of the condenser in my C++ application.

Unfortunately I have no experience with Modelica so far. What is the best way to do this?

**Comment by MichaMans** [comment]
Hi @annebierhoff, thanks for your interest in our library. What come in my mind first is the use of the fmi standard: https://fmi-standard.org/
Meaning you can use the Heatpump model with defined inputs (on off signal in your case) and defined outputs (Pel_out and Q_flow in your case) and translate that to an FMU. This FMU can then be use within your C++ application. I have never done that with C++ , but we already have some experience with this kind of applications and Python.

**Comment by mlauster** [comment]
Here is a list of fmi-libs, including c++ implementations: https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/traversaro/awesome-fmi&ved=2ahUKEwjHucf8j9PiAhXS26QKHejGA7kQFjABegQIBRAB&usg=AOvVaw1k508D-JuPJ2LUrKcyETOE

**Comment by mlauster** [comment]
Sorry, the link was corrupt, has been corrected: https://github.com/traversaro/awesome-fmi

**Comment by LauraMaier** [comment]
Hi @annebierhoff, it seems that your issue can be closed, is that correct?
