### ISSUE TITLE
RT_nom already in K in Record for Radiator

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#734]
**Describe the bug**
In **AixLib.Fluid.HeatExchangers.Radiators.Radiator** line 75
parameter SIunits.Temperature RT_nom[3]=
    (if selectable then Modelica.SIunits.Conversions.from_degC(radiatorType.RT_nom)
    else Modelica.SIunits.Conversions.from_degC({75,65,20})).
However in the record, the temperatures are expressed in K already.

**To Reproduce**
Simulate  AixLib.Fluid.HeatExchangers.Radiators.Examples.Radiator by choosing a record from the list. Check RT_nom values.

**Expected results**
RT_nom values over 300 °C.

**Additional context**
Although it is a bug, it shouldn't have created any problems until now, since the temperatures are 
as far as I know only used to build temperature differences, which are the same in K or °C.

**Comment by LauraMaier** [comment]
Hey @katharinabr maybe this is a good issue for the hackday?

**Comment by katharinabr** [comment]
In `delta_nom=(dT_nom+RT_nom[3])*(dT_nom+RT_nom[3])*(dT_nom+RT_nom[3])*(dT_nom+RT_nom[3])-RT_nom[3]*RT_nom[3]*RT_nom[3]*RT_nom[3];` the temperatures are not used to build temperature differences, but as absolute values. Therefore the simulation results will change.

**Comment by PMehrfeld** [comment]
closed by #741
