### ISSUE TITLE
FastHVAC Heat Pump Enthalpy Port Naming

### ISSUE THREAD

**Issue by Dawac** [RWTH-EBC/AixLib#736]
The naming of the enthalpy ports in the FastHVAC model of the heat pump is not consistent with the naming in it's fluid twin.
At the condenser side it shall be called "a1" and "b1", instead of "a" and "b", on the evaporator side "a2" and "b2" respectively instead of "a1" and "b1".

Quick fix...

**Comment by DaJansenGit** [comment]
The PR is merged into development. I will close this issue now.
