### ISSUE TITLE
Vapor Compression Cycle Package

### ISSUE THREAD

**Issue by cvering** [RWTH-EBC/AixLib#739]
## What is the problem?

Currently, there are no models that allow building modular and scalable heat pump or refrigerating machine models. In this case, modular means different set-ups like two evaporators (and also two expansion valves), a compressor rack or different refrigerants; scalable means different sizes of each component like the heat exchanger area or the swept volume of the compressor. Furthermore, the controllable components (e.g. the compressors and the expansion valve) should have a controller block as an interface that allows either to use an internal component controller or to use an external controller.

## Why do we want to solve it?

We want to solve this issue in order to be able building such models as mentioned before. Those models can be used, for example, to analyse different controlling concepts as well as the effect of different refrigerating media or different heat pump set-ups to the overall efficiency.

## How do we want to solve it?

In order to solve this issue, we will first develop the component models and, afterwards, provide examples of different heat pump and refrigerating machine set-ups. Specifically, we will create and solve the following issues:

1.	_Package Structure:_ We will develop a new structure to condense all models that contain heat pumps or refrigerators. In addition, we propose a structure for all components that are related to vapor compression cycles like compressors, heat exchangers and expansion valves. In this process, we bring the following issues together:
#407 Modular and scalable heat pumps
#467 Compressors for heat pumps
#479 Data bus connectors for heat pumps
#516 Moving boundary heat exchangers for modular heat pumps
#590 Expansion valves for modular heat pumps
#609 Rotating piston compressors fpr modular heat pumps
Lastly, we will discuss to include
#696 HeatPump: Improvements
in this package. 
2.	_Compressors:_ We will add different types of compressors (e.g. a scroll compressor and a turbo compressor, piston compressors). These will have variable rotational speed and, therefore, will be controllable. They base on two approaches: On the one hand, a semi-emperical approach based on literature data. On the other hand, we use a detailed physical approach.
3.	_Heat Exchangers:_ We will add two different types of heat exchangers (e.g. a plate heat exchanger and properly a finned tube heat exchanger). These heat exchangers shall be able to operate in different modes like concurrent-, counter-current and cross-current. Moreover, the heat exchangers shall be able to describe the evaporation and condensation of the refrigerant media. The approaches are finite volumes and moving boundary.
4.	_Expansion valve:_ We will add an expansion valve that is controllable since its opening degree will be variable. We use emperical approaches and a grey box approach including meta stability coefficients to improve bernoulli equation.
5.	_Controller block:_ We will add a controller block that can be used with the compressors or the expansion valve. This controller block will provide different internal controllers (e.g. a simple hysteresis as well as a PID controller). Moreover, it will be possible to provide an external controller.
6.	_Example systems:_ We will add some example models (e.g. heat pumps and refrigerating machines) to show the modular and scalable concept as well as to show the use of the controller block.

In general, we will try to focus the simulation speed while modelling the components because it should be able to use the heat pumps and refrigerating machines within larger systems. Moreover, the models mentioned before will be developed during different master thesis that is supervised by cvering. 

## Who do we think will benefit from our solution?

We think that everyone will benefit from our solution who wants to model controllable heat pumps and refrigerating machines and who wants to model the refrigerant circuit.

**Comment by KremerMartin** [comment]
@cvering What is the current status of this issue? I will set the milestone to v0.9.0. Do you think this is realistic?

**Comment by cvering** [comment]
We are integrating our refrigerant model in ibpsa library with prio one. Define realistic! This is an ongoing project for the next two to three years :)

**Comment by MartinRaetz** [comment]
@cvering 
Is there active development? If yes, feel free to undo the stale label.
Looking forward to the improvements!

**Comment by DaJansenGit** [comment]
As there is no branch to this and the VC lib is already integrated into dev I will close this issue now. If you disagree @FWuellhorst or @cvering please reopen.
