### ISSUE TITLE
Move models to package `Obsolete`

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#746]
**What is the problem?**

- Old models that are actually obsolete but might still be in use by other libraries cannot be deleted.

**How do we want to solve it? Describe the solution you'd like**

- Move these models to the new top level package `Obsolete`.
- `IBPSA` library recently introduced such a package as well.
- Wait for next IBPSA merge into AixLib (see #740)

The following models with used BaseClasses such as `CycleHP` will be moved to `Obsolete`:

- [x] `AixLib.Fluid.HeatPumps.HeatPumpDetailed`
- [x] `AixLib.Fluid.HeatPumps.HeatPumpSimple`
- [x] `AixLib.Utilities.HeatTransfer.HeatToStar`

Further ToDos:

- [x] Use annotation flag for obsolete models

**Comment by DaJansenGit** [comment]
@PMehrfeld  
just found that there is an annotation flag for obsolete models, I don't know if you are aware of but I think this could be useful 
This docu can be found [here].(https://doc.modelica.org/ModelicaReference%203.2.3/Resources/helpDymola/ModelicaReference_Annotations.html#ModelicaReference.Annotations.obsolete)

**Comment by DaJansenGit** [comment]
the requested changes were done with 1f1bc5f, so I will close this issue.
