### ISSUE TITLE
Fixed port heights in BufferStorage model

### ISSUE THREAD

**Issue by LauraMaier** [RWTH-EBC/AixLib#747]
**What is the problem?**
In model AixLib.Fluid.Storage.BufferStorage the fluid port heights of fluidportTop1 and fluidportTop2 as well as fluidportBottom1 and fluidportBottom2 are parameterized using two parameters only. So the heights are always dependend on each other.
In practice, however, ports´ height can differ.

**How do we want to solve it?**
A new record of type BufferStorageBaseDataDefinition has to be implemented including two more parameters for port heights. In addition, these new heights have to be integrated in the current calculation methods (like connection of ports, etc.).

**Comment by PMehrfeld** [comment]
@LauraMaier : Sounds good!  
But is it necessary to create a new `BufferStorageBaseDataDefinition`? Or is it possible to add 2 new parameters that might have default values so that no changes occur in comparison to current usage of the record / storage model?!

**Comment by KremerMartin** [comment]
@LauraMaier @arnoldfuetterer What is the current status of this issue? Could this be solved on the Hackday next week?

**Comment by arnoldfuetterer** [comment]
@KremerMartin the problem itself is solved. There are some conflicting files in the pull request. This shall be solved next week.

**Comment by PMehrfeld** [comment]
Closed by #762
