### ISSUE TITLE
Use wall record directly in `AixLib.ThermalZones.HighOrder.Components.Walls.BaseClasses.SimpleNLayer`

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#752]
**What is the problem?**

- [x] Distinguishing between selectable record and single parameters is not necessary
- [x] if-else nesting due to TIR and TMC in HOM model is not necessary. Use Record with wall types would be beneficial

**How do we want to solve it? Describe the solution you'd like**

- [x] Delete `selectable` in `AixLib.ThermalZones.HighOrder.Components.Walls.BaseClasses.SimpleNLayer` and according models
- [x] correct if-else nesting in HOM building and introduce a collection of wall types instead. Use if-else only on building level to select the record, which contains multiple wall records.

**Further tasks**

- [x] Create `PartialRoom` model
- [x] Compare changes to reference results
- [x] Create (old) reference results and merge branch [`issue752_createHOMRefResults`](https://github.com/RWTH-EBC/AixLib/tree/issue752_createHOMRefResults) as soon as #893 is merged into `development`

**Comment by PMehrfeld** [comment]
- [ ] conversion script

- [ ] current branch `issue752_temp_wallRecords` is temporary and only a first quick and dirty solution. This branch needs to be revised or development must happen in new branch and this one should be deleted.

**Comment by KremerMartin** [comment]
@PMehrfeld Are there updates on this issue? Could this be solved on the Hackday next week?

**Comment by PMehrfeld** [comment]
@KremerMartin: Will probably be solved in an upcoming student thesis

**Comment by PMehrfeld** [comment]
Added documentation to new record that contains multiple wall types as record:
![image](https://user-images.githubusercontent.com/11769433/72081155-45a8e500-32fe-11ea-99d5-eef655d13274.png)

**Comment by PMehrfeld** [comment]
- [ ] Cover value of infiltration rate on building level:

```Modelica
  parameter Real n50(unit="h-1") = if TIR == 1 or TIR == 2 then 3 else if TIR ==
    3 then 4 else 6 "Air exchange rate at 50 Pa pressure difference"
    annotation (Dialog(tab="Infiltration"));
```

**Comment by PMehrfeld** [comment]
Quick overview of allocation of "simple" and "load" inner wall (IW)

![image](https://user-images.githubusercontent.com/11769433/79746299-0d0ba500-830a-11ea-8beb-e9a1f357158c.png)

**Comment by PMehrfeld** [comment]
# Comparison of old an new results

## Reference results before comprehensive changes (commit e6fc5218bedea4bce4d3ad3a3876a6478d659159)
![image](https://user-images.githubusercontent.com/11769433/80281489-cfdd5380-870b-11ea-9b14-b26d63d0da0a.png)

## New results after comprehensive changes in this issue (commit 35f85da87bfe2b790eafeb7b86f52fa2f864e23d)
![image](https://user-images.githubusercontent.com/11769433/80281525-05823c80-870c-11ea-9dc3-03501879ccfc.png)


In steady state the results are almost similar.
Minor difference are due to not keeping the exact measure. E. g. like in the ground floor: `parameter Modelica.SIunits.Length length1=if TIR == 1 then 3.23 else 3.34` became just `parameter Modelica.SIunits.Length length1=3.3`.
