### ISSUE TITLE
Version of Modelica_Synchronous

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#759]
**Describe the bug**
Most recent version of Modelica_Sychnronous is 0.92.2, AixLib Development Branch uses 0.92.1

**To Reproduce**
1. Load AixLib development with Dymola 2020

**Expected behavior**
No Library Conversion

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8124013/63155670-51c09d00-c013-11e9-8f1f-d077c7acb154.png)

**Desktop (please complete the following information):**
 - Dymola 2020

**Comment by PMehrfeld** [comment]
Going to be solved in #760

**Comment by PMehrfeld** [comment]
Since conflicts could not be solved for merge `master` -> `development` I raised in both `package.mo`s the version numbers of the used libraries. 
If problem is not solved, please reopen issue @PRemmen
