### ISSUE TITLE
OpenModelica which version supports the Examples provided in AixLib/ThermalZones/ReducedOrder/MultizoneEquipped

### ISSUE THREAD

**Issue by AmeCode** [RWTH-EBC/AixLib#766]
Hi I want to run the examples provided with AixLib (especially the MultizoneEquipped example),  because I am currently working on my bachelor thesis and I need to work with AixLib library, but I keep getting errors and warnings when running the provided examples. How can I run those provided examples and which versions of AixLib, Modelica (OpenModelica) should I use? If those examples do not run in OpenModelica, can you tell me how to run them in Dymola or any other simulation environment (and please tell me the simulation settings), because I keep getting errors in all simulation environments, which I have tried until now.
You will find screenshots for OpenModelica and Dymola, when I click on simulate for the example provided in: AixLib/ThermalZones/ReducedOrder/MultizoneEquipped
1-Using OpenModelica(1.14.0dev) with AixLib 0.7.3 and modelica 3.2.2 upon clicking on simulate ,I get the follwing:
[https://photos.app.goo.gl/9ZFiRuLA7tzMuJ4Y6](https://photos.app.goo.gl/9ZFiRuLA7tzMuJ4Y6)
and the logs:
[https://docs.google.com/document/d/1qnugdcCK2LyTbJRTkkLqig-JSJvT2ntbTA0gRElENe4/edit?usp=sharing](https://docs.google.com/document/d/1qnugdcCK2LyTbJRTkkLqig-JSJvT2ntbTA0gRElENe4/edit?usp=sharing)
2-Using Dymola (2018 64-bit) with AixLib 0.7.3 and modelica 3.2.2 upon clicking on check > with simulation, I get the following:
[https://photos.app.goo.gl/RG37dMcy2ETp6XUA9](https://photos.app.goo.gl/RG37dMcy2ETp6XUA9)
and the logs:
[https://docs.google.com/document/d/1C4XiiyZv69yi8bvYL5dx7arLKGRb8mdt4AQ54FPmWII/edit?usp=sharing](https://docs.google.com/document/d/1C4XiiyZv69yi8bvYL5dx7arLKGRb8mdt4AQ54FPmWII/edit?usp=sharing)
3- Using Wolfram SystemModeler 12.0 with AixLib 0.73 and modelica 3.2.3 upon clicking on validate class, I get the following:
[https://photos.app.goo.gl/5Aqrx6qaq1kfm7Rb9](https://photos.app.goo.gl/5Aqrx6qaq1kfm7Rb9)
and the logs:
[https://docs.google.com/document/d/1T4FxFMRdW7ERJAGGfX3enDvNoR7XIZCs5MYSTzhtq-E/edit?usp=sharing](https://docs.google.com/document/d/1T4FxFMRdW7ERJAGGfX3enDvNoR7XIZCs5MYSTzhtq-E/edit?usp=sharing)
Please if you manage to run the example in AixLib/ThermalZones/ReducedOrder/MultizoneEquipped with any simulation version, provide me with the version recommended and the required steps for a a successful simulation.
Greetings,
Ahmed Amer

**Comment by mlauster** [comment]
Hey @AmeCode,
Regarding OpenModelica, I need to check the errors on my installation, looks like they could be solved. But I so far never managed to get them running in OpenModelica, finally to an issue with the weather data reader that did not yet appear in your log. But this simply might be because the other issues are blocking this error message. :-)
Regarding Dymola, you need to check your AixLib installation and paths, Dymola couldn't find the weather file, although on master, it's definitely there. You could simply put the weather file somewhere else 
Regarding wolfram, this is definitely to a limitation regarding state machines, they might not be covered in Wolfram. So I don't think you could run the example there. 
So to conclude, go for Dymola and fix the weather file issue.

**Comment by AmeCode** [comment]
Thanks @mlauster for your quick reply. If you managed to get the models work on OpenModelica let me please know, because it is the only open source software with a good GUI I could use find far and I still do not have licence to Dymola.

**Comment by AmeCode** [comment]
Thanks @mlauster for your quick reply. If you managed to get the models work with OpenModelica, let me please know, as it is the only free licence software I could use so far and I still do not have a licence to Dymola

**Comment by AmeCode** [comment]
I changed to Dymola and fixed the weather file and it had worked without errors

**Comment by MichaMans** [comment]
@AmeCode ok perfect! If we have some spare Time, we'll definitely look into OM support.

**Comment by mlauster** [comment]
OM Support is a tough cookie, seems to be unsupported features (or too weak implementation of the model? ) of the IBPSA weather data reader. The problem gets better when activating some hidden flags, but still not solved.
