### ISSUE TITLE
Improved CHP model for FastHVAC

### ISSUE THREAD

**Issue by Dawac** [RWTH-EBC/AixLib#779]
The branches AixLib/tree/issue309_HeatGeneratorsNew and AixLib/tree/B13_integration contain improved CHP models for the FastHVAC. There are models for internal combustion engines as well as PEM fuel cells.
The existing models should be checked and tested and the fully operational models should be prepared for a merge into development.

**Comment by DaJansenGit** [comment]
Please have a look at #674 

And it seems like the slew rate limiters where removed in a different branch in this commit: 8a8b138c0e86e3f503fea9fc8bba4c23d49dab1b, please have a look at this too.
