### ISSUE TITLE
Clean up of low order models

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#78]
- [ ]  delete unnecessary models
  - EqAirTempSimple
  - ReducedOrderModelStar
- [x] delete name affix EBCMod
- [ ] rename the parameters to be uniform
  - EqAirTemp package
  - ReducedOrderModel package
  - SolarRadWeightedSum
  - ThermalZonePhysics
  - ThermalZone
  - ZoneBaseRecord
- [x] make ReducedOrderModel replaceable, implement choice in higher level models and change default reduced order model in ThermalZonePhysics to the one with decoupled RWin
- [ ] clean up ZoneBaseRecord
  - No default values
  - clean up white spaces
  - delete old, unused parameter
- [x] implement choice between CorrG and NoCorrG for higher level models

**Comment by mlauster** [comment]
Tasks 1,3 and 5 will be obsolete when we merge the Annex60 ROM's into AixLib. This will be done a soon as these models are ready.

**Comment by mlauster** [comment]
Point five "clean up ZoneBaseRecord" has been partly solved with #140, deleting default values is still open. This will be open after merge of Annex models.
