### ISSUE TITLE
CI Tests fail for some models

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#781]
Some tests currently fail after the newest IBPSA merge, like [here](https://git.rwth-aachen.de/EBC/EBC_all/github_ci/AixLib/pipelines/193967) due to divation from reference results.

First @MichaMans and me thought this was due to the [update from reference results](https://github.com/ibpsa/modelica-ibpsa/issues/1190) in the IBPSA to dymola 2020 

But even after using the dymola 2020 container the deviation changes but is still there, this can be seen [here](https://git.rwth-aachen.de/david.jansen1/AixLib/pipelines/193947)

I simulated one of the failing thermalzone examples locally, both with dymola 2020 and the deviation is still there, I used the same solver with same tolerances. The screenshot shows the timestamp with the highest deviation recording to the regression test.

![image](https://user-images.githubusercontent.com/27726960/66819052-921e9780-ef3e-11e9-8f97-b67f66be1d28.png)

@MichaMans @PMehrfeld do you have any idea where this deviation comes from?

**Comment by MichaMans** [comment]
@DaJansenGit I have no idea where the deviations come from. The marked area/time at comparison is the time with the highest deviation? If so, we should maybe check:
- if we are still in the VDI 6007 deviation range
- why the check does not fail in the ibpsa --> open a discussion branch there?
- check again if the reference results from the ibpsa and our are 100% the same

**Comment by DaJansenGit** [comment]
I updated the screenshot, it shows now the timestamp of the highest deviation. 
* I will check the VDI6007 range
* I will open an discussion branch in IBPSA
* the reference results are 100 % the same, I checked this already

**Comment by mlauster** [comment]
I can't check your example results, since they ate not accessible for external, but the VDI range is 0.1 K for hourly means.

**Comment by DaJansenGit** [comment]
We solved this issue with:
* a new merge of the current master
* the usage of dymola 2020 container
* the creation of a new CI server with better performance

Thanks for you effort.
