### ISSUE TITLE
AHU with hydraulic modules

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#784]
**What is the problem?**

There are no generic ahu models that is based on fluid in order to simulate the dynamic behavior (e.g. delays, dead times) of the heating/cooling registers of the ahu.
However, these effects have to be considered for controller testing and development.

**How do we want to solve it?**

- Create an ahu model that includes the hydraulic modules for air ahu (see #677)

**Additional context**

This issue is the extension of issue #677

**Comment by alexanderAKU** [comment]
Tasks:

- [ ] create model and include ahu register modules
- [ ] define control bus
- [ ] implement simple controller
- [ ] example

**Comment by Dawac** [comment]
Hi @alexanderAKU , would this be an issue to finish on our upcoming hackday?

**Comment by MartinRaetz** [comment]
@alexanderAKU 
Is there a status update?
Should this issue remain active?

**Comment by alexanderAKU** [comment]
merged

**Comment by alexanderAKU** [comment]
reopened due to bug in CI

**Comment by alexanderAKU** [comment]
merged again
