### ISSUE TITLE
QEva_nominal is protected in HeatPumpSystemParameters

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#791]
**What is the problem?**

In class `AixLib.Systems.HeatPumpSystems.BaseClasses.HeatPumpSystemParameters` the parameter  `QEva_nominal` is protected and, thus, it should not be accessed from outside the class. However, this would be beneficial in some cases.

**How do we want to solve it? Describe the solution you'd like**

Change the parameter to a `final` one.

**Comment by Dawac** [comment]
Hi @PMehrfeld , this issue seems to be solved with your pull request #792. Can we close it?

**Comment by PMehrfeld** [comment]
Thanks for reminding @Dawac
