### ISSUE TITLE
Correct BufferStorage initialization of energyDynamics

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#793]
**What is the problem?**

In e.g. `AixLib.Fluid.Storage.BaseClasses.StorageCover` values for `TStartWall` and `TStartIns` exists but they are not used.

**How do we want to solve it? Describe the solution you'd like**

Parse the start values to the capacities and implement correct usage of `energyDynamics`.

**Comment by PMehrfeld** [comment]
- [ ] Delete `AixLib.Fluid.Storage.BaseClasses.StorageWall` as soon as the `Obsolete` top level package exists, since the model is nowhere used.

**Comment by PMehrfeld** [comment]
- `PlugFlowPipe` implemented. Comparsion between old and revised buffer storage (tested with new example model):
![image](https://user-images.githubusercontent.com/11769433/67669560-6f46a700-f972-11e9-8793-5db4c6bb51bd.png)

- **Pressure drop** at heating coil:
![image](https://user-images.githubusercontent.com/11769433/67669609-8c7b7580-f972-11e9-9bd1-12f7bec2e5d5.png)

- **Heat flow** transferred through heating coil:
![image](https://user-images.githubusercontent.com/11769433/67669670-aa48da80-f972-11e9-8e10-b5f2668c9ca4.png)

- **Temperature** in one layer:
![image](https://user-images.githubusercontent.com/11769433/67669747-c9476c80-f972-11e9-94e1-291943e632da.png)


As we can see, there are some changes in pressure drop as well as transferred heat flow. However, since all deviations are within a range smaller than 4 %, I suggest to apply the `PlugFlowPipe` model.

**Comment by PMehrfeld** [comment]
Furthermore, I added the `non-backward compatible`, which I introduced in analogy to IBPSA library.
The changes in this issue cannot be covered by an conversion script, since e.g. the discretization between the old pipe model and the new one is implemented in a different way.

**Comment by Dawac** [comment]
Hi @PMehrfeld , is this an issue which might be solved on our upcoming Hackday?

**Comment by PMehrfeld** [comment]
This issue waits only for review by @alexanderAKU in #800.
