### ISSUE TITLE
Add CO2 Concentration to Reduced Order Model

### ISSUE THREAD

**Issue by ErvinLejlic** [RWTH-EBC/AixLib#797]
**What is the problem?**

Our Project is about adding a CO2 concentration to the ReducedOrder Model.

**How do we want to solve it? Describe the solution you'd like**

We work with trace substances to calculate the CO2 concentration over time in the zone.
We want to add a connector use_C_flow to Indoor Air to calculate the CO2 concentration.

**Describe alternatives you've considered**

We first tried to work with the fluid ports but we decided to work with real connectors to keep it simple.

**Comment by KremerMartin** [comment]
@ErvinLejlic Thanks for your issue. 
Please keep in mind, that providing changes to the Reduced Order Models (OneElement, TwoElement) will lead to merge conflicts with the IBPSA.
The RC-models are derived from the [IBPSA](https://github.com/ibpsa/modelica-ibpsa)-library. Hence, if you do modifications on these models, you will need to provide your changes as well to the IPBSA. If you've got questions on that, you can ask @MartinRaetz , @katharinabr or me.

**Comment by MartinRaetz** [comment]
This Issue is connected with the branch: 
https://github.com/RWTH-EBC/AixLib/tree/issue797_AddCO2ConcentrationToROM

We have finished the clean up. Several models were merged to one model.
After we have the feedback/merge from the IBPSA, we can merge this branch to the AixLib.

ToDo:
[ ] Check for model view, several new merged branches use the space we use as well.

**Comment by MartinRaetz** [comment]
@katharinabr 
Got the renaming from moist to moist_co2 reversed or is it that we just didn´t do it yet?
In the commits from the hackday it seems that we did not do it yet.
[Commit of hackday](https://github.com/RWTH-EBC/AixLib/commit/f95809a117d8f406d424bac45f7cc75dd1b05b9c)
With the renaming we have to document it accordingly.

**Comment by katharinabr** [comment]
We have to differentiate between the naming in the example and the ROM model. In the example it must be MoistCo2 and in OneElement moist and c_flow must be used (as in [IBPSA #1275](https://github.com/ibpsa/modelica-ibpsa/issues/1275). I am working on it and will let you know as soon as I am done.

**Comment by MartinRaetz** [comment]
Missing checkboxes:
- CI unit test
- implementation to Teaser

**Comment by MartinRaetz** [comment]
Branch for the adding the UnitTest: 
https://github.com/RWTH-EBC/AixLib/tree/issue797_add_unit_test_co2_model

Work it out, or wait for the automatic unit test creation.

- [ ] Delete https://github.com/RWTH-EBC/AixLib/tree/issue797_add_unit_test_co2_model

**Comment by FWuellhorst** [comment]
@MartinRaetz What is the status of this issue? Can i solve it in the upcoming hackday?

**Comment by MartinRaetz** [comment]
@FWuellhorst: Only the Unit-Tests are missing to close this issue.
I was also planning to solve it in the next hackday, but you are invited to support me. My expertise with unit tests is very low.

**Comment by FWuellhorst** [comment]
Same here, but as it relates to my current project I'm happy to support!

**Comment by FWuellhorst** [comment]
@MartinRaetz : It seems like the unit tests won't work with the current example. All written examples are using the ThermalZone Model and thus the `zoneParam` record. However, this leads (in all Examples) to the following warning (I turned on pedantic mode so their errors now):
![grafik](https://user-images.githubusercontent.com/22442514/105822773-bb8cf680-5fbc-11eb-8564-6fa0c9cc3c19.png)

While I'm happy to solve this issue, it seems like it's a bug introduced in other branches.
Afflicted examples:
```
ComparisonThermalZoneMoistAndDryAir
Multizone
MultizoneEquipped
MultizoneMoistAirCO2
MultizoneMoistAirCO2Equipped
MultizonePartlyCooled
ThermalZone
ThermalZoneAirExchange
ThermalZoneMoistAir
ThermalZoneMoistCO2AirExchange
```
Did someone already tackle this issue?

**Comment by MartinRaetz** [comment]
@FWuellhorst: Thank you for proceeding! I don´t know of anyone tackling this issue. My first thought was, that the zoneParam do not need to be evaluated by the unit test, do they? Are you trying to evaluate them, or does this error occure anyways?

**Comment by FWuellhorst** [comment]
Nevermind, it works with the warnings present. 
I added the reference results for the two CO2 examples :)

**Comment by MartinRaetz** [comment]
Closed by: https://github.com/RWTH-EBC/AixLib/pull/1070
