### ISSUE TITLE
Improve SimpleConsumer

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#799]
**What is the problem?**

- The model SimpleConsumer contains a volume with convection to a fixed temperature. It would be benificial to have more options, e.g. predescribed heatflow or varianle temperature, thus, this model could be used for several applications

**How do we want to solve it? Describe the solution you'd like**

- Add options to select between internal fixed temperature, external temperature, internal fixed heatflow, external fixed heatflow.

**Comment by Dawac** [comment]
@alexanderAKU this seems to be a good issue to be solved at our upcoming Hackday ;-)

**Comment by alexanderAKU** [comment]
Remove plugFlowPipe in simple consumer, because it can lead to high computation times in large scale systems. Since the simpleConsumer can e.g. be used with the hydraulic modules, the inflow and outflow pipes are already included.
