### ISSUE TITLE
Mixing Volume mass flow

### ISSUE THREAD

**Issue by atharkamal** [RWTH-EBC/AixLib#81]
Below is a chiller model  that i am trying to run.
 The basic assumption from the literature that i have read and understood after reading the mixing volume component is that "the cooling liquid that comes through the coocoi1(heat exchanger) interacts dynamically with the building model, this new liquid replaces the present volume from port.a inside the building model and then goes out through the second port.b " . I assume this suggests that the liquid properties work in cooling the building(act like airducts to cool building temperature). Is this assumption correct? if it is, why isn't the building temperature decreasing? 

The block diagram is hopefully helpful if you can't understand my question. 

![block diagram](https://cloud.githubusercontent.com/assets/10814607/7899386/dce9d88c-0731-11e5-89f7-01173a12d505.png)

If not, can you suggest on how i can create a dynamic model, where the chiller cools the building temperature to a certain temperature( here 24 degrees Celsius). 

![hvac mass](https://cloud.githubusercontent.com/assets/10814607/7899318/94614250-072f-11e5-87df-e26d6f8621c1.png)

**Comment by mlauster** [comment]
Since there is no discussion going on, I will close this issue.
