### ISSUE TITLE
Incopressible Air Medium

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#830]
**What is the problem?**

- The air models in the AixLib and MSL are compressible. This can lead to a high computational effort especially in air duct networks due to small pressure impulses.

**How do we want to solve it? Describe the solution you'd like**

- An incompressible air medium would improve te computational speed. However, this model would only be suitable for small pressure and temperature changes (e.g. in air ducts for room ventilation).

**Comment by KremerMartin** [comment]
Closed by PR #840
