### ISSUE TITLE
PassThroughMedium should extend differently

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#833]
**What is the problem?**

`AixLib.Fluid.Interfaces.PassThroughMedium` extends from `PartialTwoPortInterface`. 
In `PartialTwoPortInterface` the start values for m_flow and dp are set to 0 in the protected section.

**How do we want to solve it? Describe the solution you'd like**

Extend from `PartialTwoPort`.

- [x] With a conversion script one should take care of `m_flow_nominal` and `show_T`.

@FWuellhorst: Was there any reason you remember, why you extended from `PartialTwoPortInterface`?

**Comment by FWuellhorst** [comment]
Looking at the commit message, no. If this affects any model, the regression-tests will tell.
However i'd assume this won't affect anything.
