### ISSUE TITLE
Naming in VarAirExchange

### ISSUE THREAD

**Issue by KremerMartin** [RWTH-EBC/AixLib#850]
The model `VarAirExchange` contains a `RealInput` that is defined as `InPort`. This is not very explaining. Moreover there is missing som documentation to this input.

It would be wise to change the name from `InPort` to `ventRate` and add some documentation. Moreover a conversion script will be needed.

**Comment by PMehrfeld** [comment]
Good point @KremerMartin. Additionally, you might cover this is well:

- [ ] Add unit for new `ventRate` port (unit="1/h")
- [ ]  I assume you need to create a (protected) constant for unit conversion like `constant Real hToS(unit="s/h") = 3600` and replace this with the `3600` in the equation.

**Comment by KremerMartin** [comment]
@PMehrfeld Thanks for that advise, i will consider it, and proms to @PRemmen , since he discovered this during his review on our LOM-issue. ;)

**Comment by KremerMartin** [comment]
@XucYin You are right. I have set this on my list for the hackday. :)

**Comment by KremerMartin** [comment]
closed by PR #1034
