### ISSUE TITLE
Move class to Obsolete package

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#865]
Move `AixLib.Fluid.HeatPumps.BaseClasses.CycleHP` to `Obsolete` package.

- [ ] Consider how to steps in the documentation of the `Obsolete` package.
- [ ] Add conversion script
- [ ] Raise AixLib version number

**Comment by konstantinaxanthopoulou** [comment]
trying working on this issue

**Comment by konstantinaxanthopoulou** [comment]
I'm working on this issue
