### ISSUE TITLE
Style Check of Modelica Models

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#869]
What is the problem?

At this time the models are not up to date to pass the tests StyleCheck successfully. Therefore the tests are only applied to new models in the short term to ensure that the styles are correct and correspond to the settings.

In the future, the models that fail the test will have to be revised and adapted.

**Comment by PMehrfeld** [comment]
@SvenHinrichs: Thanks for opening the issue!  
I assigned @DaJansenGit and myself to keep track of this.  
Additionally, I set a Label and Milestone.

**Comment by DaJansenGit** [comment]
@SvenHinrichs this is already included in development with #802, right? If yes we can close this :)

**Comment by PMehrfeld** [comment]
@SvenHinrichs: Any update regarding DaJansenGit's question?

**Comment by SvenHinrichs** [comment]
@PMehrfeld : Yes, this stage is allowed to fail. The best thing to do is to consider how much we want to follow the guidelines of the Style Check of ModelManagement and to adapt our models to these guidelines, also considering with the models of the IBPSA Library.

**Comment by PMehrfeld** [comment]
Okay thanks. I think we can close this issue for now.
