### ISSUE TITLE
issue876_warningsonconnector

### ISSUE THREAD

**Issue by konstantinaxanthopoulou** [RWTH-EBC/AixLib#876]
What is the problem?
When simulating the code I get this message 

1. Got to AixLib.ThermalZones.HighOrder.Validation.ASHRAE140.Case620

![grafik](https://user-images.githubusercontent.com/62007409/76500029-1cace980-6440-11ea-926f-3ff1b57ce11c.png)

![grafik](https://user-images.githubusercontent.com/62007409/76501110-fb4cfd00-6441-11ea-9c58-6d7e50e38919.png)

**Comment by PMehrfeld** [comment]
@konstantinaxanthopoulou: Thanks for opening this issue.  
You are absolutely right. Unfortunately, these test cases are not in our CI unit tests so far. This is the reason why the error is not thrown in our automated tests.

One solution is to select in the parameter window of `idealHeaterCooler` the value `Record` for `recOrSep` for a moment. Then select any record for the `zoneParam` (it is only a dummy). Then switch the parameter `recOrSep` back to `Seperate`. Click OK.

This is not the desired solution. I will continue looking for a smarter solution.

**Comment by konstantinaxanthopoulou** [comment]
@PMehrfeld 
Thanks! It works with the suggested changes.

**Comment by PMehrfeld** [comment]
Solved in #800  
Now in `development`
