### ISSUE TITLE
Error using system library AixLib in OpenModelica 1.14.1

### ISSUE THREAD

**Issue by jwalbrunn** [RWTH-EBC/AixLib#888]
### Describe the bug
I've got a problem using the System Library "AixLib" under OpenModelica 1.14.1 and I don't know if it's me, the library or OpenModelica :/

### To Reproduce
1. Working with AixLib 0.7.3 in OpenModelica 1.13.2
- works fine
- I'm able to simulate examples and build own models

2.  Working with AixLib 0.9.1 in OpenModelica 1.13.2
- works fine
- I'm able to simulate examples and build own models

3. Working with AixLib 0.7.3 in OpenModelica 1.14.1
- error
- pictures look diffrent
- connectors are missing
- formulas are missing

4. Working with AixLib 0.9.1 in OpenModelica 1.14.1
- error
- pictures look diffrent
- connectors are missing
- formulas are missing

###Screenshots
![LoadLibrary](https://user-images.githubusercontent.com/63235928/78551029-5980bc00-7805-11ea-9e20-9397e7c83bfd.PNG)
- Picture to Step 1
![01_OME13_2_AixLib_073](https://user-images.githubusercontent.com/63235928/78551027-58e82580-7805-11ea-9e78-e45cec7611e7.PNG)
- Picture to Step 2
![02_OME13_2_AixLib_091](https://user-images.githubusercontent.com/63235928/78551036-5ab1e900-7805-11ea-94d7-0cd539eecf63.PNG)
- Picture to Step 3
![03_OME14_1_AixLib_073](https://user-images.githubusercontent.com/63235928/78551035-5ab1e900-7805-11ea-8a3b-1331293654ec.PNG)
- Picture to Step 4
![04_OME14_1_AixLib_091](https://user-images.githubusercontent.com/63235928/78551032-5a195280-7805-11ea-821b-258a67556fc2.PNG)

### Additional context
I also tried OpenModelica 1.15 without success
Has anyone an idea what I'm doing wrong or how to fix this problem?

**Comment by jwalbrunn** [comment]
Hi there,

The fault is more or less with me. I got this answer from the OpenModelica-Support:

OpenModelica 1.14.1 and up has the new frontend on by default for both OMEdit API and code generation.

To remove the usage of the new frontend for OMEdit API do:
    OMEdit->Tools->Options->Simulation
    unclick: Enable new frontend use the OMC API (faster GUI response)

If you have issues with model compilation, you can use the old frontend for that as well (might work better or not)
    OMEdit->Tools->Options->Simulation
    click: Enable old frontend for code generation

**Comment by PMehrfeld** [comment]
@jwalbrunn: Good to hear that the issue could be solved by changing OM settings.

I assume this solved all the problems. If this is not the case, please feel free to reopen this issue.
