### ISSUE TITLE
HOM: Interior distribution solar fractions

### ISSUE THREAD

**Issue by konstantinaxanthopoulou** [RWTH-EBC/AixLib#896]
**What is the problem?**
The solar radiation transmitted through a window is then distributed on the different surfaces in the room, depending on the interior shortwave absorptance and the window orientation.
Currently the AixLib only differentiates between vertical walls, ceeling and roof.

**How do we want to solve it? Describe the solution you'd like**
Differenciate between the different orientations of the windows and walls.

**Comment by PMehrfeld** [comment]
Solved in PR #897
