### ISSUE TITLE
Minor changes in package CorrectionSolarGain

### ISSUE THREAD

**Issue by konstantinaxanthopoulou** [RWTH-EBC/AixLib#899]
### Describe the bug
Currectly the transmitted solar radiation using model AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.CorG_VDI6007 is multiplied with g the coefficient of solar energy transmission. The already transmitted radiation does not need to be decreased by g.

### To Reproduce
    1.Go to 'AixLib.ThermalZones.HighOrder.Components.WindowsDoors'
    2.Click on 'Window'
    3.Click on 'Ag'
    See error

### Screenshots
![grafik](https://user-images.githubusercontent.com/62007409/80072469-8e4f7b80-8546-11ea-8bd5-ae0a2e2e1ae6.png)

### Approach to solve issue
  Remove `g` from `Ag` in Windows.
  Add `g` to model `noCorG`, to multiply incoming radiation with coefficient of solar enggy transmission if no model for correcting the solar factor is used.

**Comment by PMehrfeld** [comment]
Solved in #889
