### ISSUE TITLE
Extend FlowMachineInterface to allow polynomial performance curves

### ISSUE THREAD

**Issue by PhOstmann** [RWTH-EBC/AixLib#909]
**What is the problem?**

Right now the FlowMachineInterface model only allows the specification of one characteristic speed line. This means that the efficiency scales linearly with fan speed, which does not exactly fit real data.

**How do we want to solve it? Describe the solution you'd like**

The FlowMachineInterface will be partialized and an additional extended model should be implemented. This new model will allow for the specification of polynomial coefficients, that characterise real or cfd-simulated data.

**Describe alternatives you've considered**

An alternate solution is to provide discrete performance points which form the performance map and interpolate between those points. Depending on the resolution of the points this can lead to inaccuracies or suboptimal equations.

**Comment by KremerMartin** [comment]
@PhOstmann I would advise you to open a corresponding issue in the IBPSA soon, as the change on the existing `FlowMachineInterface `will affect the IBPSA. You could ask, whether it would be ok to implement a `PartialFlowMachineInterface` from which the existing `FlowMachineInterface` will extend. You will only need to provide the In- and Outputs in the partial model. The rest can be set by the existing model and your new model. Duplicate parts should always be in the partial model.
If any questions or help needed, feel free to bother me. ;)

**Comment by MartinRaetz** [comment]
@PhOstmann 
Is there a status update?
Should this Issue remain active?

**Comment by PhOstmann** [comment]
This issue can be closed.
The whole topic will be adressed in a new issue in the context of a bachelors/masters thesis, once a suitable candidate is found.
