### ISSUE TITLE
Alternative pipe model

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#910]
**What is the problem?**

Currently, the aixlib contains the pip 'PlugFlowPipe', which has problems with heat transfer and the model 'Pipe', which bases on the MSL pipe model.

**How do we want to solve it? Describe the solution you'd like**

- We want to create a simple discretized pipe model that includes n volumes and the 'HydraulicDiameter' as well as a radial heat transfer.
- Integrate the `PlugFlowPipe` and the new `SimplePipe` into a `GenericPipe` model with records for pipe size and insulation.

**Comment by alexanderAKU** [comment]
I created a first version of the pipe model.
Further steps:

- [ ] Documentation
- [ ] Example
- [ ] Discussion about heat losses (see below)

**Comment by alexanderAKU** [comment]
@TobiasBlacha I created a simple pipe with n volume elements and a resistance. I can add a heat transfer. However, the model 'Pipe'  already includes different heat transfer models. Thus, we could include the 'simplePipe' as an additional option or replace the MSL pipe. Additiolly, we could include the plugFlowPipe as an option.

**Comment by TobiasBlacha** [comment]
@alexanderAKU I think this depends on where the new pipe model will be used. If pipes are to be replaced in existing models, we have to check whether they require heat transfer.  I think the additional option of heat transfer is useful in general.

**Comment by alexanderAKU** [comment]
merged  into development

**Comment by alexanderAKU** [comment]
- [ ] delete 0 insulation record

- [ ] make insulation conditional in generic pipe model

**Comment by PMehrfeld** [comment]
@alexanderAKU : Is the last ToDo done?
