### ISSUE TITLE
Renaming of bus variables for ThermalMachineControlBus

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#912]
**What is the problem?**

- In bus connector `AixLib.Controls.Interfaces.ThermalMachineControlBus` variables are not up to date with our latest naming conventions for bus variables.

**How do we want to solve it? Describe the solution you'd like**

- [x] Refactor variable names
- [x] Include conversion script
- [x] Raise AixLib version number

**Comment by FWuellhorst** [comment]
Additionally, we will refactor two things:

- [ ] Security -> Safety
- [ ] ThermalMachine -> VapourCompressionMachine
