### ISSUE TITLE
HTML error in development

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#919]
As mentioned in [this comment](https://github.com/RWTH-EBC/AixLib/commit/82e9d5bbe6f246511b099b174bf4a6c35dda1a47#commitcomment-39173519), I introduced by accident a HTML error into the development.

This is a debugging for `development` not `master`.

**Comment by MartinRaetz** [comment]
Closed with https://github.com/RWTH-EBC/AixLib/pull/920
