### ISSUE TITLE
Merge IBPSA v3.0.0

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#927]
**What is the problem?**

- The latest version of the IBPSA library is not included in the AixLib

**How do we want to solve it? Describe the solution you'd like**

- Merge the IBPSA libraray

**Comment by PMehrfeld** [comment]
@alexanderAKU: Thanks a lot for your work here. Please make sure to have an eye on this [issue ](https://github.com/ibpsa/modelica-ibpsa/issues/1371)and the according [PR ](https://github.com/ibpsa/modelica-ibpsa/pull/1372)in IBPSA.  
Maybe wait for the merge there and do the IBPSA->AixLib merge afterwards?!

**Comment by alexanderAKU** [comment]
We will wait for the IBPSA issues.

However, I want to merge the threeWayValveTable. Therefore, I will create a new branch, where only the valve model and related files will be added/changed.

**Comment by alexanderAKU** [comment]
Three way table based valve is merged into development.

**Comment by XucYin** [comment]
Just as a hint: It seems that the IBPSA issue Philipp mentioned is closed. IBPSA v 3.0.0 is already released.

**Comment by MartinRaetz** [comment]
@alexanderAKU 
Is there a status update?

**Comment by alexanderAKU** [comment]
@MartinRaetz not from my side. I remember to have some trouble with the python scirpts. Feel free to merge the library :)

**Comment by DaJansenGit** [comment]
this will be done by automatic ibpsa merge:
https://github.com/RWTH-EBC/AixLib/issues/802
