### ISSUE TITLE
Unit test in package AixLib.Fluid.Movers.PumpsPolynomialBased.Examples

### ISSUE THREAD

**Issue by SvenHinrichs** [RWTH-EBC/AixLib#962]
**What is the problem?**

- Error when setting up unit tests for package AixLib.Fluid.Movers.PumpsPolynomialBased.Examples

**How do we want to solve it?**
- The package structure is not correct. For this reason the folder structure should be corrected.

**Comment by alexanderAKU** [comment]
@DaJansenGit and @SvenHinrichs : what is the current status of this issue? I figured out some problems with the pump due to many initial values. I wanted to create a new issue for that problem, but I could also work in this branch/issue.

**Comment by SvenHinrichs** [comment]
@alexanderAKU :  For this issue I have added necessary information to the .mos scripts and the annotation section of the models for the regression test. If you need to readjust certain values or parameters, it would be very useful to continue working in this branch, as the reference files will then be out of date and should be recreated. So feel free to work in this branch.

**Comment by alexanderAKU** [comment]
@SvenHinrichs I modified the pump model and removed some start conditions and the MSL system properties. You can proceed with the unit tests now, if needed

**Comment by DaJansenGit** [comment]
@alexanderAKU Could you
* [ ] delete the old .mos scripts in `AixLib\Resources\Scripts\Dymola\Fluid\Movers\PumpsPolynomialBased\Examples` and create new ones for the new models? You know the model better than Sven or me.
@SvenHinrichs After the new .mos scripts are created, you could then 
* [ ] create the missing reference results

Thanks to both of you :)
