### ISSUE TITLE
AixLib.FastHVAC.Components.Storage.HeatStorageVariablePorts: Parameters not propagated

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#966]
### Describe the bug
Parameters of `top_cover`, `storage_mantle[n]`, and `bottom_cover` are not propagated.

This is for the two models:
- AixLib.FastHVAC.Components.Storage.HeatStorage
- AixLib.FastHVAC.Components.Storage.HeatStorageVariablePorts

Is the HeatStorage without variable ports even still necessary?

### Approach to solve issue
1. Propagate parameters of `data` according to `AixLib.Fluid.Storage.BufferStorage`

**Comment by DaJansenGit** [comment]
Thanks for the bug description. I will solve this on Hackday tomorrow.

**Comment by DaJansenGit** [comment]
`AixLib.FastHVAC.Components.Storage.HeatStorage` isn't used in any other AixLib model and the `AixLib.FastHVAC.Components.Storage.HeatStorageVariablePorts` provides all functionality of the basic model.
As the models don't extend from each other, I would suggest to delete the basic model.
