### ISSUE TITLE
HOM: empirical validation

### ISSUE THREAD

**Issue by konstantinaxanthopoulou** [RWTH-EBC/AixLib#967]
**What is the problem?**

In order to validate the HOM of the `AixLib` empirically the calculated results should be compared to data from real buildings, test cells or laboratory experiments.

**How do we want to solve it? Describe the solution you'd like**

Add examples from real buildings to compare simulation results with measurement data.

**Comment by MartinRaetz** [comment]
@konstantinaxanthopoulou 
Is there a status update?
Could the conflicting files be solved?

**Comment by PMehrfeld** [comment]
Thanks for reminding us. I will talk to @konstantinaxanthopoulou. Additionally, I added myself as assignee as well.

**Comment by PMehrfeld** [comment]
Closed by #1017
