### ISSUE TITLE
Graphics in Dymola 2016

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#97]
It seems that annotations have been changed in Dymola 2016. As a consequence, the graphics e.g. in LOM are in some parts corrupt. As example, the black connection lines of star connections do not work any more.

**Comment by PMehrfeld** [comment]
You have to remove the modifier "pattern=LinePattern.None" in the connect annotation in order to get back the grey line of the star connections. When you draw new star connections you directly have visible lines.

**Comment by thorade** [comment]
also see discussion here
https://github.com/iea-annex60/modelica-annex60/issues/220
