### ISSUE TITLE
Readme git clone command

### ISSUE THREAD

**Issue by Maghnie** [RWTH-EBC/AixLib#971]
**What is the problem?**

`git clone` command in README.md leads to another repository

**How do we want to solve it? Describe the solution you'd like**

Let clone command point to AixLib with `git clone --recurse-submodules https://github.com/RWTH-EBC/AixLib.git`

**Comment by Maghnie** [comment]
Everyone, I'm working on this.

**Comment by DaJansenGit** [comment]
seems to be a copy paste issue :) @Maghnie If you are working on this, you can assign your self, via the assignees buttom :)
