### ISSUE TITLE
Correct HOM VoWo models according to partialRoom model

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#978]
**What is the problem?**

- [x] VoWo room models in `AixLib.ThermalZones.HighOrder.Rooms.MFD.OneAppartment` do not extend from `AixLib.ThermalZones.HighOrder.Rooms.BaseClasses.PartialRoom` yet.
- [x] Examples do not work: `AixLib.ThermalZones.HighOrder.Examples.Appartment_VoWo` (and `AixLib.ThermalZones.HighOrder.Examples.RoomGFOw2_DayNightMode` (--> Solved in other branch/issue)

**How do we want to solve it? Describe the solution you'd like**

- Extend from partial room model
- Correct examples
- Add regression (unit) tests

**Comment by FWuellhorst** [comment]
Affected issues: #1123

**Comment by FWuellhorst** [comment]
@KremerMartin @DaJansenGit @PMehrfeld :
Looking at this further I found the model does neither follow AixLib guidelines nor uses English. Further, the example uses obsolete pump models. I don't see the benefit in updating everything, as this model is obviously not used anymore. I guess the update time would be at least 8 h, checking if everything still works and we don't introduce errors. 
Time which we can better invest into other open issues.

Hence, I would opt to move it to obsolete.

**Comment by KremerMartin** [comment]
@FWuellhorst @DaJansenGit @PMehrfeld :
I agree with @FWuellhorst . The model `AixLib.ThermalZones.HighOrder.Rooms.MFD.OneAppartment` seems pretty outdated. An update would be very time-consuming. If there are some capacities free, it could be tackled during a hackday. Otherwise I would also move it to obsolete.

**Comment by DaJansenGit** [comment]
With a quick look over the model, it seems to me that we have enough examples with OFD. So I would agree with Fabian and Martin and move `AixLib.ThermalZones.HighOrder.Rooms.MFD.OneAppartment` to obsolete. Of course, if someone wants to use it in the future, he/she can bring it back to life :)

**Comment by tobinfiedler** [comment]
@FWuellhorst @DaJansenGit @KremerMartin Can we close this issue?

**Comment by FWuellhorst** [comment]
Nope, we have to move them to obsolete. I can deal with this tomorrow!
