### ISSUE TITLE
FastHVAC - HeatStorageVariablePorts: no effect in changing tau

### ISSUE THREAD

**Issue by jwalbrunn** [RWTH-EBC/AixLib#988]
**Describe the bug**
There is no effect in changing tau (time constant for mixing) at component AixLib.FastHVAC.Components.Storage.HeatStorageVariablePorts.
I tried 1, 1000 (default) and 10000000 - no influence in simulation results.

**To Reproduce**
1. Go to 'AixLib.FastHVAC.Examples.Storage'
2. Click on 'BufferStorageVariablePorts'
3. Start simulation with different values for tau (1, 1000, 10000000)
4. Watch results (HeatStorageVariablePorts.T_layers[1-10]

**Expected behavior**
Different behaviour of temperatures in the layers according to tau

**Desktop (please complete the following information):**
 - Simulation environment and version: OpenModelica v1.16.0-dev.03
 - Simulation environment and version: Dymola Version 2020x (64-bit), 2019-10-10
 - AixLib 0.10.1

**Additional context**
I also tried it in a simulation which model I created on my own.

**Comment by jwalbrunn** [comment]
Additional context:
* I updeted to 0.10.2 and there is also no change

**Comment by DaJansenGit** [comment]
Thanks for the issue! You are right, the `tau` parameters seems to be a relict of former models and is not used anymore. The mixing is affected by the selected `HeatTransfer`. I removed the parameter in https://github.com/RWTH-EBC/AixLib/pull/993
