### ISSUE TITLE
CHP without controller

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#990]
**What is the problem?**

- The chp model `AixLib.Fluid.BoilerCHP.CHP` has an internal controller. Thus, the part load rate cannot be set directly by an external control.

**How do we want to solve it? Describe the solution you'd like**

- Create a modified version without an internal controller

**Describe alternatives you've considered**

The model `AixLib.Fluid.BoilerCHP.ModularCHP.ModularCHPIntegrated` is probably to complex for the use in large scale systems.

**Comment by MartinRaetz** [comment]
@alexanderAKU 
Is there a status update?
Should this Issue remain active?

**Comment by PMehrfeld** [comment]
@alexanderAKU: From my understanding this issue is done with the merge of PR #1141. Please reopen if this is not the case.
