### ISSUE TITLE
[패스트캠퍼스 수강 후기] {UX/UI 디자인 올인원 패키지 Online} 100% 환급 챌린지 {1} 회차 미션

### ISSUE THREAD

**Issue by dltndjs01** [RWTH-EBC/AixLib#992]
<img width="2048" alt="1" src="https://user-images.githubusercontent.com/65386366/92366656-65fc9e00-f130-11ea-9092-e1bd7956597f.png">
<img width="2048" alt="2" src="https://user-images.githubusercontent.com/65386366/92366665-68f78e80-f130-11ea-905c-ef099ebaa3f5.png">
<img width="2048" alt="3" src="https://user-images.githubusercontent.com/65386366/92366672-6b59e880-f130-11ea-9e66-41b4ebe041f1.png">

# ch01. UX디자인 시작하기
학습 목차
1. UX디자인의 시작
- UX에 대한 간단한 소개와 Technology의 발전

오늘은 UX/UI 올인원 패키지로 시작하는 100%환급 챌린지 첫날이다.
시작 강의로는 20년을 UX 디자인을 해오신 강사님의 간단한 소개부터 시작해 UX 디자이너가 하는 일에 대해 알려주셨다. 리서치부터 시작해 컨셉 잡고 디자인하는 것 뿐만 아니라 풀시나리오 작업, 프로토타이핑, UT까지 필드 영역이 이것도 디자이너의 일인가? 싶을만큼 넓은 영역의 일들까지 포함되어있다.
UX의 정의는 쉬운 것 같지만 20년차 UX디자이너도 어렵다고 말하는 것이 UX의 정의다. 전문가마다 다른 정의들이 있고 그 정의들이 틀리지 않다는 것에 정의내리는 어려움이 있다.
그러므로 나만의 정의를 정립하는 것 또한 UX디자이너로 필요한 일 중 하나라 생각한다.
 
UXUI를 사용하는 사람들을 User라 칭하고 이 유저들의 경험을 중요하게 여긴다. UXUI의 탄생은 기기를 사용하는 유저들이 보다 편리하게 직관적으로 기기를 사용할 수 있을까?의 고민에서 출발하기 때문이다. 
유저들에게 서비스를 제공하는 입장인 디자이너에겐 사용자의 맨탈 모델을 잘 이해하는 것이 중요하다.
디자인을 하기 전 리서치 단계에서 사용자들의 Mental Model, Conceptual Model을 시의적절하게 캐치해야 한다. 
선생님은 적절하게 코끼리의 그림으로 예시를 해줬다. 사용자가 코끼리의 코를 설명하는데 디자이너는 코끼리의 귀를 생각하는 것은 결코 좋은 결과물을 내기 어려울 것이다. 또한 사용자들의 보편적인 생각을 캐치 하는 것 또한 중요하다.
그러나 명심해야할 것은 멘탈모델은 불안정하며 늘 변하는 것이다. 즉 업데이트 된 서비스에 반응해 멘탈모델도 진화(?)한다고 봐도 무방할 듯 하다.

각각의 분야의 디자이너들마다 더 강조되는 역량이 있겠지만, UXUI 디자이너에게 가장 우선적으로 필요한 역량은 커뮤니케이션, 그 중 공감성을 필요로 한다. 그 공감성을 바탕으로 Conceptual Model를 잘 만들어야  할 것이다.

# ch.08 SKETCH/MARVEL/ZEPLIN
학습목차
2.스케치 시작하기 
-기본 UI구성 살펴보기

평소 스케치를 사용하지만 기본적인 부분 밖에 알지못한다. UX 개념에 이어 스케치의 기본기 이상을 다지기 위해 스케치에 대해 공부하였다. 스케치 여자 강사님이 기본 부분인 메뉴바,  툴바, 레이어리스트,페이지리스트와 단축키에 대하여 알려주셨다. 페이지 리스트, 레이어리스트를 함께 살펴보면 페이지리스트는 심볼과 아트보드 각각이 모여있는 곳이다. 실무에서 UI 기획서가 회원가입, 로그인, 메인, 설정 등으로 되어있다면 페이지 리스트에서도 회원가입, 로그인 등등 순으로 구성한다. 페이지리스트를 설정하면 화면 구성이 많은 페이지일 때 원하는 페이지 구성을 빠르게 찾아 접근할 수 있다.

페이지 리스트는 우측 플러스 버튼을 눌러 추가 가능하고 이름 설정으로 편하게 확인 가능하다. 아트보드나 오브젝트를 cmd +D를 눌러 바로 붙여넣기가 가능하다. 또한 오브젝트를 옮긴 후 CMD+D 를 누르면 명령이 반복된다.

Resize to fit
 현재 아트보드에 올려진 최상단과 최하단의 길이에 맞게 사이즈가 조절된다.

Ungroup
아트보드 위에 오브젝트만 놔누고 아트보드 삭제시 ungroup을 눌러주면 된다.

화면축소
Cmd + Z,클릭

화면 확대
Cmd + opt, 클릭

실제 사이즈
Cmd + 0 (숫자)

**Comment by DaJansenGit** [comment]
spam

**Comment by dltndjs01** [comment]
> spam

excused me sir, but I am doing my project. so don't close it.
