### ISSUE TITLE
Create contribute.md instead of wiki entry

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/AixLib#999]
We should move our how to contribute description from wiki (https://github.com/RWTH-EBC/AixLib/wiki/Contribute-to-AixLib) to a contribute.md file.

**Comment by DaJansenGit** [comment]
the file already exists here I just saw:
https://github.com/RWTH-EBC/AixLib/blob/development/.github/CONTRIBUTING.md

we might move to top level...

**Comment by MartinRaetz** [comment]
@DaJansenGit 
Should this issue remain open?
Help wanted?

**Comment by DaJansenGit** [comment]
this can be closed. Everything works fine and logged in github useres without contributions to aixlib see a "Want to contribute" welcome screen in issue section. Nothing to be changed here :)
